### ISSUE TITLE
リスト画面での検索項目

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#1]
## 概要
仕様書version1の8.2.リスト画面の検索項目について。
患者リスト表示モード、腫瘍登録管理表示モードでは検索できる項目が異なるが、具体的な項目は決まっていない。
登録年次、がん種などは両モードで検索したいが、それ以外については細かいニーズが不明。
若手の先生達に確認が必要。

**Comment by kosaka-hokuto** [comment]
β版では登録年次、がん腫の検索を行えるようにします。決まっている項目があればスケジュールに応じて実装します。

**Comment by kosaka-hokuto** [comment]
登録年次は癌種毎の診断日の一番古い日付になると考えておりますが、卵巣がんにはありません。
Schemaを修正するか、症例テーブルに登録年次を保存するカラムを追加になると考えています。
抽出や検索ロジックをシンプルにするためには症例テーブルに持つ方が良いのですが、運用上の懸念はございますか。
