### ISSUE TITLE
症例入力画面デザイン

### ISSUE THREAD

**Issue by yoshiaki-hokuto** [jesgo-toitu/jesgo-frontend#10]
2/28 WGにてデザインについての議題あり。次回お打合せ時に議論させて頂く。
縦に項目の羅列は可読性が良くなく、スクロールも大きくなるため項目を横に配置するレイアウト案を検討する。

現在の仕組みで実現できる方法で入力項目の横並びレイアウトを作成。
配列Widget（＋ボタンで複数追加できるWidget）と、オブジェクトWidget（複数Widgetのグループ）で横並びに
要求仕様の"jesgo:ui:subschemastyle:column"にあたる。
※Widgetの幅は自動調整です。1枚目の子宮頸がんで症例が長くなっているのは、注釈の長さに引きずられています。
2枚目の腫瘍最大腫瘍径では、おそらくそれぞれの選択肢の幅に基づいています。Windowの幅が縮んで入りきらない場合は改行されます。

No.1
![image](https://user-images.githubusercontent.com/98301499/156513444-00425512-267b-4948-995e-ba65b5555f41.png)

No.2
![image](https://user-images.githubusercontent.com/98301499/156513555-a24b1157-1939-4c57-a444-4d5ac1cd005a.png)

No.3
![image](https://user-images.githubusercontent.com/98301499/156513616-b297d49b-b1e4-426d-95d6-f62fd931cf96.png)

**Comment by yoshiaki-hokuto** [comment]
横並びレイアウトの他に行間や文字サイズも調整
・患者情報エリア（ヘッダ）の余白調整
・コントロールボタンと表示エリアを横並びにする
・見出し（アンダーバーのあるタイトル）フォントを小さく
・注釈を？アイコンのツールチップ化
　└要求仕様書にある対応。暫定対応なので、ルートの注釈は未対応

対応前
![image](https://user-images.githubusercontent.com/98301499/156516305-e857da3d-4ed6-4c5f-aba8-9faf250dc488.png)

対応後
![image](https://user-images.githubusercontent.com/98301499/156516351-a2f3dc22-c092-400e-91b8-72c679316ac5.png)

**Comment by toitu-nomura** [comment]
サンプル画像、ありがとうございます。
横並びと注釈を「？」にするだけでもスッキリしますね！

**Comment by piyotaicho** [comment]
若手の先生から、タブをもう少し使ってスクロールの長さを抑えたいという意見も出ました。

**Comment by piyotaicho** [comment]
あと、descriptionの展開で"\n"で改行をいれていただけると幸いです。

**Comment by piyotaicho** [comment]
タブを使ってスクロールの長さを抑える件については、スキーマ設定でできそうなので修正します。

**Comment by saso-hokuto** [comment]
2022/03/04打ち合わせ結果
アプリでの横並び対応と、スキーマの構成変更で縦スクロールをなるべく減らす方向とします。

**Comment by saso-hokuto** [comment]
2022/03/10打ち合わせ結果
HTML表記の使用はdescriptionのみとし、対象タグは`<br>`,`<sup>`,`<sub>`とします。
β版では少なくとも`<br>`については対応します。
