### ISSUE TITLE
通常のテキストボックスに選択肢が出てしまう問題

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#100]
### 課題
https://github.com/jesgo-toitu/jesgo-frontend/issues/92#issuecomment-1164707638
上記課題のコメントより
手術療法の手術時間は通常のテキストボックスのはずなのに「333」という選択肢が表示されてしまう

### 原因
以前入力した値がブラウザのオートコンプリート機能で表示されていると考えます

###  対応
コントロールにautocomplete="off" の属性を追加する
→uiSchemaに`ui:autocomplete`を設定する

**Comment by piyotaicho** [comment]
ソフトウェアの性格的にコントロールのautocompleteは基本的に全部offでよいかと思います。スキーマに設定する必要もないかと考えます。
よほど希望があれば許容すれば良いと思いますが、原則的には施設で希望がある内容は術者などが想定されます。それは施設でのスキーマ継承で
```
"items": {
  "type": "string"
}
```
を
```
"items": {
  "type": "string",
  "enum": [
    "山田",
    "桂",
    "林家"
  ]
}
```
とタイプの変化のないリストなどに拡張して貰えばよいかと思います。

**Comment by hsc-morita** [comment]
言葉足らずで申し訳ありません。
`ui:autocomplete=off`はハードコードで一律設定するようにいたしますので、スキーマファイルへの追加は不要となります。
実装中のブランチ：https://github.com/jesgo-toitu/jesgo-frontend/commit/896756949eb33fbb650fb56857fd3d22779e1151
現在評価中ですが、今のところ特に問題なく動作しております。
どうしてもリストにしたいケースについては承知しました。
