### ISSUE TITLE
JSONスキーマのtitle,subtitleについて

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#11]
## 概要
要求仕様 4.3.3. ドキュメントスキーマテーブル の説明にて、以下記載があります。
こちらについていくつか確認させてください。

> スキーマの規定するドキュメント種別を示すためtitleが利用される。スキーマ中の"title"が利用されるが、title中にwhitespaceがあるばあい、最初のwhitespaceまでをtitleに格納され、whitespace以降がsubtitleに格納される。スキーマの"title"命名についてはこの点を十分留意して行う必要がある。

- 「スキーマの規定するドキュメント種別」とありますが、「ドキュメント種別」とはどのような種別でしょうか。また、なんの機能に対して使われる種別でしょうか。
- 現在のプロトタイプでは、スキーマ中のtitleにwhitespaceがある場合でも、スキーマのtitleをそのままドキュメントのタイトルとして使用しています。
  DBのtitleカラムだけにすると、「患者台帳 子宮頸がん」「患者台帳 子宮体がん」などの見分けがつかなくなるためこのような対応としましたが、最終的にはtitleカラム（「患者台帳」）の値のみがタイトルとして使われる想定でしょうか。

**Comment by piyotaicho** [comment]
titleはレコードにかかわる大きなドキュメントを生成するときに使います。subtitleは…使い道ないですね。  
```
{
  "title": "foo bar",
  "jesgo:parentschema": "/schema/CC/root"
  "properties": {
    "john": {
       "const": "doe"
   }
}
```
から生成されたjsonドキュメント
```
{ 
  "john": "doe"
}
```
があったとします。  
プラグインがレコードの全部の情報を要求した場合プラグインには以下のようなjsonドキュメントが提供されます。
```
[
  {
    "case_id": "000000",
    ... レコードの内容...
   "患者台帳": {
      // /schema/CC/rootのtitleは"患者台帳 子宮頸がん"ですが、ドキュメントの種別が"患者台帳"なのでここはこう展開されます
      ...もろもろ...
      "foo": {
         "john": "doe"
      },
      // 上記のドキュメントは "foo" という種別になり、ドキュメントの種別がドキュメントのプロパティ名となります。
      ...もろもろ...
   }
  }
]
```
このようにデータベース中に分散したドキュメントを巨大な1つのドキュメントに再編成するときにproperty nameとして利用されるのが「ドキュメント種別であるtitle」となります。

**Comment by piyotaicho** [comment]
入力フォーム生成の時には、"title"が使用されます。

**Comment by saso-hokuto** [comment]
補足
入力フォームのタイトルには、DBのtitleではなく、jsonスキーマのtitle（whitespaceで分割前のもの）が使用される。
