### ISSUE TITLE
ZIPファイルのアップロードが正常にいかないことがある

### ISSUE THREAD

**Issue by kosaka-hokuto** [jesgo-toitu/jesgo-frontend#111]
一部のファイル(大きいファイル、日本語名を含むファイル)をアップロードした際に、アップロード処理が終わらなかったり、サーバーが異常終了したりすることがある。

**Comment by piyotaicho** [comment]
- 大きいファイル対策   
いっそのことファイルサイズについては最大のサイズを規定するのはどうでしょう？
クライアント側で確認してからアップロードするようにすれば良いかと思います。巨大なファイルを指定してクライアントが落ちるくらいなら悪戯対策にも良いでしょう。
サーバー側にでもコネクションタイムアウトを設けた方が安全ですね（デフォルトでは数分ですよね）。
クライアント側もコネクションが切れることを前提にアップロード系についてはタイムアウト処理を入れた方が良いでしょう。

- 日本語ファイル名対策   
ZIP内の日本語ファイル名については、一旦テンポラリに解凍してからロードするという手法をとっているので仕方が無い気もします。WindowsがZIP圧縮の際にファイル名をCP932で保存するのでリスクは高いですね。
まずは仕様で禁止して、根本的にはnode unzipperのparse.jsにEncodingを使ってファイル名をきちんとuft8に変換するパッチをあてる必要がありますね。

**Comment by hsc-morita** [comment]
対応済み
