### ISSUE TITLE
スキーマアップロード時のエラー表示について

### ISSUE THREAD

**Issue by kosaka-hokuto** [jesgo-toitu/jesgo-frontend#112]
[#88 (comment)](https://github.com/jesgo-toitu/jesgo-frontend/issues/88#issuecomment-1157788397)
上記課題のコメントより

- スキーマをインポートする際にエラーが発生した場合も、一度すべてのスキーマを精査した上でエラーの一覧を表示する(途中中断しない)
  - エラーが発生したスキーマ以外は登録が行なわれる、スキーマ同士の関係性が異常なスキーマが登録されることがある(親が存在しない子スキーマ等)
  - 上記処理により、スキーマ同士の関係性が異常なスキーマが登録されていても、後にエラーを解消したスキーマをアップロードすることで関係性のエラーを解決することができる(正常に登録していたスキーマを再登録する必要はない)
    - その上で新たに親子関係におけるエラーが発生することも考えられる、その場合はその関係性のみが登録されない(各々のスキーマ自体は登録されるが、継承関係にならない等)。その場合は改めてエラーの一覧が表示される
- エラーが発生した際には該当ファイルの$IDを表示する
- エラーに関してはアラートで表示せず、画面上に表示する(アラートだと閉じてしまうと確認できないため)

**Comment by piyotaicho** [comment]
- エラーが発生した際には該当ファイルの$IDを表示する   
にはユーザのレベルにあわせてファイル名も表示しては如何でしょうか？

**Comment by kosaka-hokuto** [comment]
スキーマ登録の物に関してはファイル名を表示するようにします。
スキーマ同士関係性の更新はDBに登録されているもの全体で整合性を取る関係上今回アップロードしたスキーマ以外もエラーが発生し得るため、表示方法を考慮します。

**Comment by piyotaicho** [comment]
ファイル名も併記したほうがよいという意味でしたごめんなさい。

**Comment by kosaka-hokuto** [comment]
ローディング画面表示前に既存のエラー一覧を非表示にする必要あり。

**Comment by hsc-morita** [comment]
9/16状況
`ローディング画面表示前に既存のエラー一覧を非表示にする必要あり。`
→上記の件未対応
