### ISSUE TITLE
ツリー表示における継承スキーマの表示有無について

### ISSUE THREAD

**Issue by kosaka-hokuto** [jesgo-toitu/jesgo-frontend#117]
## 概要
スキーマ管理画面におけるツリー表示では継承スキーマに関しては表示すべきでしょうか。
[#68コメント欄](https://github.com/jesgo-toitu/jesgo-frontend/issues/68#issuecomment-1131853970)にて、継承スキーマが独自に subschema, childschema を持つことは許容されるべきとのことですが、
その場合すべての継承スキーマに対しても下位スキーマを表示することになり表示が若干煩雑にならないかを懸念しております。

```
▼親スキーマ
　▼子スキーマ本体
　　▶孫スキーマ1
　　▷孫スキーマ2
　▼子スキーマ継承1
　　▶孫スキーマ1
　　▷孫スキーマ2
　▼子スキーマ継承2
　　▶孫スキーマ1
　　▶孫スキーマ3
　　▷孫スキーマ2
　　
// 孫スキーマ1,2は子スキーマ本体、継承先それぞれで共通だが、独自に設定される可能性もあるため全表示
```

こちら、煩雑になってもすべての継承スキーマをツリー表示するべきでしょうか。
それとも現在基底設定されている(基底継承関係並び替えで一番上になっている)スキーマのみ表示等にした方がよろしいでしょうか。

**Comment by piyotaicho** [comment]
この部分はカスタマイズのキモになるのでツリー表示は煩雑になっても良いと思います。
最終的に入力でも煩雑で困る場合は、親の方から表示するものを選んでもらえればよいのです。この辺を含めてもカスタマイズと考えています。

ただ、闇雲に煩雑になってしまうのは確かに問題ですし、継承スキーマと基底スキーマが区別しづらいのもありますね。
表示方法についてはスキーマ管理をリリースしてから意見を求めていっても良いかと思います。

**Comment by kosaka-hokuto** [comment]
了解致しました、取り急ぎ基底設定のスキーマのみ表示を行い、余裕があれば全表示も確認できる形で一度お出ししたいと思います。

**Comment by hsc-morita** [comment]
9/16状況
- 継承スキーマの表示まで対応済み
