### ISSUE TITLE
"jesgo:ui:listtype"によるコンボボックスの仕様について

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#118]
現在"jesgo:ui:listtype"によるコンボボックスの実装を行っております。
いくつか要求仕様から変更したい箇所がございますので、お忙しいところ恐れ入りますがご確認お願い致します。

### 1. コンボボックス内の選択肢検索仕様について
要求仕様には`文字列による前方一致検索`と記載されておりますが、部分一致の方が使いやすいと考えております。
部分一致検索に変更してもよろしいでしょうか？

### 2. patternによる入力値の制限について
要求仕様に`"combo"では以下のようにスキーマを記載し、自由入力でのエラーを回避する。` として
pattern(正規表現)指定による回避方法が提示されておりますが
コンボ用のvalidationを実装しなければ特にエラーになりませんので
自由入力でのエラー回避が目的でしたらpatternでのvalidationを実装しない方向とさせていただきたいのですがよろしいでしょうか？

上記2点の仕様で問題なければ以下の仕様となります。
認識違い等ございましたらご指摘願います。
- コンボボックスにする場合、リスト値はoneOfもしくはanyOfの中のoneOfで定義する
- oneOf、anyOf中にpatternを記述してもvalidationは行わない
- "jesgo:ui:listtype"が"combo"の場合、選択肢の検索は行わず全ての選択肢を表示する
- "jesgo:ui:listtype"が"suggestlist"、"suggestcombo"の場合、部分一致検索で選択肢を絞り込む
	- 階層表示の場合、検索された項目の親となるグループ名も表示する
- "jesgo:ui:listtype"が"suggestlist"の場合、フリー入力不可とする
	- 選択肢にない項目が入力されるとフォーカスアウト時にクリアする
	- "combo"、"suggestcombo"の場合はフリー入力可

### 想定するコンボ用スキーマ記述方法サンプル
```
"プルダウンリスト(通常の単一select)": {
  "type": "string",
  "enum": [
    "選択肢1",
    "選択肢2",
    "選択肢3"
  ]
},
"コンボボックス(フリー記載可)": {
  "type": "string",
  "jesgo:ui:listtype": "combo", // ←★listtype:combo指定
  "oneOf": [ // ←★oneOfの中にenum定義
    {
      "enum": [
        "選択肢1",
        "選択肢2",
        "選択肢3"
      ]
    }
  ]
},
"サジェストリスト(フリー記載不可)": { // ★suggestlistの場合、リストにない項目が入力されるとクリアされます
  "type": "string",
  "jesgo:ui:listtype": "suggestlist", // ←★listtype:suggestlist指定
  "oneOf": [
    {
      "enum": [
        "選択肢1",
        "選択肢2",
        "選択肢3"
      ]
    }
  ]
},
"サジェストコンボ(フリー記載可)": {
  "type": "string",
  "jesgo:ui:listtype": "suggestcombo", // ←★listtype:suggestcombo指定
  "oneOf": [
    {
      "enum": [
        "選択肢1",
        "選択肢2",
        "選択肢3"
      ]
    }
  ]
},
"階層表示コンボボックス(フリー記載可)": {
  "type": "string",
  "jesgo:ui:listtype": "combo", // ←★listtypeはsuggestlist、suggestcomboも指定可
  "oneOf": [
    {
      "const": "選択肢1"
    },
    {
      "const": "選択肢2",
      "title": "選択肢2-表示名"
    },
    {
      "title": "グループ1",
      "enum": [
        "選択肢3",
        "選択肢4"
      ]
    },
    {
      "title": "グループ2",
      "oneOf": [
        {
          "title": "グループ2-1",
          "enum": [
            "選択肢5",
            "選択肢6"
          ]
        },
        {
          "title": "グループ2-2",
          "enum": [
            "選択肢7",
            "選択肢8"
          ]
        }
      ]
    }
  ]
}
```

**Comment by piyotaicho** [comment]
- 部分一致検索はそれはそれで問題ありません。検索できれば良いでしょう（化学療法など選択枝が多すぎる位なので）
- スキーマの設定についてはcomboはあくまで自由入力なのでvalidation freeとして良いでしょう

**Comment by hsc-morita** [comment]
ご確認ありがとうございます。それでは上記仕様で対応いたします。

**Comment by hsc-morita** [comment]
#120 にて対応済み
