### ISSUE TITLE
アップデートのリリースについて

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#119]
施設からの質問などについてはこちらも特に受けていないのですが、
- combo/suggestの実装
- おおまかなスキーマ管理の実装
をもって一度アップデートをリリースしますか？施設側でのアップデートに関しての操作なども考えないといけないかとおもいますので。

**Comment by toitu-nomura** [comment]
[【JESGO】問合せ台帳.xlsx](https://github.com/jesgo-toitu/jesgo-frontend/files/9256623/JESGO.xlsx)
情報共有が漏れており、申し訳ございません。
弊社には環境構築に関することを中心に、お問合せが来ております。
現時点でのお問合せ一覧を添付いたします。
よろしくお願いたします。

**Comment by piyotaicho** [comment]
共有ありがとうございます。基本的なところで結構躓いていますね。
いま全ての施設で動いているようですが、今後は vsruntime は配布時に同梱しておいたほうがよさそうですね。

**Comment by toitu-nomura** [comment]
はい、vsruntimeについては2/5の施設でお問合せがありましたので
今後のリリースには同梱したいと思います。
また、QAにも記載しておきたいと考えています。

**Comment by toitu-nomura** [comment]
鳥取大)情報部様から、修正版にてサービス開始できたとのご連絡がありました。
今のところ、アップデートに関するお問い合わせは、
鳥取大様からの2件のみで、どちらも解決済みとなっております。
[【JESGO】問合せ台帳.xlsx](https://github.com/jesgo-toitu/jesgo-frontend/files/9827755/JESGO.xlsx)
