### ISSUE TITLE
継承スキーマについて

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#12]
## 概要
継承スキーマについて、二点確認させて下さい。
- 継承スキーマとして扱う条件は、以下であっていますか？
  - 自身の$idの一段上のパスを$idに持つドキュメントが存在する
    - 自身のが$id:"/schema/foo/bar"の場合、$id:"/schema/foo"のドキュメントがある
  - jesgo:baseversionが指定されている

- コントロールボタンでのドキュメントの切り替え時の動きは、以下であっていますか？
  - 基底スキーマ→拡張スキーマだけでなく、拡張スキーマ→基底スキーマも切り替え可能。
  - 切り替えた場合、child_schemaには切り替えた方のスキーマのみが登録される。

**Comment by piyotaicho** [comment]
・継承スキーマには命名規則があり '$id': '/schema/foo' がある場合、'$id': '/schema/foo/bar' は '/schema/foo' を継承したものとなります。逆説的ですが、ご指摘の通りです。
・jesgo:baseversion はまだ1つも設定していませんが、基底スキーマに改変があったときのトラブルを防ぐため継承スキーマでは必須としたいですね。
・コントロールボタンでの切り替えはご指摘の通りです。ただ、切り替え可能の選択肢としてあらわれるか否かもスキーマ管理でコントロール可能とします。（拡張スキーマが非表示ならば選択されない）

**Comment by saso-hokuto** [comment]
2022/03/10打ち合わせ結果
- （極端な例にはなりますが）今のスキーマ定義に'$id': '/schema/CC'というスキーマを追加した場合、その追加スキーマはCCフォルダにあるスキーマ（'$id': '/schema/CC/XX'）全ての基底スキーマとして扱われる、という解釈であっている。
