### ISSUE TITLE
patient-area の@media挙動

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#121]
今の今まで気にしていなかったというか、無視していましたが、画面の幅を縮小して行くと一番気になる問題が.patient-areaのようです。

Bootstrapが標準的に持っているCSSメディアクエリを利用しているようで、保存/保存してリストに戻る/ リストに戻るのボックス(.user-info-button-col)の挙動がちぐはぐになっています。

その他にCSSメディアクエリが入っているかは確認できていませんが、メディアクエリは消しておいた方が良いですね。

**Comment by hsc-morita** [comment]
> Bootstrapが標準的に持っているCSSメディアクエリを利用しているようで、保存/保存してリストに戻る/ リストに戻るのボックス(.user-info-button-col)の挙動がちぐはぐになっています。

これは保存/保存してリストに戻る/ リストに戻るボタンがウィンドウの拡縮状況に応じて
1段、2段、3段と不揃いな表示位置になるのが問題と捉えてよいでしょうか？

ボタングループをひとまとめで横並び(1段)にすることはできましたので、問題なければマージいたします。
PR：#129

※BootStrapのグリッドシステムによる`@media`はそのまま残しております

**Comment by hsc-morita** [comment]
画面縮小してもSubmitButtonグループが右端になるよう修正してマージ済み
