### ISSUE TITLE
デザインの調整

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#123]
使ってみるとドキュメント中のサブスキーマ（子ドキュメントではない）のタイトル(<legend>)がどうしても目立ちますね。
font-size: 1.3rem; でなくてlabelと一緒の14pxでよいかもしれません。

フレームワークを使っている宿命ですがスタイルシートの各種指定についてもそのうちどこかで整理したほうがよさそうです。

**Comment by hsc-morita** [comment]
14px(1.0rem)へ修正いたしました。

**Comment by hsc-morita** [comment]
マージ済み
