### ISSUE TITLE
development :  病期診断が保存されない

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#125]
特にエラーは起きていないようですが、保存されません。

**Comment by hsc-morita** [comment]
申し訳ございません。コンボボックス選択時に保存されない不具合がございましたのでPRを出しておりました。
先ほどdevelopmentにマージいたしましたので、最新版で今一度ご確認願います。
解消されない場合、またはコンボボックス以外の項目も保存できない場合はお手数をおかけしますがご一報願います。
