### ISSUE TITLE
β版導入方法

### ISSUE THREAD

**Issue by yoshiaki-hokuto** [jesgo-toitu/jesgo-frontend#13]
## β版導入方法について検討
1. Windowsに限定する
2. Dockerを使用する方法は断念
  - イメージのオフライン展開はDockerの概念から少し異なる
  - Docker for Desktopが有料
  - Windowsの機能を追加、Hyper-vなどBIOSの設定変更が場合によって発生する
3. インストールスクリプトを生成する方法
 - PostgreSQLはサイレントインストール
 - Node.jsはバイナリをZip展開する
 - JESGOアプリはZip展開し、IPアドレスなど必要な部分を手動で書き換えする
 - Webサーバーはwinserパッケージを使用してサービス登録することで常時稼働させる
     - サービス登録が一番安定稼働するが管理者権限が必要になる
 - DBバックアップはタスクスケジューラに登録（出力先は施設担当に編集してもらう）

**Comment by piyotaicho** [comment]
βの配布時点でインストーラとサーバの簡単なコンソールはあったほうがよいでしょう。  
当初予定している施設は大きいところが多いですが、施設担当者のレベルを決して信用してはいけません。場合によっては、医局内の「だれかがやる」というレベルも想定されます。インストーラがダウンロードできない、実行できないというレベルからありえます。  
  
さて、実行イメージですが、PostgreSQL、NodeJSともに*nix文化を引き継いでいますので、ディレクトリベースで展開して環境変数を適切に設定すれば稼働させられます。よって、JESGO全体のインストーラがあれば、それぞれのインストーラでのインストールをする必要はありません。  
ただし、WindowsはPOSIX準拠なのにchrootでプロセスからみえる構成を切り分けることができないので、NodeJSのFileで悪用されると困っちゃう点があります。なので、基本的な実行権限も一般ユーザとするのが妥当かと考えます。  
  
サービスの起動・停止について管理できるダイアログ1つの簡単なもので良いのでコンソールがあったほうがよいと思います。バックアップもコンソールが管理するもの、幸せな環境でタスクスケジューラから起動できるCLIと2通り用意しておくのが無難だと思います。
