### ISSUE TITLE
β+対応 8/31時点実装状況　※9/09更新

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#138]
8/31時点の実装完了分をdevelopmentにマージ済みです。
- フロント側、バックエンド側ともに更新があります
- バックエンド側に更新用SQLを用意しているため、お手数をおかけしますが手動で実行願います。
	- jesgo-backend\doc\DB\batch\beta1
		- 01_alter.sql
		- 02_update.sql

以下実装状況となります。
#### メイン機能
- jesgo:ui:listtypeによるチェックボックス、ラジオボタン、コンボボックスの対応  → **必要に応じてスキーマファイル修正必要あり**
- スキーマ管理画面
	- スキーマダウンロード機能
	- 継承スキーマの表示/非表示切り替え　→　**9/05 取り急ぎ表示切り替えは対応。並び替えはβ＋以降で実装予定**

#### 改善・バグ修正
- スキーマ関連のハードコーディング部分を修正 → **スキーマファイル修正必要あり**
- 登録拒否チェックボックスのキャプション修正(なし → 登録拒否)
- textboxのautocompleteをoff
- 患者情報を保存するまでドキュメントの作成抑止
- validationのメッセージをスキーマで指定できるよう対応 → **必要に応じてスキーマファイル修正必要あり**
- API通信時のエラーハンドリング強化
- 子タブの入力で親タブも強調表示する
- 必須項目入力後、赤枠での強調を解除
- スキーマアップロード時、更新エラーが発生しても中断せずに更新するよう対応
- 必須項目かつtitle指定ありの場合、validationの必須チェックに引っかからない問題を修正
- ウィンドウ縮小しても症例登録画面の保存ボタン群が右端になるよう対応
- objectの大項目名のフォントサイズを1.3remから1.0remに変更

### 修正中の不具合
- [x] #141 →　済
- [x] #144 → 済
- [x] スキーマ編集中にスキーマツリーをクリックした際、遷移をキャンセルしてもハイライトがクリックしたスキーマへ移る
※不具合は9/09までを目途に対応予定ですが、ハイライトの件は難度が不明のため見送る可能性があります
- [x] #147 → 済

**Comment by hsc-morita** [comment]
9/09追記
バグ修正含め現状の最新をdevelopmentブランチに反映いたしました。(フロント、バックエンド共に)
現在はアップデート用のモジュールを精査中です。
なお下記のバグは対応を検討する必要があるため、申し訳ありませんが次回へ持ち越させてください
- #149

現状の動作で何かお気づきの点がございましたら、お手数をおかけしますがご一報いただきたく存じます。

**Comment by piyotaicho** [comment]
がまんすればよいだけで大したことではないのですが、required をもつスキーマが展開されたとき(例："/schema/treatment/operation_adverse_events")に必ずエラー表示が作成されるのはどうしましょう？

**Comment by piyotaicho** [comment]
現在"jesgo:ui:listtype": "buttons"の実装について確認をしています。

1. 例(1) array の選択肢 oneOf   
```
  "hoge": {
    "type": "array",
    "jesgo:ui:listtype": "buttons",
    "items": {
       "type": "string",
       "oneOf": [
         {
           "enum": [
             "A", "B", "C"
           ]
         }
       ]
     }
  }
```
の場合、"oneOf"なのでラジオボタン選択のアレイ入力が妥当と考えますが、ラジオボタンにはならないようです。

2. 例(2) array の anyOf   
```
  "hoge": {
    "type": "array",
    "jesgo:ui:listtype": "buttons",
    "items": {
       "type": "string",
       "anyOf": [
         {
           "enum": [
             "A", "B", "C"
           ]
         }
       ]
     }
  }
```
この場合のイメージでは、アレイ入力ではなく、チェックボックスが多数並ぶリスト形式に相当します。   
現在の実装では、チェックボックスが多数並ぶリスト表示がさらにアレイになり入れ子になってしまいます。

**Comment by piyotaicho** [comment]
今更感がありますが、デフォルトのスキーマの開始日設定を見直したいと思います。  
現在は登録日になっていますが、これだとスキーマ修正などを行った場合にeventdateがそれ以前だと展開されないことになり利便性の低下につながってしまうと思います。（これはテストでいろいろ食べさせていて強く感じました）

"jesgo:valid" が未指定の場合、開始日はepoch(1970-01-01)にして、同名idスキーマについて未指定の開始日は１日ずつずらしてゆくのが実装として今後スキーマのトラブル回避目的のアップデート配布などを通してもトラブルフリーを目指せるのではないかとおもいます。
この場合、問題はいま想定していない「現在使用しているスキーマよりも新しいスキーマが利用できるようになったことを検出する必要がある」と余計なロジックが増えますので議論が必要な部分かと思います。

このロジックについてはテストとして弄りましたので、backendのほうにPRを入れておきます。
https://github.com/jesgo-toitu/jesgo-backend/pull/22

**Comment by hsc-morita** [comment]
過去バージョンの課題のためクローズ
