### ISSUE TITLE
スキーマアップロードでzipをアップロードすると一部のスキーマが登録されない

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#147]
### 不具合内容
スキーマ管理画面からいくつかのスキーマファイルをzip圧縮してアップロードすると、登録件数が実際のファイル数より少なくなってしまう

### 原因
バックエンド側でのzip展開時、すべてのファイルが展開される前にファイル一覧を取得している。
→zip展開時にfinishイベントが来るまでawaitで待機してからファイル一覧を取得しているが、finishイベントの発火タイミングが早い？

**Comment by hsc-morita** [comment]
バックエンド側を修正
https://github.com/jesgo-toitu/jesgo-backend/pull/15

**Comment by hsc-morita** [comment]
@piyotaicho 
上記の登録されていなかったスキーマですが、β版リリース時点のDBバックアップにも登録されておりませんでした。
大変申し訳ございません。
つきましては以下の対応を行うことを検討しております。問題ございましたらご指摘願います。
#### 対応案
- β＋リリース時には一旦すべてのスキーマをアップロードしていただく
※既にアップロードが正常に行われているスキーマに関してはバージョンが新しくなっていない旨のエラーが出ますが
問題はありません、未登録のスキーマのみ追加で登録されます
- 未作成のサブスキーマはコントロールボタンから追加作成できるようにする
- 追加したサブスキーマは削除不可

**Comment by piyotaicho** [comment]
そっちの方は全く気づいていませんでした、手動で対応してもらう他ないですね。

**Comment by hsc-morita** [comment]
9/14追記
β版リリース時点のDBでも不足していたと記載いたしましたが、確認したバックアップDBが古く
実際のリリース時点のDBはすべて適応されておりました。大変失礼いたしました。

不足しているスキーマを手動で登録できるようにする対応はそのまま入れた状態といたします。

**Comment by piyotaicho** [comment]
こちらでもあれ？と思ったら入っていました。
