### ISSUE TITLE
スキーマで定義されるUIの種類について

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#15]
## 概要
開発側の都合で大変恐縮なのですが、使用しているライブラリの都合上、JSON schema 2019で準拠した定義全てにUIを表示対応することが大変難しいです。そのため、表示するUIとそれを表現するためのスキーマのフォーマットを決めておき、それ以外のスキーマ記述については動作保証外、としたいです。
現在、要求仕様に記載のあるパターンと、2022/1/4時点で受領したスキーマ定義にあるパターンについては対応予定です。

β版では、2022/1/4時点で受領したスキーマ定義にあるパターンを対応範囲とする予定です。
以下にそのパターンをあげました。
これ以外で追加の可能性があるパターンがありましたら、お手数ですが早めにお知らせいただけると助かります。

- type:string
  - 自由入力
  - 日付入力（カレンダー選択）
  - ドロップダウン（選択のみ）
  - ドロップダウン（選択のみ/選択肢の表示と中身の値が異なる）
  - ツリー構造でグループ化されたドロップダウン（選択のみ）

- type:number
  - 自由入力（上/下ボタンによるカウントアップ/ダウン付き）

- type:integer
  - 自由入力（上/下ボタンによるカウントアップ/ダウン付き）

- type:boolean
  - チェックボックス

- type:array
  - 複数追加可能UI（並び替え可能）
    - 項目が単数
    - 項目が複数

- typeが複数
  - ドロップダウン（入力（string以外のtype）＋選択）
  - 自由入力（特定のstringのワード＋string以外の値）

- 組み合わせのパターン
  - ドロップダウンの選択で他UIの設定が切り替わる
    - 子UIの追加
    - requiredの対象
    - 参照する$defs
    - descriptionの切り替え

- 拡張ボキャブラリー
  - "jesgo:required"：項目ラベル横に必須となる登録データセットの名称のラベルを表示
  - "jesgo:set"
  - "jesgo:ui:textarea"
  - "jesgo:unique"
  - "jesgo:ui:enabledwhen"
  - "jesgo:ui:subschemastyle"
  - "jesgo:ui:visibleWhen"

- その他jsonschemaプロパティ
  - 画面表示
    - required
    - readOnly
    - description：？アイコンでのツールチップ表示
    - units：入力UIの末尾に単位表示
  - validation
    - pattern：validationの条件（正規表現）
    - minimum

**Comment by piyotaicho** [comment]
- numberとinteger
アップダウンは要らないです、入力内容のvalidationだけで結構です。

**Comment by piyotaicho** [comment]
enum だけで形成されるものは、リストからの選択。  
選択と自由入力が組み合わさっているものは、ドロップダウンコンボとなります。
タイプが複数の場合 number と string で不明などを表現する場合があるので input box でvalidationする形になるかと思います。

**Comment by saso-hokuto** [comment]
確認ありがとうございます。

> numberとinteger

承知しました。アップダウンは非表示とします。

> enum だけで形成されるものは、リストからの選択。
選択と自由入力が組み合わさっているものは、ドロップダウンコンボとなります。
タイプが複数の場合 number と string で不明などを表現する場合があるので input box でvalidationする形になるかと思います。

こちらについても、承知いたしました。

**Comment by saso-hokuto** [comment]
> - type:string
>    - ツリー構造でグループ化されたドロップダウン（選択のみ）

![階層リストからの選択](https://user-images.githubusercontent.com/98303409/159115985-71959c37-e378-43d4-88ec-32a3244021ba.png)

こちらについて実装しましたので画面イメージを貼っておきます。（「薬剤名」です）
現状階層は1つまでの対応としています。
※この項目については下に余裕がないため、上にリストが開いています。他の選択リストと同様、下に余裕がある場合は、下に開きます。

**Comment by piyotaicho** [comment]
ツリー構造のドロップダウンで以下の問題があるようです。
```
[{
  "title": "Works",
  "enum": [
    "foo",
    "bar"
  ]
},{
  "title": "not works well",
  "oneOf": [
      {
         "const": 1,
         "title": "foo"
      },
      {
         "const": 2,
         "title": "bar"
      }
   }
}]
```
前は予定通りに展開されますが、後ろの方はすべてtitleとconstが表示されます。Chemoはうまくゆくのですが、合併症がどうしようもなりません。ちょっと弄ってみます。

**Comment by piyotaicho** [comment]
"jesgo:ui:liststyle": "button" はないと合併症が辛いですね。とりあえず、arrayなので無理矢理リストで対応していますが。
