### ISSUE TITLE
今更やらかしていたことが発覚しました。

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#154]
Performance Statusのスキーマ、/schema/evaluation/performance_status のtitleをPerformance Statusでスペースを入れて作成してしまっていました。動作自体にはなんの問題はありませんが、これで今後検討している全体ドキュメントを作成すると可読性がおちてしまいます。
さてさて。

https://github.com/jesgo-toitu/jesgo-schema/issues/5#issue-1376797906

**Comment by hsc-morita** [comment]
こちらもSQLにて対応いたします。
