### ISSUE TITLE
requiredのエラーがある場合でも保存できるようにする

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#156]
がまんすればよいだけで大したことではないのですが、required をもつスキーマが展開されたとき(例："/schema/treatment/operation_adverse_events")に必ずエラー表示が作成されるのはどうしましょう？

_Originally posted by @piyotaicho in https://github.com/jesgo-toitu/jesgo-frontend/issues/138#issuecomment-1250339089_

上記の件に対して以下のように対応する
- 保存時にエラーがあってもそれがすべてrequiredによるものである場合、保存できるようにする
- エラー自体は表示する

**Comment by kosaka-hokuto** [comment]
OKです。

**Comment by hsc-morita** [comment]
対応済み
