### ISSUE TITLE
β版での実装機能

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#16]
## 概要
β版の実装機能の目標として、以下とします。

- ログイン、患者一覧(検索)、表示、保存、1患者の情報をテキストで出力、画面表示している症例一覧をCSV出力、ができることが目標
- 検索は必要最低限として確実に動作するものとする
- オンプレ導入できる状態とする。その前段階として、先生方が触れる環境を用意する（Azure）。

**Comment by yoshiaki-hokuto** [comment]
3/31 お打ち合わせで追加で確認
・入力したデータの扱い（お試しのテストデータか原本なるかご確認）
・デザインの完成度（クレームが来ないレベルまでにする必要があるため）

**Comment by yoshiaki-hokuto** [comment]
### β版スキーマ対応状況
- jesgo:ui:visiblewhen : arrayは対応済み。それ以外は未対応。
- jesgo:ui:textarea : 入力した文字数に応じた自動リサイズ未対応
- jesgo:ui:listtype : 未対応
- jesgo:ref : 未対応
- description : 幅の調整だけ未対応
- jesgo:set："death"保存時の確認ダイアログ未対応。"recurrence"未対応。
- 編集可能なドロップダウン :  suggestlistが有効になっている
- スキーマの表記方法などは課題で問い合わせさせていただいています

以下は現在のスキーマでは使われていないものです。
- jesgo:valid：DB登録までは対応済み（未検証）。有効期限による使用スキーマの判定など中身の処理は未対応。
- jesgo:version：DB登録までは対応済み（未検証）。バージョン管理など中身の処理は未対応。
- jesgo:baseversion：DB登録までは対応済み（未検証）。バージョン管理など中身の処理は未対応。
- jesgo:error：未対応
- jesgo:get：未対応
- jesgo:ui:enabledwhen：未対応
	- 書き換えにより未使用。github[#37](https://github.com/jesgo-toitu/jesgo-frontend/issues/37)で書き換え問題ないか確認中。
- jesgo:ui:hidetitle：未対応
- jesgo:ui:width：未対応
- jesgo:ui:disabled：未対応
- jesgo:ui:noindent：未対応
- jesgo:ui:subschemastyle："row"のみ未対応。それ以外は対応済み。

**Comment by yoshiaki-hokuto** [comment]
JESGO β版実装状況(4/20)

### 患者リスト表示、腫瘍登録管理表示
- リスト表示(実装済み)
- 検索は登録年次、がん種のみ実装
- ユーザ権限による表示の切り替えは(未対応)
- 死亡時のグレーアウト、ステータス欄表示(未実装)

### 症例入力
- 現時点のスキーマで全項目表示、保存
- jesgo:uniqueに対応（複数タブの作成保存）
- validation（実装中）
- タブ移動時の保存、確認メッセージ（未対応）
- 但し、閉じずに保存する機能を実装（この機能の応用でタブ移動時の保存機能を実装する予定）
- 権限による制御（未実装）
- パスワードの変更（実装中）

### スキーマ管理
- データーベース上への登録、参照機能(実装済み)

### ユーザー管理機能
- 実装中（登録、編集、削除）

### CSV出力機能
- 実装中

### プラグイン機能
- β版以降で対応
- スキーマバージョン管理
- スキーマ更新機能(UI）（未実装）※プラグイン機能
- スキーマ管理画面（未実装）
