### ISSUE TITLE
[仕様検討]患者リストの日付検索条件について

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#160]
患者リストの検索条件で初回治療開始日や診断日での検索項目がありますが
現状は暫定措置として初回治療開始日は過去3年、診断日は過去1年分までを範囲にしています。
今後運用して行くにあたり5年予後の入力もあるため、最低5年分の検索は必要かと思います。

###  対応案
1. input type=dateにして日付で検索できるようにする
2. 年、月をテキストボックスにし、フリー入力で検索する
3. 基準となる年月を決め、そこから現在年月までのリストを生成する

**Comment by piyotaicho** [comment]
日付については検索というか表示絞り込みとして以下が妥当だと思います
- 必須なもの
  - 初回治療日の範囲指定もしくは年次指定での検索
  - 最終イベント日の範囲指定もしくは年次指定での検索
- オプション
  - 年/月
  - 年/月/日

**Comment by hsc-morita** [comment]
遅くなりまして申し訳ございません。
いただいた仕様を元に日付での絞り込みUIを検討いたしました。
特に問題がなければ以下の仕様で進めさせていただきます。
![image](https://user-images.githubusercontent.com/101262997/213360374-37310fc4-a9ca-4a67-8418-7b10b90d45bd.png)
- 年次/月次/日次のラジオボタンを選択し、それに応じて日付入力欄の表示を切り替えます
- 日付はテキストボックスで入力します
- 左矢印ボタン：入力値の前年、前月、前日にします
- 右矢印ボタン：入力値の翌年、翌月、翌日にします
	- 選択中の年次/月次/日次のラジオボタンにより動作が変わります
- 今年/今月/本日ボタン：現在日をテキストボックスにセットします
- 範囲指定のチェックボックスをONにするともう1つ日付入力欄が表示され、範囲指定可能とします
- 範囲指定の場合、左側の日付のみ入力時は入力日以降で抽出、右側の日付のみ入力時は入力日以前で抽出します

#### 最終イベント日について
最終イベント日での絞り込みですが、抽出対象は以下のどちらでしょうか？現在は前者を想定しております。
1. 患者に紐づくすべてのドキュメントの中で最も新しいeventdateが抽出範囲に該当している患者を表示する(1患者に対しeventdateが1つ決まる状態)
2. 患者に紐づくすべてのドキュメントの中で抽出範囲に該当しているeventdateを持つドキュメントが1つ以上ある患者を表示する(1患者に対しeventdateが複数あり、その内1つ以上該当する状態)

**Comment by piyotaicho** [comment]
ありがとうございます。
そうですね、日付はdatepickerよりこちらのほうがよいかもしれませんね。閏年など面倒はありますが。

最終イベント日については、恐らく経過記録などでしょうから前者の最新eventdateに基づけば良いと思います。
もしくは記載を変えて、
```
□イベント日　[◎最新　○全て]　[○年次　○月次　○日次]…
```
でユーザが選べるようにしてしまうのもよいかもしれません。正直あまり使い道は思い浮かびませんが。

**Comment by hsc-morita** [comment]
ご確認いただきありがとうございます。それでは概ね上記の仕様で実装を進めます。
最終イベント日については汎用性を考えて、ご提案いただいたユーザ選択方式にいたします。
![image](https://user-images.githubusercontent.com/101262997/213380436-e5bfe360-b0c7-400a-8e4e-f9370b5a1b42.png)

**Comment by hsc-morita** [comment]
条件リセット機能追加

[通常の検索]
![image](https://user-images.githubusercontent.com/101262997/216511353-a2fa2345-f840-4de9-83b8-a50c16d05f3d.png)

[詳細表示]
![image](https://user-images.githubusercontent.com/101262997/216511461-48564508-ad68-40ad-bb96-04c62aacdfc4.png)

**Comment by hsc-morita** [comment]
マージ済み
