### ISSUE TITLE
[仕様検討]スキーマの有効期限に関する仕様

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#164]
スキーマの有効期限の考慮を本格的に実装するにあたり仕様検討
以前の課題を参考に仕様再検討
https://github.com/jesgo-toitu/jesgo-frontend/issues/76

## 基本仕様
- スキーマの有効期限はスキーマごとにバージョン単位で持つ
- 有効期限の指定がない場合は、開始日：1970/01/01　終了日：null　とする
- 複数バージョンある場合、有効期間の重複はないようにする
- 有効期間は空白期間を作らないようにする  
  例) 有効期間が2022/01/01～2022/1/31 と 2022/03/01～2022/03/31のように1か月の空白期間があるスキーマはNG
- どのバージョンのスキーマを使用するかはドキュメント毎のeventdateが有効期限内にあるスキーマとする
- ~~eventdateが未入力、または~~eventdateによりスキーマを特定できない場合、最新スキーマを参照する

## ドキュメント作成時の考慮
- 作成・継承のメニューに表示されるスキーマは**現在日時点で有効なスキーマ**を対象とする
	- ★現状は最新スキーマを表示しているので変更必要
   	- スキーマの有効期間重複はないため、1件該当もしくは該当なしとなる想定
- 自動展開されるサブスキーマは現在日時点で有効なサブスキーマとする
	- 親スキーマは期間内だがサブスキーマが期間外のケースは最新サブスキーマで展開する

## 作成済みドキュメントに対する考慮
- ドキュメント作成後は文書毎のeventdate(診察日など)が入力・変更される度にどのバージョンのスキーマを適応するか決定し、それに応じてスキーマを切り替える
- サブスキーマ、子スキーマも同様に切り替える。この時に参照するeventdateはドキュメント全体のeventdateとする
- ~~eventdateが未入力の場合は最新スキーマが適応される~~
- eventdateが未入力の場合は現在日時点で有効なスキーマが適応される
##### 実装時の注意点
- 最新スキーマ以外も参照する必要があるが、eventdateが変わる度に有効なスキーマをAPIから取得するのか予めすべてのスキーマ情報をロードしておくのか検討する必要がある  

## スキーマアップロードによる有効期限の更新
※以下の「新スキーマ」とはアップロードするスキーマのことを指します
- 既存スキーマを更新する際は以下のルールで更新する
	- 開始日が旧スキーマの開始日以前(当日含む)のスキーマへの更新はNGとする
	- 有効期限未指定のスキーマをアップロード時は開始日を旧スキーマの開始日＋1日とし  
	  旧スキーマの終了日は旧スキーマの開始日と同じ日付に更新する
	- 新スキーマの開始日が指定されている場合、旧スキーマの終了日は新スキーマの開始日-1日で更新する
	- 新スキーマの終了日は加工せずそのまま更新する

## スキーマ管理画面での有効期限管理　※追加機能
- スキーマアップデートでは過去に遡って開始日を設定することが出来ず、誤って設定した場合のリカバリーが出来ないためスキーマ管理画面で有効期限の変更を行えるようにする
- バージョンの一覧とバージョン単位の有効期限を手動で設定できるようにする
- バージョンの無効/有効の切り替えも行えるようにする
- スキーマダウンロードもバージョンごとに行えるようにする
- 保存時に以下のルールを満たしているかチェックし、ルールを満たしていなければ保存できないようにする(スキーマが無効化されている場合はチェック対象外)
	- 開始日は必須
	- バージョン間の有効期間に重複がないこと
    - 開始日≦終了日であること
	- 最新バージョン以外の終了日は必須入力
	- バージョン間の有効期限に空白期間を作らないこと
    - バージョン間の開始日は旧バージョン ＜ 新バージョンであること
    - 1つ以上有効なバージョンがあること

有効期限編集のイメージ  
![jesgo-veredit-sample](https://user-images.githubusercontent.com/101262997/194023809-38759c25-f16b-4c16-aa61-aae2c866a8f6.png)

**Comment by hsc-morita** [comment]
[訂正]
- メニューに表示するスキーマは現在日時点で有効なスキーマ
- 作成したドキュメントのeventdateが未入力の場合は最新のスキーマを適応

と記載しておりましたが、ドキュメント作成時点ではeventdateは空になるため、開始日が未来日のスキーマが最新だった場合に未来のスキーマが表示されてしまいます。
そのためeventdate未入力時も現在日時点で有効なスキーマを表示する仕様に変更いたします。
※有効なスキーマが見つからない場合は最新スキーマとなります。(作成済みドキュメントの開始日を後からすべて未来日に変更した場合など)

**Comment by hsc-morita** [comment]
@piyotaicho 
有効期限の動作確認をしていたところ、無限ループのような状態に陥るケースがあることが判明いたしました。
例）再発スキーマのバージョンごとの有効期限とeventdateに指定されている項目が以下のようになっている
|バージョン|開始日|終了日|eventdateの項目|
|:----|:----|:----|:----|
|1.2|2022/12/01|なし|再発確認日2|
|1.1|1970/01/01|2022/11/30|再発確認日|

※12/01から開始するスキーマにおいて、eventdateの項目として別の項目が指定されたケース

上記の状態で以下の操作を行う
1. 12/15に再発のドキュメントを新規作成　→　eventdate未入力のため最新スキーマ1.2が適応される
2. 「再発確認日2」に「2022/11/01」と入力　→　Ver1.1に該当するため1.1へ切り替わる
3. Ver1.1は「再発確認日」がeventdateだが未入力なので12/15時点の最新スキーマが適応　→　Ver1.2へ切り替わる
4. Ver1.2に切り替わるとデータ引継ぎ機能により「再発確認日2」には「2022/11/01」が入力される
→　**2～4繰り返し**

幸いスキーマの読み込みタイミングにより実際には無限ループは発生していませんが
保存を行うたびに適応されるスキーマが変わってしまう状況でした。

### 対応方針
- 適応するスキーマが特定できない状況のため、最新スキーマを適応する
- 保存時にvalidationのエラー表示と共に日付不整合のエラーを表示する
![image](https://user-images.githubusercontent.com/101262997/208028451-33743700-7234-4a1a-8c94-e15ec61623e2.png)

### 確認事項
- 「該当スキーマがない場合は最新スキーマを参照する」という仕様に含まれるため、エラーメッセージは特に不要でしょうか？

**Comment by piyotaicho** [comment]
ご指摘、ありがとうございます。
そんなにこのイベントは多くないと思われますが「期限によるスキーマが特定できない場合は最新スキーマを適応」でゆきましょう。

**Comment by hsc-morita** [comment]
早速のご返信ありがとうございます。
> 「期限によるスキーマが特定できない場合は最新スキーマを適応」でゆきましょう。

承知いたしました。特にエラーメッセージは表示させずに最新スキーマを適応する仕様にいたします。
