### ISSUE TITLE
症例データの削除

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#17]
## 概要
症例データの削除については要求仕様で触れられていませんが、機能として必要だと考えています。
以下の仕様で追加することを考えています。
- 削除はリスト画面で行う
- 症例一覧の各レコードに削除ボタンを追加、削除ボタン押下で以下ダイアログ表示
```
患者ID：1122-34
患者名：テスト 患者１

この症例データを削除しますか？
```

- データは論理削除。症例テーブルに`deleted`カラムを追加し、削除された場合はこちらにtrueを設定する。症例テーブルに紐づくドキュメントの`deleted`は更新しない。

運用上、問題ありそうなところがありましたら、お手数ですがご指摘ください。

**Comment by piyotaicho** [comment]
そうですね、あまりないとは思いますが削除はあった方が良いと思います。
ただ、削除は権限が必要ですので一般ユーザにはあまり関係ないかもしれませんね。

**Comment by saso-hokuto** [comment]
確認ありがとうございます。承知いたしました。削除の仕様を追加します。
ユーザーロールはremoveに当たるので、システム管理者、上級ユーザーのみが使用できる機能になります。

**Comment by kosaka-hokuto** [comment]
課題作成時の仕様に問題があったため、仕様を一部変更します。

削除された症例と新規入力した症例の患者IDが重複した際、症例データは上書きされますが、それに紐づくドキュメントが残っていると症例データ閲覧、入力時に旧データが参照される可能性があるため、症例データの削除時に紐づくドキュメントも論理削除することにします。

**Comment by piyotaicho** [comment]
あまりないケースだとは思いますがそれがよいとおもいます。
