### ISSUE TITLE
[プラグイン]一連のドキュメント出力フォーマット確認

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#173]
@piyotaicho 
developmentブランチに、テスト用のドキュメントJSONを出力できるよう対応いたしました。
何かお気づきの点がございましたらご指摘願います。
**バックエンド側のdevelopmentも修正がありますので併せてご確認ください**
なお、DBの変更はありません。

## 確認用JSONドキュメント出力機能仕様
- データ出力系プラグインの場合にmain関数へ渡される巨大なJSONドキュメント出力機能を追加
- 簡易的にボタンから出力できるようにしていますが、正式リリース時は削除いたします
- ★特に問題なければ実際にmain関数へ渡す場合もJSON(string)で渡す予定です。

### 仕様
- 出力ボタン・メニューを以下に配置
	- 患者リストのボタン群「ドキュメント出力」
    	- 患者リストに表示中の患者のドキュメントすべてを出力(複数患者可)

![image](https://user-images.githubusercontent.com/101262997/202976304-0de1bde5-2362-44f4-be49-dd1fc50b0ebe.png)

- 症例登録画面ヘッダ「ドキュメント出力」
	- 開いている患者のすべてのドキュメントを出力

![image](https://user-images.githubusercontent.com/101262997/202976506-4af6b1a3-7803-4942-ab16-cf22d31db56f.png)

- 症例登録画面の各ドキュメントメニュー「ドキュメントの出力」
	- 対象ドキュメントとその子ドキュメントのみ出力

![image](https://user-images.githubusercontent.com/101262997/202976658-fbb5740b-9418-4c45-8edc-c13ccce8dec3.png)

- ドキュメント出力結果は別画面に表示する
	- 画面上のダウンロードボタンにて表示中のJSONを保存できる
    - ★実際はこの画面にmainの戻値が渡されて、テーブル形式の場合とそうでない場合で表示形式を変える想定です

![image](https://user-images.githubusercontent.com/101262997/202977126-13896557-f8ab-4a86-ad47-530da0c779f5.png)
    
### 出力ドキュメントの留意点
- ドキュメントの入力内容がない場合、`"診断所見": {}` のように空のオブジェクトで出力されます
	- 同名タイトルのものは配列にしているため、どちらも入力内容がない場合は以下のようになります。

```json
"診断所見": [
  {},
  {}
]
```
- 出力対象患者が1人しかいない場合でも配列にしています
### その他制限事項
- 患者リストからの出力時は「現在表示されている患者」にしています。jsonpathでの抽出は非対応です。
- 出力されるドキュメントに氏名、IDなど載っていますが本実装時は出力ON/OFF切り替えに対応いたします。

**Comment by piyotaicho** [comment]
大旨よさそうです。
空オブジェクトはこの実装で良いと思います。

が、jsonpathでアクセスを試していたところ問題が発生しました。

_同名タイトルのものは配列にしているため、どちらも入力内容がない場合は以下のようになります。_
とありますが、同名タイトルの有無をjsonpathで対応するのが困難でした。jsonpathのみで配列か否かを判別した上で状況に合わせてその下に入ることが困難だと気付きました。

同名タイトルが存在する可能性については、スキーマ定義で "jesgo:unique": false なドキュメント以外はその可能性があります。よって、ドキュメント生成については以下のようにしたほうがよいかと思います。

例えばドキュメントが一つだけの場合をあげると現在は：
```
[
  "jesgo-unique-trueなドキュメント名": { "A": "value" },
  "jesgo-unique-falseなドキュメント名": { "B": "value" }
]
```
となりますが。
複数の可能性があるのであれば、最初から配列にしておいたほうがアクセスが容易になります。
```
[
  "jesgo-unique-trueなドキュメント名": { "A": "value" },
  "jesgo-unique-falseなドキュメント名": [
    { "B": "value" }
  ]
]
```
このほうが、jsonpathでドキュメントの数により $.B と $.*.B が変わることがなく、安全だと思います。

**Comment by hsc-morita** [comment]
ご確認いただきありがとうございます。
jesgo_schemaテーブルのuniquenessカラムを参照し、falseの場合は必ず配列で出力するよう対応いたしました。
バックエンド側のdevelopmentを更新いたしましたので、お手数をおかけしますが最新取得願います。

**Comment by hsc-morita** [comment]
フロントエンド、バックエンド共に最新のdevelopmentにして確認しましたが、こちらの環境ではドキュメント出力が行えました。

思い当たることとして、以下のPRにて`npm run release-build`でビルドした場合にドキュメント出力ボタンを非表示にする対応を行いました。
[#174 ドキュメント出力機能OFF対応](https://github.com/jesgo-toitu/jesgo-frontend/pull/174)
お手数をおかけしますが、以下の点をご確認願います。
- フロントエンドを`npm run build`でビルドする
- フロントエンドのルートディレクトリに`.env.development`および`.env.production`が存在するか
- webpack.config.jsの先頭に以下の記述があるか
```js
const Dotenv = require('dotenv-webpack');
let enviroment = 'development';
const modeIdx = process.argv.findIndex(arg => arg.toLowerCase() === '--mode');
if(modeIdx > -1 && process.argv.length > modeIdx + 1) {
  enviroment = process.argv[modeIdx + 1];
}
```

**Comment by piyotaicho** [comment]
developmentでビルドされているのは確認しています。
ドキュメント出力でfalseだけが返ってくるので、バックエンド側の問題かとおもって一度node_modulesを消してnpm ci, buildしましたが状況は変わりません。バックエンド側のコンソール、クライアントのコンソールいずれにもエラーは出ません。

nodejsを他のプロジェクトのビルドのためnodejsを（なぜか18でなく）16に先日の会議の後で上げましたがそれが原因でしょうか。

**Comment by hsc-morita** [comment]
申し訳ございません。原因が判明いたしました。nodeのバージョンは関係ありませんでした。
API内でユーザ権限チェックをしており、現在は暫定的にsystem_manager権限がないとドキュメント出力できないようにしておりました。(認証失敗のfalseが返る)
お手数をおかけしますがsystem_manager権限があるユーザでログイン後出力できるかお試しください

**Comment by hsc-morita** [comment]
また、別件でunique=falseのドキュメントの子ドキュメントが出力されないという問題も見つかりました。
例）経過 -> 経過・所見(複数作成可) -> PerformanceStatus など
こちらは修正中となります。明日にはマージいたします。

**Comment by piyotaicho** [comment]
ユーザ権限での制限承知しました。システム管理者では出力できました。お騒がせしました。

**Array化は確認しましたが。ある程度の階層以下が出力されないようです。**
一番簡単な例だと、患者台帳.初回治療.手術療法.実施手術 や 患者台帳.初回治療.手術療法.手術合併症 が来るはずですが実施手術や手術合併症が出力されません。
