### ISSUE TITLE
権限：システムオペレーター だとログインできない

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#180]
どこにもエラーが残らないのでトレース困難ですが、システムオペレーター権限のユーザを作るとログインに成功はするもののルーティングがログインに戻ってしまいます。
![login-failure](https://user-images.githubusercontent.com/57445173/207757974-467ba74c-2797-4e65-af4c-299267fced86.gif)

**Comment by kosaka-hokuto** [comment]
この度はシステムオペレーター職においてログインが不可能になる問題が発生して申し訳ございません。
原因はシステムオペレーター職にVIEWの権限が無く、VIEWの権限がないと症例一覧のデータが取得できないことでした。
修正は下記仕様検討を参考に1月中に実施させていただく予定です。お手数ですがそれまではVIEWの権限がある職で作業していただきたく願います。

https://github.com/jesgo-toitu/jesgo-frontend/issues/182

**Comment by piyotaicho** [comment]
データベースのフラグまでは確認していませんでした。
と、そういえば、権限のカスタマイズとかすっかり忘れ去っていましたね。

**Comment by hsc-morita** [comment]
システムオペレーターでログインできない件は対応済み
