### ISSUE TITLE
スキーマ管理：必須スキーマの継承スキーマ取扱について

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#181]
以前スキーマ管理を実装したときに、とりあえず現状の継承元スキーマを設定した上での継承スキーマ選択という運用にしました。
今後、施設での改良が行われはじめたときに、継承スキーマだけを使いたいというケースがでてくるかと思います。当初のスキーマ管理実装では必須スキーマに継承スキーマがある場合、どちらかで表示非表示を選択可能としていましたがこの点をどうしましょうか？
（現行では必須スキーマは継承元スキーマだけが表示されています）

**Comment by hsc-morita** [comment]
申し訳ございません。失念しておりました。以下の仕様を提案いたします。
- 継承元のスキーマ選択時に表示される「継承スキーマ」の中に自身のスキーマも表示する　※表示チェックは非活性
- 継承スキーマの並び替えをできるようにし、最上位にあるスキーマを継承元のスキーマとする
　→最上位のスキーマは必ず表示チェックをつける
- 継承元のスキーマ(以下画像の「患者台帳 子宮頸がん」)が不要の場合は並び替え後に非表示にする

![image](https://user-images.githubusercontent.com/101262997/207805019-93034dbd-343b-4f5a-bd93-8b022ce9a6f4.png)

**Comment by hsc-morita** [comment]
マージ済み
