### ISSUE TITLE
"jesgo:get": "initial_treatment"について

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#183]
拡張ボキャブラリーで未対応のものの実装を進めておりますが、jesgo:getのinitial_treatmentの仕様について確認させてください。

### "jesgo:get": "initial_treatment"の仕様
- 現在のドキュメントの連なるツリーの近い位置にある /schema/initial_treatment が保持する event_date を取得する.未設定の場合は空白扱い.

上記の仕様ですが、例えば「患者台帳 子宮頸がん」にある「初回治療開始日」ですと、サブスキーマの「初回治療」のeventdateを取得する仕様と解釈しております。
ですが、初回治療のスキーマにはeventdateの設定がありません。
そのため、以下の仕様に基づきeventdateを取得します。

### eventdateの取得仕様
- event_dateは、ドキュメント内の日付情報とあわせて設定される。
- event_dateがNULLのドキュメントは、親ドキュメントのevent_dateを継承する。

eventdateがnullのため、親ドキュメントである「患者台帳 子宮頸がん」のeventdateを参照しに行きますが
子宮頸がんにもeventdateの設定がないため、eventdateは空白となります。

## 確認事項
- jesgo:getのinitial_treatmentの場合、eventdateは子ドキュメントを参照した方が良いでしょうか？
※初回治療の子には手術療法、化学療法、放射線療法などがありますので、そこから日付を取ることになります
※子から取得する場合、最も日付が古いものを取得します
- jesgo:getの対応を行うと今まで入力していた初回治療開始日が上書きされてしまいますがよろしいでしょうか？
　※jesgo:getの項目は強制的にreadOnlyにする予定です
- 仕様書では _initial_treatment_date_ となっていますが、 現在のスキーマに合わせ _initial_treatment_ で良いでしょうか？

**Comment by piyotaicho** [comment]
患者台帳は複数存在する可能性も皆無ではないので、initital_treatmentは、ドキュメントの上流にある 患者台帳 に設定された治療開始日を拾うようになっていればよいです。

event_dateについても、未設定の場合親を継承と規定していたと思います。

**Comment by hsc-morita** [comment]
以下の理由によりjesgo:get自体の対応見送り
- 入力済みの初回治療開始日が消えてしまう問題の回避が難しい
- 年齢などの計算もプラグイン機能を用いればできるため、必須機能ではなくなった
