### ISSUE TITLE
[検討]suggest_listがコンボボックスに見えない問題の解決策

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#191]
### 概要
suggest_list(任意の値入力可能なコンボボックス)が見かけ上通常のテキストボックスに見える
リスト表示されるコンボボックスに見えるよう見た目を変更したい
![image](https://user-images.githubusercontent.com/101262997/209760295-46e94e1e-a365-40c3-b77f-c7af48a618b8.png)

### 課題
material-uiのAutoCompleteコンポーネントを使用しているが、freeSoloモード(任意の値入力可)にすると右端にあった▼ボタンが非表示になってしまう。freeSoloがfalseだと任意の値が入力できないため仕様を満たせない

### 解決策
AutoCompleteにはアイコンを強制表示させる設定(forcePopupIcon)があったため、それを使用する

**Comment by kosaka-hokuto** [comment]
OKです。

**Comment by piyotaicho** [comment]
OKです。
