### ISSUE TITLE
jesgo:ui:subschemastyle=inline指定時のレイアウトについて

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#199]
@piyotaicho 
以前のお打ち合わせの際、項目を横並びにする可能性が高いとお伺いしたため
array以外の通常のobjectもjesgo:ui:subschemastyle=inlineを設定することで横並びできるよう対応いたしました。

以下はcTNM分類とypTNM分類を _inline_ にしたケースです。
なお現状のスキーマでは _row_ が指定されているため、現状通り縦並びとなります。(rowは未実装のためデフォルトのnoindent相当)
![image](https://user-images.githubusercontent.com/101262997/213070475-0dab65f2-950c-4334-93fc-60632cd5dbca.png)

[スキーマ例]
```json
"cTNM": {
  "type": "object",
  "title": "cTNM分類(日産婦2020暫定版)",
  "description": "cTNM分類は、治療を開始する前に、内診・直腸診による局所所見に画像所見を加味して総合的に判断し報告する。<br>子宮頸部円錐切除術は臨床検査とみなし,これによる組織検査の結果は原則としてcTNM分類に入れる。",
  "jesgo:ui:subschemastyle": "inline",
  "properties": {
    "T": {
      "$ref": "#/$defs/T"
    },
    "N": {
      "$ref": "#/$defs/cN"
    },
    "M": {
      "$ref": "#/$defs/cM"
    }
  }
}
```

[仕様]
- object自身のタイトル(画像の例だと「cTNM分類(日産婦2020暫定版)」)を1行目に表示
- objectの項目(propertiesで定義された項目)は2行目に表示し、横並びで表示する
	- 領域からはみ出すものはwrapして次行に表示する

このレイアウトでよろしいでしょうか？問題なければdevelopmentに反映いたします。
※PRは#198 のため、対象ブランチで確認できます

**Comment by akihikoueda** [comment]
平素よりお世話になっております。京都大学の植田です。横から失礼いたします。
上記横並びの見やすい形でのご提案を頂きありがとうございます。
構成については賛成ですが、横並びにした場合の各項目の横幅については選択肢などの項目の文字列に従った可変長となりますでしょうか？ 項目が長い場合の折り返し等の設定についてはどのようなイメージとなりますでしょうか？

**Comment by hsc-morita** [comment]
ご確認いただきありがとうございます。以下回答いたします。
> 横並びにした場合の各項目の横幅については選択肢などの項目の文字列に従った可変長となりますでしょうか？

→ 仰る通り、各項目の横幅は選択枝の文字列の長さに応じて可変長となります。そのため長い選択枝のものがある場合下段へ折り返されます。

> 項目が長い場合の折り返し等の設定についてはどのようなイメージとなりますでしょうか？

以下折り返し時のイメージとなります。
画像の縮尺がおかしいですが、画面幅が小さくなるにつれて折り返されるため最終的には縦並びとなります。
フルHDサイズ(N分類　1行目：3項目　2行目：1項目)
![image](https://user-images.githubusercontent.com/101262997/214203680-b636fc72-efa8-4b2d-b3ec-ef65d3d66034.png)
横幅小さく(N分類　1行目：2項目　2行目：2項目)
![image](https://user-images.githubusercontent.com/101262997/214203691-e3f39944-b55b-4a13-9113-015286057bfe.png)
さらに横幅小さく(N分類　1行1項目)
![image](https://user-images.githubusercontent.com/101262997/214203706-b5edee68-5169-42cc-847f-75149c4434bd.png)

**Comment by piyotaicho** [comment]
現状でも画面サイズをあまり想定しておらず、トップの患者情報、コントロールですら微妙なので、折り返し(over-flow)の定義までスキーマでさせると厳しいと思います。

in-lineがここまで大きいsubschemaを相手させるということは想定しておらず。
出番は主に化学療法の　薬剤名　投与量　単位　といった、「横並びが良いもの」程度に考えています。

**Comment by hsc-morita** [comment]
2023/02/03
- 取り急ぎ現状の仕様でマージ済み
