### ISSUE TITLE
[schema]jesgo:ui:subschemastyleの仕様について

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#20]
## 概要
`jesgo:ui:subschemastyle`の仕様について確認させてください。

仕様書version1では、以下の定義となっています。
![subschemastyle](https://user-images.githubusercontent.com/98303409/160761232-ca8e9068-2953-420b-a29a-c153f4386e57.png)

仕様書では、サブスキーマフィールドタイトル、フィールドタイトル、入力コントロールが全て横並びであることがデフォルトでした。

そちらを前提として、以下を確認させてください。
- 現在のレイアウトは、使用しているライブラリの仕様もあり、サブスキーマフィールドタイトル、フィールドタイトル、入力コントロールが全て縦並びになるのをデフォルトとしています。
  そのため、`jesgo:ui:subschemastyle`のデフォルトも今のレイアウトのデフォルトに合わせたいと考えているのですが、可能でしょうか。
- `noindent`と`row`のように、サブスキーマフィールドタイトルの位置だけ異なるケースはあるでしょうか。
- 3/27に追加されたスキーマの`/schema/treatment/supportive_care`（緩和治療）で`"jesgo:ui:subschemastyle":"row"`が指定されていますが、こちらは仕様書の定義の通り、サブスキーマフィールドタイトル、フィールドタイトル、入力コントロール全てが横並びになるレイアウトを想定しての設定でしょうか。

**Comment by piyotaicho** [comment]
現在のレイアウトは、全てが縦方向になるので noindent 相当となっているかと思います。
システム的にも、これがデフォルトの方が楽だと思いますので、スキーマの方を変更します。

さて、object のサブスキーマならばnoindentでも展開に問題はないのですが、array の場合 noindent で展開してくると複数入力された項目がなににあたるのかはっきりしなくなる（コントロールレイアウトの問題でboxが間延びします）のを回避する目的で row を用意しています。

inline は TMN 分類のような進行期で縦並びだと「絶対にクレームが来る」内容については 横並びをどうしても実現しなければいけないので用意して居ます。実装はしていただいているので

supportive_care は良く考えたら、jesgo:unique を外しているので複数用意できるドキュメントなので構造を変更します。これは縦並び(noindent)で結構です。

**Comment by piyotaicho** [comment]
併せてお気づきかと思いますが、ご厚意でタブ形式に子ドキュメントを展開していただいていた部分を明確に指示できるように jesgo:subschemastyle に tab を追加しました。/schema/*/root.json をそのように書き換えています。

**Comment by piyotaicho** [comment]
- jesgo.json でデフォルトを noindent に修正しました。
- supportive_care.json を簡略化しました。
