### ISSUE TITLE
データ更新プラグイン実行時の上書き確認の表現方法検討

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#206]
データ更新プラグイン実行時、値が入力済みの項目に更新する場合に上書き確認を行うが
現在の実装では項目名と変更前、変更後の値しか表示していないため
最低でもどの患者のどのスキーマのどの項目を更新するのかを表示する必要がある。

情報量が多くなるため、window.confirmではなく独自のダイアログ表示を検討する。

**Comment by piyotaicho** [comment]
ダイアログ類、window.alert(), window.confirm()よりも、bootstrapのmodalラップしたカスタムコンポーネントで良くないですか？
(JOEDはそんな感じで対応しています)

**Comment by hsc-morita** [comment]
上書き確認イメージ
![image](https://user-images.githubusercontent.com/101262997/216216978-8e09c1a4-12e5-4e83-ae0c-4802872c9ca6.png)

- 患者ID、氏名を表示
- スキーマ名表示(親子関係含む)
- 項目名はjson pointerのパス　※先頭の"/"はトリム
- 「以降、確認ダイアログを表示しない」のチェックを追加
	- はい：以降すべて上書き
	- いいえ：以降すべて上書きしないでスキップ

[課題]
- arrayへの追加時、または置き換え時の表現

**Comment by piyotaicho** [comment]
**こんな感じでいいと思います。**
ただ、中身が増えるとエライコトになるので、modal-bodyのmax-heightを70vhぐらいにしてoverflow-y: scrollで対応したほうがよいのかなと思います(bootstrapが受け入れてくれるかは未検証)。

**arrayについて** はかなり悩ましいです。elementのタイプに依存しますね。
- objectの場合はまるっと上書きしかない
- string/numberの場合は、arrayの上書き・追記を選択
というところです。

ただ、こんなことやっていると大変なので、デフォルトはarrayを上書きとして、上書き全体で
- 確認それぞれの項目にチェックボックスを設置して、変更を受け入れるか（デフォルトは受け入れ）を選択
- 以降ダイアログを表示しない、でのあーだこーだは下のログで手作業対応
- インポートについてはログを出力する（実施されていなくてもその変更予定だった内容は記録されるのであとで手修正できる）
という風にすればみんな幸せになれるかと。

**Comment by hsc-morita** [comment]
### 上書き確認新仕様案
いただいた案を元に確認ダイアログのデザインと更新後のログ表示を検討いたしました。
方針に問題がなければこれにて実装を進めさせていただきます。
お忙しいところ恐れ入りますが、ご確認のほどよろしくお願いいたします。

#### 上書き確認ダイアログ
![image](https://user-images.githubusercontent.com/101262997/216872991-1fb24360-f8e8-4e8d-9a80-fcc306eecbea.png)
- 既に入力値がある項目に更新する＆差分がある場合に確認ダイアログを表示する
- ダイアログは症例(患者)単位で表示する
- ドキュメント単位でグループ化し、1項目ずつ上書きする/しないをチェックボックスにて選択する(デフォルトON)
- 項目名はjson pointerのパス表記。見栄えを考慮し先頭の"/"はトリムする。array時の添え字(hoge/0)やハイフン(hoge/-)も取り除いた形とする
- arrayの場合は全体を上書きするかスキップするかの2択にする
	- arrayのelementがobjectの場合はJSONで比較・表示する
	- object以外(stringやnumber)の場合は値を表示
	- 画面にはarrayの内容1つにつき1行表示し、順番を表示する。差分がないものも表示する
- 「以降、すべての項目を上書きし確認ダイアログを表示しない」のチェックを付けて更新すると、これ以降はすべて上書きしてダイアログは表示しない
	- 誤って上書きしたものは後述のログから手作業で復元する

#### 上書き後のログ
![image](https://user-images.githubusercontent.com/101262997/216883282-12502a33-36a6-40f9-8a2d-5ed3a9f1e956.png)
- OutputViewにタプルで上書き結果を渡し、テーブルとして表示する
	- 上書きしたすべての症例(患者)を表示する
	- 上書きしたかスキップしたかわかるように表記する
- ログはCSVでダウンロード可
- ログに表示されるものは上書き確認ダイアログで表示されていた項目とする。ブランク項目に更新したケースは表示しない

**Comment by piyotaicho** [comment]
とても良いと思います。これでお願いいたします。

**Comment by hsc-morita** [comment]
大変お待たせいたしました。上記の上書き確認ダイアログの対応を行い、developmentにマージしております。
※バックエンドも変更しております。

ひとまずこれでStep2としての対応はすべて入っている認識です。
お忙しいところ恐れ入りますがご確認の程よろしくお願いいたします。

**Comment by piyotaicho** [comment]
検証中です。
なにやらどのたいみんぐからか患者状態アイコンがでなくなったので一度データベースから全部再構築して確認してます。
