### ISSUE TITLE
[バグ]プラグインによる上書き確認無しのデータ更新時の不具合

### ISSUE THREAD

**Issue by kosaka-hokuto** [jesgo-toitu/jesgo-frontend#209]
### 不具合内容
プラグインによるデータ更新時に上書き確認をキャンセルしてもデータが更新されることがある
#### 前提条件
プラグインからAPIに渡される更新オブジェクトのtargetに2つ以上の要素があり、かつ上書き確認が必要ないものの前に、上書き確認が必要なものが配置されていること

### 再現手順
1. 症例登録画面で「患者台帳 子宮頸がん」を作成
2. 上記ドキュメントのうち、「初回治療開始日」に適当な日付を入力し、「診断日」は空欄の状態で保存を行う
3. DBからドキュメントIDを見る等して該当のドキュメントを更新するプラグインを記載する
4. 上記プラグインの更新オブジェクトのtargetを以下の様に設定する
    ```
   "target":
   {
     "/初回治療開始日": "2023-02-01", // 入力値と異なる値
     "/診断日": "2023-02-02"
   }
    ```
5.  プラグインを実行し、上書き確認でキャンセルをしても初回治療開始日が上書きされてしまう

**Comment by hsc-morita** [comment]
上書き確認の仕様を大幅に変更したためクローズ
