### ISSUE TITLE
[schema]/schema/EM/staging(子宮体がんの病期診断)について

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#21]
## 概要
/schema/EM/staging(子宮体がんの病期診断)のスキーマについて確認させてください。
参照：https://github.com/jesgo-toitu/jesgo-frontend/blob/prototype/docs/schema/EM/staging.json

1. TNMとypTNM
手術状況で"術前治療施行例"を選んだ場合、TNMには`"$id": "#TNM"`の、ypTNMには`"$id": "#pTNM"`の「TMN分類(UICC第8版)」が設定されるため、同じタイトルを持つ「TMN分類(UICC第8版)」が2つ表示されることになりますが、認識あっているでしょうか？

2. ypTNMのelse条件
```json
"ypTNM": {
            "if": {
                "properties": {
                    "手術状況": {
                        "const": "術前治療施行例"
                    }
                }
            },
            "then": {
                "$ref": "#pTNM"
            },
            "else": {
                "type": "object",
                "additionalProperties": true
            }
        }
``` 
elseに`"type": "object"`のプロパティが定義されていません。
その後に記載のあるallOf内でのif~thenではelseの定義はないようなので、こちら"ypTNM"内のelseも削除して問題ないでしょうか。

**Comment by piyotaicho** [comment]
ご指摘の通りです、確認して修正しておきます。

**Comment by piyotaicho** [comment]
途中経過でおかしくなっていたのと、additionalProperties: false にしていたので余計なことが生じていたのを確認したので修正しました。コメントも少し追加しています。

**Comment by saso-hokuto** [comment]
schemaの修正、ありがとうございます。

修正していただいたschemaについて、再度確認させてください。
手術状況で"術前治療施行例"を選んだ場合ですが、
TNMには"$id": "#TNM"の、ypTNMには"$id": "#pTNM"の「TMN分類(UICC第8版)」が設定されるため、
以下のように「TMN分類(UICC第8版)」というタイトルを持つフォームが2つ表示される想定でおりますが、問題ないでしょうか。
それとも、「TMN分類(UICC第8版)」の上位のタイトルとして、TNM、pTNMがそれぞれ表示される方が正しいでしょうか？
![子宮体がん_病期診断](https://user-images.githubusercontent.com/98303409/161886972-647158bf-7630-43cf-b7ab-71a88b10324b.png)

**Comment by saso-hokuto** [comment]
5/30目途でスキーマが大幅に更新されるとのことなので、その際に改めて動作確認します。
本件は一旦クローズとします。
