### ISSUE TITLE
スキーマ修正

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#214]
以下の二点を修正
- https://github.com/jesgo-toitu/jesgo-schema/pull/7
  - その他の～を選択しても自由入力が展開されなかった
    - visiblewhen に typo → visibleWhenに修正
    - pattern では動作しないためenumに変更
  - ここにあるべきでは無い付属器の状態(そもそもなぜか展開なかった)を削除
- https://github.com/jesgo-toitu/jesgo-schema/pull/8
  - スキーマのエラーで展開されなくなっていた
  - buttonsを使用
  - oneOf/anyOfを修正
  - anyOfでのカテゴリ分けは実装されていないようなので諦めた

**Comment by hsc-morita** [comment]
`その他の～を選択しても自由入力が展開されなかった`
→ 以前のスキーマで確認したところ、展開されなかったのはスキーマ解析処理の不具合であることが判明しました。
大変申し訳ございませんが、こちらは別課題に上げて修正いたします。

※詳細は別課題に上げますが、visibleWhenで術式を条件にしている項目が2つあったことが原因でした。(自由入力、卵巣・卵管の状態の2つ)
卵巣・卵管の状態を削除したところ、自由入力の方は表示されました。

**Comment by toitu-nomura** [comment]
@piyotaicho 
植田先生からいただいている、スキーマ修正の件です。
https://github.com/jesgo-toitu/jesgo-schema/issues

これらの修正についても、こちらで対応を進めてよろしいでしょうか？
もし、山本先生の方ですでに着手済みでしたら、
その旨お知らせいただけると助かります。
よろしくお願いいたします。

**Comment by piyotaicho** [comment]
まだ要件を並べ替えているところでまだ作業はしていません。
ブランチを作成しておきますので、そこのなかで分担して行ければと思います。

**Comment by toitu-nomura** [comment]
承知いたしました。
宜しくお願いいたします。
