### ISSUE TITLE
[仕様検討]ユーザロールの設定機能

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#219]
### 概要
ユーザ権限により機能制限を行っているが、現状権限の設定機能がないため各施設で独自のロールを設定できない。
ユーザロール設定機能を検討する

### 仕様草案
- ユーザ権限設定画面を追加。利用者管理画面にユーザ権限設定画面へ遷移するボタンを設ける
	- system_manage権限があるユーザであれば開ける
- ロールの追加、削除、各種操作権限の変更を行えるようにする
- ~~roll_id=0のシステム管理者の設定はロール名(title)のみ変更できるものとし、削除・各種操作権限の変更は不可とする~~
- roll_id=0(システム管理者)は非表示とし、編集不可とする
- ロールの削除はそのロールを使用しているユーザが1人もいない場合に行えるものとする
	- jesgo_user_rollテーブルに削除フラグのカラムを追加する
- 各種操作権限はチェックボックスでON/OFFする。操作権限自体の追加・削除は不可
- ユーザが追加する権限はroll_idを10000から開始し、シーケンシャルに振っていく。また、roll_idは非表示(編集不可)とする

**Comment by piyotaicho** [comment]
申し訳ありません。この件についてはぼーっとしてました。

roll_idは10000以降とかシーケンスで適当に付与で編集できる必要はないと思います。
また、roll_id == 0はさすがにtitleを含めて編集不可で良いんじゃ無いでしょうか。

UIは単純に、テーブルでチェックボックスが並ぶ、で良いと思います。

**Comment by hsc-morita** [comment]
ありがとうございます。以下の仕様を追加いたします。
- roll_id=0(システム管理者)は非表示とし、編集不可とする
- ユーザが追加する権限はroll_idを10000から開始し、シーケンシャルに振っていく。また、roll_idは非表示(編集不可)とする
- jesgo_user_rollテーブルに削除フラグ、更新者、更新日のカラムを追加する

**Comment by piyotaicho** [comment]
ありがとうございます。
トラブルの元になりますからALTERは最低限にしたいです。更新者、更新日の記録は不要かと思います。

削除（有効無効）のフラグだけは追加になりますね、仕方ない。

**Comment by hsc-morita** [comment]
承知しました。削除フラグのみ追加といたします。

**Comment by hsc-morita** [comment]
以下イメージで対応中です。弊社内部での動作確認が終わり次第developmentにマージいたします。
![image](https://user-images.githubusercontent.com/101262997/226295305-e5febc14-94c5-44a5-bab6-421ae75b97e6.png)

- 利用者管理画面を開き、ヘッダの「権限管理」のリンクを選択することで権限管理画面を開く
- システム管理者(roll_id=0)、ログ用ユーザ(roll_id=999)、および削除されたものを除いた権限一覧を表示する
- チェックボックスで権限の有効/無効を設定する
- 新規作成ボタン押下で新しい行を追加
	- 追加したものはroll_id=10000から採番し、追加する度にインクリメントする
- 保存ボタンにより保存する(削除時も削除→保存の手順を踏みます)

[エラーチェック]
- 権限名称は必須
- 削除対象の権限が既にユーザに付与されている場合は削除不可
- 権限設定に何か変更がある場合、保存せずに画面遷移するとアラートを表示する

**Comment by hsc-morita** [comment]
申し訳ありません。本日developmentへマージ予定でしたが、バグ修正後の再確認が完了していないため
明日(3/23)にマージいたします。
