### ISSUE TITLE
ドキュメントテーブルのevent_dateが有効期間外の場合

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#22]
## 概要
仕様書version1 4.3.2. ドキュメントテーブル にて、
ドキュメントテーブルのevent_dateがスキーマの有効期間外であった場合（有効なスキーマが存在しない場合）、そのスキーマを用いたドキュメントの作成、変更は許容されない(readonlyとして扱われる)
とあります。
これを踏まえると、そもそもドキュメント登録時に入力したevent_dateがスキーマの有効期間外であった場合、登録自体を防ぐべきだと考えていますが、運用上問題ありそうでしょうか。

**Comment by piyotaicho** [comment]
ご指摘の通りevent_dateが入力されて、該当する新しいバージョンのスキーマも存在しない場合は、警告を発して登録を防ぐ運用でよいと思います。
今後期間限定の臨床研究に対応できるようにの配慮です。
このあたり突き詰めるとかなり面倒ですが、スキーマのアップデートの流れについても要検討だと思うので issue にして考えておきます。

**Comment by saso-hokuto** [comment]
スキーマアップデートについてのissue作成ありがとうございます。
event_dateについては承知しました。
