### ISSUE TITLE
【プラグイン】all_patient: false, update_db: true, target_schema_id_string: あり が表示されない

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#229]
今更感がありますが、サマリ自動作成や、ロジカルチェックなどを実装するにあたり検証しています。
all_patient: false, update_db: true で、target_schemaを設定すると、プラグインがコントロールボタンに表示されません。
探してみると。

ControlButton.tsx : 660
```
          {jesgoPluginList.map(
            (plugin: jesgoPluginColumns) =>
              !plugin.all_patient &&
              !plugin.update_db &&
              plugin.target_schema_id &&
              plugin.target_schema_id.includes(schemaId) && (
                <MenuItem eventKey={`plugin_${plugin.plugin_id}`}>
                  プラグイン:{plugin.plugin_name}
                </MenuItem>
              )
          )}
```
663行目をコメントアウトして表示されるようにしましたｇは、コントロールボタンからは基本的に参照系での呼び出しとなるようですね。

とりあえずupdate_dbは、患者ベース(target_schemaなし)では機能するのでそれに基づいて設計します。結構複雑なドキュメントに育つと結構キツいかもしれません。

**Comment by hsc-morita** [comment]
申し訳ありません、各ドキュメントのコントロールボタンから更新系プラグインの実行を制限した正確な経緯は失念してしまいましたが
無関係なドキュメントを更新するプラグインも書けてしまうことを懸念しての措置だったと記憶しております。

ただ、スキーマ指定なしの患者ベースの更新プラグインは対象の患者(症例)のみ更新されるよう制限しておりますので、それと同じ要領で「対象ドキュメントとその子ドキュメントのみ更新する」とすることは可能かと存じます。
修正案を検討いたします。
