### ISSUE TITLE
腫瘍登録管理表示の[登録]にエラーありなしをアイコンで表示させたい

### ISSUE THREAD

**Issue by kosaka-hokuto** [jesgo-toitu/jesgo-frontend#232]
## 概要
各症例において、腫瘍登録管理表示の[登録]部分にエラーのありなしをアイコンで確認できるようにする

## 仕様
- 該当症例にエラー(jesgo:errorで定義されるもの)が1件でもあればエラーを表示する
- 一つの症例に複数件のエラーがある場合も一つしかアイコンは表示しない
- エラーがない場合はアイコンは表示しない
- 一旦アイコンは仮のものとして実装する(SVG形式のファイルであれば差し替え可能)
- 本来の登録ステータス(済/未/拒否)より後に表示する

## ブランチ
#232-dev-show_error_case_icon(バックエンドにもあり)

**Comment by kosaka-hokuto** [comment]
@piyotaicho こちらに関しては専用のアイコンをいただければ取り込んで反映いたしますので、準備ができ次第提供していただきたく存じます。

**Comment by piyotaicho** [comment]
SVGアイコンを追加しました。

**Comment by kosaka-hokuto** [comment]
アイコンのご提供ありがとうございます。
弊社内で動作確認でき次第マージいたしますので今しばらくお待ちください。
