### ISSUE TITLE
書き戻し対応への出力系拡張

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#234]
現状で書き出し→外部ツール→書き戻しを柔軟に行う為に出力系プラグインにドキュメントidを埋め込むように細工しました。
https://github.com/jesgo-toitu/jesgo-backend/pull/60

**Comment by piyotaicho** [comment]
#235 updateでもまとめドキュメントを取得できるように拡張してみました。

**Comment by kosaka-hokuto** [comment]
PRをマージしましたのでクローズします。
