### ISSUE TITLE
jesgo:error のハンドリングについて

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#236]
正式にプラグインを渡していないのでバレていないと思いますが **１保存で消える** のは保存されるタイミングがものすごく多いので検討が必要そうです。

### 実装の容易な現実的な対応
- トップの保存ボタンでの保存実行時にのみエラーを削除するように実装を変更する   
現状、jesgo:errorはドキュメントをparseした時点で削除されており、ドキュメントを開いた時点で保存の確認がでます。更にそこで保存するとエラーが消えてしまいます。  
若干の変更が必要になりますが、トップの保存ボタンで操作をした際に、エラーの削除を行うかどうかconfirmするのも一案かもしれません。

### かなり困難が予測される対応（多分一番希望される)
- jesgo:errorを表示しているcustom divに一つ一つ削除ボタンを用意する   
jesgo:errorはドキュメントに分散しているので現在の文字列だけを取得しているエラー表示に削除の実行を実装するのは現実的ではありません。  
比較的容易な実装としては、エラー一行一行をカスタムコンポーネントにして、それぞれがdocument_id, jesgo:error 中のjsonpathを保持しstoreにあるドキュメントを操作する。でしょうか。

**Comment by hsc-morita** [comment]
返信が遅くなりまして申し訳ございません。
後者の **かなり困難が予測される対応（多分一番希望される)** の方を元に検討いたしました。
＜イメージ＞  
![image](https://github.com/jesgo-toitu/jesgo-frontend/assets/101262997/b1105554-0808-442d-b3f5-ba616de645ce)

### 動作仕様
- jesgo:errorがある状態でタブ遷移を行っても、jesgo:errorを削除していない限り保存確認ダイアログは非表示とします
- jesgo:errorを症例画面上部へ表示する際、エラー内容の各テキストの右に×ボタンを配置します
- ×ボタンを表示するのはjesgo:error由来のメッセージのみとし、スキーマ定義による未入力チェックなどは対象外とします
- ×ボタンをクリックすると対象のエラーメッセージを削除します(この時点ではDBへの保存は行いません)
- 保存時、削除したjesgo:errorの内容も保存します
- エラーは手動で削除して保存する運用となります

### 実装時の留意点
- jesgo:errorはドキュメント(formData)から削除せずに残しておく。formDataの内容からスキーマに不足している項目を追加する処理にて、jesgo:errorは対象外にし画面のドキュメント上に表示されないようにする
- エラーメッセージとして表示している内容は、現状でもdocumentIdなどの情報を持っているため、特定のエラーメッセージに紐づくドキュメントを更新することはそれほど困難ではない
- メッセージ作成時にjsonpathを設定しておき、×ボタンクリック時に対象ドキュメントのjesgo:errorの指定項目を削除する。

**Comment by piyotaicho** [comment]
まだ、利用者側ではjesgo:errorの姿はよほどの好き者でない限り目にしていないはずなので、この提案された運用が利用者側の希望にも添えるのかなと思います。

別件ですが、エラー削除の運用を各施設で工夫してもらえれば、現在希望が出ていますが無理ですと伝えている「上級職によるデータのチェックが済んでいるかを確認するフラグ」を検討する必要もなくなりそうです。
