### ISSUE TITLE
ドキュメントレベルのdescription

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#24]
以下のようなスキーマの場合  
```
{
  "$id": "/schema/hoge",
  "title": "ほげ",
  "description": "寿限無.",
  "type": "object",
  "properties": {
     "foo": {
        "type": "string",
        "description": "文字列"
    }
  }
}
```
現在、タブ状になっている場合タイトルタブのところに(?)がついて展開されていますが、ドキュメントレベルの場合はドキュメントの先頭部分に文字列として展開していただければとおもいます。  
フィールド(プロパティ)については現状の様式で構いません。
![image](https://user-images.githubusercontent.com/57445173/161416608-f772186f-9029-4285-9379-6bed5f351b4b.png)

**Comment by saso-hokuto** [comment]
承知しました。
ドキュメントレベルの注釈については、先頭に文字列として表示します。

**Comment by saso-hokuto** [comment]
ドキュメントレベルの注釈を、文字列として展開するようにしました。
Azure環境にも反映済みです。

**Comment by piyotaicho** [comment]
今確認した限りではきちんと展開されているようです。

**Comment by saso-hokuto** [comment]
確認ありがとうございます。
本件はクローズとします。
