### ISSUE TITLE
[development] 重複癌がAPIで出力できない？

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#240]
masterでは問題ありませんが、developmentで重複癌のデータで、出力系のAPIで二つ目の患者台帳から下が展開されないケースがあります。
（再現状況を確認中）

**Comment by piyotaicho** [comment]
原因を特定しました。先のPRに漏れがありました。

https://github.com/jesgo-toitu/jesgo-backend/pull/63

**Comment by piyotaicho** [comment]
と、ここで別の問題があることに気が付きました。
重複癌では schema_id は重複しない(unique: true)ものの、generateされるドキュメントでは 患者台帳 が重複します。プラグイン側での対応が結構面倒になることが発覚しました。これはプラグインの解析ランタイム側で処理することにします。

**Comment by hsc-morita** [comment]
こちらのPRをマージいたしました。お手数をかけて申し訳ありません。
https://github.com/jesgo-toitu/jesgo-backend/pull/63
