### ISSUE TITLE
[取得系プラグインAPI] 出力されたJSON中の空のarrayにnullが出力されるケースがある

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#241]
現在指摘があって判明しているのは
スキーマ "/schema/OV/staging"
のpTNMの遠隔転移部位で生じます。

恐らくこれは、pTNM = 1 を条件に発動するハズですが、発動していないときでも定義は参照され、minItems: 1であるため無理矢理nullが指定されているものと思われます。
そして、このnullは項目を選択してもarrayの要素として残り続けているようです。

**Comment by hsc-morita** [comment]
課題に気づくのが遅くなり大変申し訳ございません。
取り急ぎ調査結果を報告いたします。対応方針は別途検討いたします。

`pTNM = 1 を条件に発動するハズですが`
→ "jesgo:ui:visibleWhen"にて表示/非表示を定義しておりますが、visibleWhenは制限事項としてtype:arrayのitems内のみ有効としておりました。(items以外は未実装)
そのため`pTNM/M/pattern = ^1`による表示切り替えは効いておらず、pTNMの遠隔転移部位は常に表示されます。申し訳ありません。

`minItems: 1であるため無理矢理nullが指定されているものと思われます。`
→ 仰る通りminItems: 1のためarrayに項目が自動で追加されるのですが
　itemsのtypeがstring、number、integerの場合、`undefined`で追加されJSONとして保存した際にnullで保存されるようです。
　なお追加ボタンで追加した場合も同様に`undefined`となります。(react-jsonschema-formの仕様です)
　itemsのtypeがstringの場合、`"default": ""`とデフォルト値を追加することで、nullの代わりに空文字が登録されることは確認済みです。

`そして、このnullは項目を選択してもarrayの要素として残り続けているようです。`
→追加されたarrayの空項目に対し入力(選択)すると正常に上書きされ、nullは残りませんでした。
　ただし、手術状況をブランクにして遠隔転移部位を非表示にしてもdocumentには残ったままとなります。

#### 確認事項
`出力されたJSON中の空のarrayにnullが出力されるケースがある`　とのことですが、問題点としては以下のどちらでしょうか？
1. 遠隔転移部位にnullが出力されているのが問題。遠隔転移部位の出力自体はOK
2. 遠隔転移部位は非表示かつ入力していないにも関わらず遠隔転移部位が出力されていることが問題

**Comment by piyotaicho** [comment]
ありがとうございます。
遠隔転移部位の内容は問題ないのですが、nullが常に出力されていることが問題です。

ここで''が入ることも、本来undefinedもしくはlength==0となるプロパティに不要な値が入ることとなりますので、arrayの値であれば当該elementを削除、プロパティの値であればプロパティを削除したほうが良いと考えます。

これがあろうとなかろうととりあえずのフロントエンドのformの動作には影響がないので、バックエンド側でjsonを保存する際に処理した方がよいかもしれません。この辺をどこで実装するかはお任せします。

プラグインランタイム側では上記のように対応するようにしておきます。

**Comment by hsc-morita** [comment]
回答ありがとうございます。
array中にnullや空文字があるものは除外して保存しようと考えましたが
minItemsが設定されているため、nullを除外した状態のドキュメントを症例登録画面で表示させた際に以下の問題がありました。
- `"遠隔転移部位": []`のように空のarrayにすると、保存時に「1件以上入力してください」とエラーが表示される
- プロパティ自体を削除すると症例登録表示時に自動でarrayに追加されるため、タブ移動時に「保存しますか？」と毎回聞かれてしまう


よって、バックエンド側のドキュメント取得処理にてarrayのnullを除外したドキュメントを返すよう対応したいと考えております。(DBのデータは現状のまま)
以下の仕様で問題ありましたらご指摘願います。

- arrayの要素内でnull、undefined、""(空文字)のものは除外します
例）nullの要素が紛れているarray
```
＜実データ＞
{
  "項目名": ["AAA", null, "CCC"]
}
↓
＜null除外後＞
{
  "項目名": ["AAA", "CCC"]
}
```

- arrayのnull除外後、要素が0個になった場合はプロパティ自体を削除します
```
＜実データ＞
{
  "項目名1": [null, null],
  "項目名2": "AAA"
}
↓
＜null除外後＞
{
  "項目名2": "AAA"
}
```

- arrayの要素がオブジェクトの場合、そのオブジェクト内の要素も順に処理します
- 空のオブジェクト(`"項目名": {}`)は削除しません

上記の対応を行うことにより、プロパティが何もないJSONドキュメントが生成されることがあるのでは？
と懸念しましたが、`jesgo:document_id`は必ず付与されるのでそちらは問題なさそうです。

**Comment by hsc-morita** [comment]
本件、バックエンド側のdevelopmentへマージしております。
お忙しいところ恐れ入りますが、ご確認の程よろしくお願いいたします。

**Comment by piyotaicho** [comment]
確認ですが、このあたりはazureに設置された1.0.3aには未反映でよろしいでしょうか。(ローカルでのテストと食い違いが生じました)

**Comment by hsc-morita** [comment]
大変申し訳ありません、バックエンド側のソースが古かったようです。
最新のdevelopmentブランチの内容で立ち上げ直しましたのでお手数をおかけしますが再度ご確認お願いいたします。

**Comment by piyotaicho** [comment]
確認しました。この仕様に依存しているプラグインなので試す前にわかってよかったです。
