### ISSUE TITLE
[不具合]スキーマのif-thenによる表示制御ができない場合がある

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#246]
### 不具合内容
https://github.com/jesgo-toitu/jesgo-schema/issues/15
上記のスキーマ変更ができるか確認していたところ、以下のようなスキーマになっていた場合if-thenでの表示処理が正常に動作しない

### 再現手順
1. 以下のスキーマを修正
スキーマ：/schema/CC/staging
defs/Tのオブジェクトに、Tの入力状況で「T1a期 詳細入力」が表示されるようif-thenの記述を追記する
```json
"T": {
    "$id": "#T",
    "type": "object",
    "title": "T分類",
    "jesgo:ui:subschemastyle": "inline",
    "properties": {
        "T": {
            "type": "string",
            "enum": [
                "TX",
                "T0",
                "Tis",
                "T1(亜分類不明)",
                "T1a1:脈管侵襲なし",
                "T1a1:脈管侵襲あり",
                (～省略～)
                "T3a",
                "T3b",
                "T4"
            ]
        }
    },
    "if": {
        "properties": {
            "T": {
                "pattern": "^T1a.*"
            }
        }
    },
    "then": {
        "properties": {
            "T1a期 詳細入力": {
                "type": "string",
                "enum": [
                    "水平方向7mm以下",
                    "水平方向7mmをこえる",
                    "不明"
                ]
            }
        }
    }
},
```

2. 上記のスキーマへ更新後、患者台帳(子宮頸がん)を作成
3. 病期診断の"pTNM"にある"T"の選択肢から「T1a～」を選択する

→　**T1a期 詳細入力が表示されない。**
　なお、"cTNM"の方にあるTを入力すると、そちらでは詳細入力が表示される

※"T"はcTNM、pTNM、ypTNMで共通で使用する項目

### 原因
if-thenによるスキーマの書き換え時、書き換え前のスキーマのpropertiesを元に処理していくが
pTNMやypTNMはデフォルトでは存在しないプロパティ(if-thenで後から追加されるプロパティ)のため
書き換え処理が動いていない。
cTNMの方はデフォルトで存在しているプロパティのため、正常に書き換わる
→一応書き換え後のスキーマに対し、再度スキーマ書き換え処理を行うとpTNMでもif-thenが効くようになることは確認済みだが、データ入力時のレスポンスがワンテンポ遅れてしまう
(lodashのcloneDeepが遅い原因だが、必要な処理)

### 対応

**Comment by piyotaicho** [comment]
そうですね、確かにこの手の展開を比較的多用している部分があります。
問題は、この"T1a期 詳細入力"が、値を持つものであるため同様にif~thenで内容を展開しているpTNM、cTNMなどとは扱いが異なる点ですね。
本来これに対応するべく考えたjesgo:disableなどがありましたが、これをif~thenで置き換えてきた手前この書き方は仕方がないですね。

ここでオブジェクトを再構築する際にワンテンポ遅れる点を仕方ないとするか、少しでも速度を改善するた目的でlodash.cloneDeep() を別に置き換えるかですね。
幸いcloneDeepだけであればJSON.parse(JSON.stringify(var))でもlodashよりは早かった気がします。

**Comment by hsc-morita** [comment]
以下のようにデフォルトのプロパティを追加して
```
"cTNM": {
    "$ref": "#/$defs/cTNM"
},
"pTNM": {
    "$ref": "#/$defs/pTNM"
},
"ypTNM": {
    "$ref": "#/$defs/ypTNM"
}
```

thenの中は`{}`をセットしてみましたが、どのif-thenルートに行ってもデフォルトのcTNM、pTNM、ypTNMが表示されてしまう状況でした。
```
"then": {
    "properties": {
        "cTNM": {
            "$ref": "#/$defs/cTNM"
        },
        "pTNM": {},
        "ypTNM": {}
    }
}
```

フィールドを`{}` にした場合の動作ですが、仕様書に書かれている通り
``書き換え不要なフィールドは`"フィールド名": {}`で定義する。
が効いておりますので、`{}`を指定してもデフォルトのプロパティが表示されるという状況です。

if-thenでのプロパティ書き換え後、再度書き換え処理を走らせる方向で検討いたします。

**Comment by hsc-morita** [comment]
@piyotaicho 
修正したものをdevelopmentにマージいたしました。レスポンスも許容範囲内かと思います。
一旦これをデモサーバに反映し、スキーマの方もアップロードいたします。
作業は本日中の予定です。終わりましたら一報いたします。

**Comment by hsc-morita** [comment]
スキーマのPRにも記載しましたが、本件デモサーバに反映済みです。
