### ISSUE TITLE
[schema]ツリー構造のリストの登録値について

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#25]
## 概要
oneOfを使用してツリー構造のリストで表現している項目を登録する場合、値のみが登録される、という動きで認識あっているでしょうか。

例：
```json
"術式": {
    "type": "string",
    "oneOf": [
        {
            "title": "開腹手術",
            "oneOf": [
                {
                    "title": "子宮摘出・子宮頸部摘出術式",
                    "enum": [
                        "腟上部切断術",
                        "単純子宮全摘出術(筋膜内)",
                    ]
                },
                 {
                    "const": "その他の開腹手術"
                }
            ]
        },
     ]
},
```

上記のようなschemaがあった場合、「腟上部切断術」を選択した場合は「腟上部切断術」がそのまま登録されます。
帳票出力やUNIMなど外部システムへの連携をする場合も同様に「術式:腟上部切断術」だけが出力されます。
schemaのtitle部分（「腟上部切断術」を選択した場合は「開腹手術」「子宮摘出・子宮頸部摘出術式"」）もデータ出力時にほしいケースがあるか、気になっての確認でした。

**Comment by piyotaicho** [comment]
必要なのは値だけです。
ツリー構造の選択枝は、項目分けのためにこういう構成になっています。

この例だと、必要な値は「腟上部切断術」だけです。

**Comment by saso-hokuto** [comment]
確認ありがとうございます。承知しました。値のみの登録とします。
