### ISSUE TITLE
[frontend] 新規実装要求

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#252]
jesgo:require が指定されたフィールドについて、入力のボックスをハイライト(薄ピンク？)してほしいとの依頼がありました。スケジュールがタイトですがご検討お願いいたします。

個人的には全体がまっピンクになるのであまり乗り気ではありません。

これをロジックでやると大変なので、jesgo:requireが指定されているフィールドには、div.form-groupにjesgo-require-jsogやjesgo-require-jsgoeといったクラスを追加してCSSでまとめてハイライトのon/offを指定するのが楽かもしれません。（そのかわりどこかにON/OFFのコントロールを仕込まないといけません）

JESGOはSELECTがめちゃくちゃ多いので、SELECTのstyle.backgroundを指定するとOPTIONのドロップダウンも色がついてしまいます。
![image](https://github.com/jesgo-toitu/jesgo-frontend/assets/57445173/c38734f8-8c14-4307-9f66-4401e8738d6d)

ところが、chromiumは今のところbackground: linear/radial-gradient()などをOPTIONのドロップダウンに適応しない仕様なので、この仕様を利用するとinput type="text"とselectだけ狙って色づけすることができます。
(例：style.background = 'radial-gradient(#ffffff 60%, pink)')
![image](https://github.com/jesgo-toitu/jesgo-frontend/assets/57445173/802807ce-509c-412b-9cf5-b17b26e257a0)
(例：style.background = 'linear-gradient(90deg, transparent 95%, pink), linear-gradient(270deg, transparent 95%, pink), linear-gradient(0deg, transparent 65%, pink), linear-gradient(180deg, transparent 65%, pink) ')
![image](https://github.com/jesgo-toitu/jesgo-frontend/assets/57445173/975859d6-1a77-4821-9af9-39eb8a637362)

ちなみに、スキーマのjesgo:require希望項目についての連絡はまだです。

**Comment by saso-hokuto** [comment]
実現方法についてご提案いただきありがとうございます。参考にさせていただきます。

1点、念のため確認させてください。
ハイライトの動きですが、
`required`の枠を赤くする件と同様、未入力の時にON、入力されればOFFにする、という仕様でよいでしょうか？

**Comment by piyotaicho** [comment]
未入力時にハイライトできればよいと思います。
加えてハイライト自体のon/offがあればうるさくならないと思います。

**Comment by saso-hokuto** [comment]
回答ありがとうございます。承知しました。
 jesgo:require の項目のハイライトON/OFFをシステム設定で行えるようにし、
ONの場合は、 jesgo:require の項目が未入力であればハイライトするようにします。

**Comment by piyotaicho** [comment]
#260 のとおり、2023年の登録までの分にはJSOGをたてました。あわせてJSGOEのブランチもマージしています。

**Comment by saso-hokuto** [comment]
ありがとうございます。
参考にさせていただきます。

**Comment by hsc-morita** [comment]
対応済み
