### ISSUE TITLE
[腫瘍登録画面]ドキュメントスキーマに存在しないプロパティの削除機能実装

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#253]
### 概要
ドキュメントのスキーマに存在しないプロパティがドキュメント内にあった場合読取専用で表示する仕様があるが
その項目をボタンで削除できる機能を実装する

### 対応方針
- スキーマに存在しないプロパティの内容表示時、右に削除ボタン(×ボタン)を置いて削除できるようにする
- 通常の読取専用項目と区別するため、拡張ボキャブラリーに`jesgo:notExistProperty`(boolean)を追加し、削除ボタンを付ける項目なのかを判定する

### 仕様
- ドキュメント内にスキーマに存在しない項目(プロパティ)があった場合、入力UIの右に削除ボタンを表示し、ボタン押下で項目ごと削除する
- arrayの項目はarray用の既存の削除ボタンを利用する
	- 通常readonlyの場合削除ボタンは使えないが、スキーマに存在しない項目の場合のみ削除ボタンを有効化する
- arrayおよびオブジェクトの項目は、子項目がすべて削除された場合にプロパティごと削除する

### 対象の値型と表示UIの関係
スキーマに存在しない項目は値型によって表示UIが異なるためそれぞれに対応が必要だが
大別すると`テキストボックス`、`チェックボックス`、`array用UI`の3種類しかない。

|値型|ドキュメントJSON記述例|表示UI|
|:----|:----|:----|
|string|{  "文字列": "aaaa"  }|テキストボックス|
|integer|{  "整数": 10  }|テキストボックス|
|number|{  "小数": 1.5  }|テキストボックス|
|boolean|{  "真偽値": true  }|チェックボックス|
|array|{  "配列": [1, 2, 3]  }|array用UI|
|object|{ "オブジェクト": { "abc": "ABC", "def": "DEF" } }|子の項目に依存|

**Comment by piyotaicho** [comment]
確認しました。これでいいかとおもいます。
![image](https://github.com/jesgo-toitu/jesgo-frontend/assets/57445173/3db3a55e-acc0-457f-8941-f0c639b19fd2)
