### ISSUE TITLE
[バグ]ワイルドカードを含んだsubschemaおよびchild_schemaの指定が正常に動いていない

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#265]
### 不具合内容
スキーマアップロード時、`jesgo:subschema`や`jesgo:childschema`にワイルドカード(`*`)でスキーマ指定していた場合
本来は該当するすべてのスキーマが子スキーマとして登録されるはずが、1件しか登録されない
例）
```json
"jesgo:childschema": [
    "/schema/evaluations/*"
]
```
上記のスキーマの場合、idが"/schema/evaluations/ascites"や"/schema/evaluations/cervix"のスキーマが子として登録されるはずが
"/schema/evaluations/ascites"しか登録されない

### 原因
バックエンド側の処理でワイルドカード指定の場合に複数のスキーマを取得しているが
最初の1件しか登録しないコードになっていた

### 現在の影響
- 再発スキーマの子スキーマが登録されていない
- 病理診断レポートのparentSchemaにもワイルドカードがあったが、こちらは問題なし

### 対応
バックエンド側を修正し、該当するすべてのスキーマを登録するようにする(サブスキーマ、子スキーマの2種類)

**Comment by hsc-morita** [comment]
### 追加対応
既存施設向けに、既に登録されているスキーマに対し、jesgo_document_schemaテーブルのsubschema、child_schemaを更新するAPIを用意する
- `repair-childschema` というAPIを用意する。実行時にユーザ認証は行わないようにする
- curlコマンドなどで実行する。`curl http://localhost:3000/repair-childschema`
- APIの中身は以前からあるスキーマ更新用の関数を呼び出すだけのもの

#### 備考
- スキーマ更新は何かしらのスキーマアップロード時に全件更新されるため、APIを実行せずともいずれ解消される想定
- 配布時にバッチ処理で実行するのが理想

**Comment by piyotaicho** [comment]
ふと思いましたが、このように宙ぶらりんでリンクされないスキーマは管理できないですね。

**Comment by hsc-morita** [comment]
仰る通り、現状以下の問題があります。
- 親子関係が設定されていないスキーマが登録されても管理画面に表示されない
- 存在しないスキーマIDがsubschemaやchild_schemaに設定されていてもエラーにならないため、誤りに気付きにくい

**Comment by piyotaicho** [comment]
スキーマ管理にevent_dateを任意に設定して操作する仕掛けを用意しても良いかもしれませんね。
