### ISSUE TITLE
[バグ]あとから追加されたsubschemaのドキュメント追加が出来ない

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#268]
## 不具合内容

後から追加されたsubscemaのドキュメントが追加できません。
subschemaのワイルドカードの有無に関係なく起こります。
手順は以下です。
  
1. 症例登録済みの既存スキーマにsubschemaを追加し、スキーマ更新
2. 既存データのハンバーガーメニューから追加したsubschemaを追加
3. 画面上は一瞬追加されたように見えるが、追加されていない

child_schemaは問題ありません。
また、child_schema追加後なら、subschemaの追加もうまくいきます。

**Comment by hsc-morita** [comment]
### 原因
サブスキーマをメニューから追加するパターンはunique=false(複数作成可能)なスキーマを追加するパターンしか想定しておらず
saveData更新時に「既に作成済みのサブスキーマの隣に追加する」という処理を行っていたが
サブスキーマが未作成だったため親スキーマのchild_schemaに追加されていなかったのが原因
