### ISSUE TITLE
[schema]誤記と思われる箇所の修正

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#27]
## 概要
いただいているschmeaにて、いくつか誤記と思われる箇所がありました。
jesgoの定義などに合わせて修正したのですが、認識があっているか確認をお願いできますでしょうか。
PR #26 を作成しましたので、そちらをご確認ください。

**Comment by saso-hokuto** [comment]
すみません、あとからrebaseしたためコミットが複数ありますが、 Files changedタブをご確認いただければと思います。

**Comment by piyotaicho** [comment]
とりあえず、問題ないのでmergeしました。dev-とprototype-でよいですかね。
子宮体癌のpTMNについての表記はちょっと文書を確認します。

**Comment by saso-hokuto** [comment]
prototypeへのmergeありがとうございます。
dev-alphaのほうは現在Azureにアップされているものと一致させておきたいので、一旦マージせずにおきます。
子宮体癌のpTMNについて、承知しました。よろしくお願いいたします。

**Comment by saso-hokuto** [comment]
dev-alphaにもマージし、Azure環境にも反映済みです。

**Comment by saso-hokuto** [comment]
5/30目途でスキーマが大幅に更新されるとのことなので、その際に改めて動作確認します。
本件は一旦クローズとします。
