### ISSUE TITLE
[バグ]実施手術の術式で複数項目の順番変更をすると、エラーが発生し入力続行不可になる

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#277]
### 不具合内容
実施手術（"/schema/treatment/operation_procedures"）の術式で、
複数データを登録して順番を変更すると、エラーが発生し入力続行不可になる（画面が真っ白になる）。
値の入力があるデータとないデータが混在すると起こる。
全て未入力/入力済みの場合は起こらない。

### 原因
実施手術（/schema/treatment/operation_procedures）のスキーマの最上位のtypeがarrayで定義されており、
propertiesが空なのが原因でした。
「スキーマになくformDataにある項目をスキーマに追加する」処理の際、
formDataとschema.propertiesを比較していると思いますが、
そこでスキーマがないと判断され（実際は同階層のitemsにある）おかしくなっていたようです。
試しに最上位のtypeがobjectになるようスキーマを書き換えたところ、エラーが発生しなくなりました。

### 問題点
「スキーマになくformDataにある項目をスキーマに追加する」処理が、schema.properties以下のスキーマしか対象にしていない

### 対応
「スキーマになくformDataにある項目をスキーマに追加する」処理で、最上位のtypeがobject**以外**だった場合の考慮が必要。
- string
- integer
- number
- boolean
- array

関連して、削除ボタンでreadonlyの項目を削除された場合も同様の考慮が必要。

**Comment by piyotaicho** [comment]
そうなんですよね。あれはとりあえず列挙型の入力ができればよいだけの入れ物なのでarrayなのです。

JOED5は付随情報として処理しているものがありますが、JESGOでは全てflatになっているためarrayとしています。

**Comment by saso-hokuto** [comment]
情報ありがとうございます。
今後もこのような形のスキーマが追加される可能性はあるかと思いますので、
最上位のtypeがobject以外の場合にも対応できるようにします。

**Comment by saso-hokuto** [comment]
合わせて以下も対応。
- 削除済み項目をreadonlyで表示する件の追加対応
  - 入れ子になったarray
  - arrayのitemsの一部を削除した場合
