### ISSUE TITLE
[schema]フォーム自動生成ライブラリに合わせたスキーマの書き換え

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#29]
## 概要
schemaの記載方法で、使用ライブラリの関係上、そしてカスタムする部分のコーディング量を減らすため、いくつか記述のルールを変えたい箇所があります。問題ありましたら、ご指摘いただきたいです。
※こちらで修正済みのschemaはすでにあるので、問題なければそちらをマージしてPRを出します。

### 1. $refの参照先指定
現在はidで$defsのフィールド指定をしていると思いますが、使用しているJSON Pointerライブラリの仕様に合わせて、#から始まる絶対パスのみ許可したいです。
```json
"properties": {
"pTNM": {
    "type": "object",
    "properties": {
    "pT": {
        "$ref": "#/$defs/T"   // 現在は "$ref": "#T"
    }
    }
},
"$defs": {
    "T": {
        "type": "object",
        "properties": {
            "T": {
                "type": "string",
                "enum": [
                    "TX",
                    "T0",
                ]
            },
        },
    },
}
```
使用箇所：CC/staging.json など

### 2. `"readOnly": true`のフィールドの値
読み取り専用となる`"readOnly": true`のフィールドの値を指定したい場合、ライブラリの既存の仕様に合わせ、`const`ではなく`default`での指定としたいです。
```json
"がん種": {
    "type": "string",
    "default": "子宮頸がん",  // 現在は "const": "子宮頸がん"
    "readOnly": true
},
```
使用箇所：CC/root.json など

### 3. 登録する値と表示ラベルが異なるリスト
登録する値(value)と表示内容（label）が異なる選択リストについて、ライブラリの既存の仕様に合わせて、以下のルールとしたいです。
- anyOfを使用。
- anyOfの中に以下を定義
  - "type":"valueのtype"
  - "enum" : ["value"]
  - "title":"label"

```json
 "判定": {
    "type": "string",
    "anyOf": [
        {
            "type":"string",
            "enum": ["CR"],
            "title": "CR: 完全奏功(complete response)"
        },
        {
            "type":"string",
            "enum": ["PR"],
            "title": "PR: 部分奏功(partial response)"
        }
    ]
},
```
使用箇所：evaluation/tumor_assessment.jsonなど

### 4. 複数typeがあるフィールド
複数Typeを持つドロップダウン（入力（string以外のtype）＋選択）、または入力フィールド（string＋numberなど）を使用する場合、ライブラリのカスタム部分の実装を少なくするため、以下のルールに統一したいです。
- oneOfを使用する。
- フィールドのtypeは指定せず、oneOf内でtypeをそれぞれ指定する。
- oneOfでenumを使用している場合のみ、ドロップダウンとなる。それ以外は入力フィールドとなる。

```json
"T1a期の広がり": {
    // "type": "string",    ★ここではtype指定しない
    "oneOf": [
        {
            "type": "number",
            "minimum": 0,
            "units": "mm"
        },
        {
            "type": "string",
            "enum": [   // ★enumの場合のみドロップダウンとなる
                "7mm以下",
                "7mmを超える",
                "不明"
            ]
        }
    ]
}
```
使用箇所：CC/staging.json,treatment/blood_transfusion.jsonなど

### 5. `additionalProperties`の使用
以前のお打ち合わせでも少しお話ししましたが、使用しているライブラリの仕様上、`additionalProperties:true`を設定すると配列Widgetが自動生成されてしまいます。
#9 で回答いただいた通り、`additionalProperties`は削除してしまってよいでしょうか。
拡張ボキャブラリーに置き換える話もありましたが、そちらでの対応も可能です。

**Comment by piyotaicho** [comment]
それぞれ確認しました。内容の実装的には変わらないので問題ないと考えます。  

5 - additionalPropertiesについては、trueがデフォルトなので削除して構わないです。   
   
ただし、データベースからのドキュメント読み込みで、スキーマ定義にないプロパティを読み込んだときの挙動を決めておかないといけません。  
   
原則的にスキーマ定義にないプロパティを読み込んだ場合は、そのプロパティの値を string として入力フィールドで扱うことにしておけばよいかと思います。

**Comment by saso-hokuto** [comment]
確認ありがとうございます。内容を適用したスキーマをマージしてPRを作成しました。
https://github.com/jesgo-toitu/jesgo-frontend/pull/32

> ただし、データベースからのドキュメント読み込みで、スキーマ定義にないプロパティを読み込んだときの挙動を決めておかないといけません。

こちらについては、スキーマ更新をしたときの挙動をどうするか、も含め決めなければならないと思うので、別途issueをあげておきます。
