### ISSUE TITLE
[バグ?] zipファイルの展開不良？

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#290]
トランザクションで括るのをを忘れていてこちらの検証環境にあるDBのスキーマを飛ばしたので、白紙の状態からzipでまとめてアップロードをしてみました。

すると、1～2のjsonファイルが弾かれました。
単品では問題なく処理されましたのでzipの展開に何らかの問題があるかもしれません。

backendをunzipper@0.10.14にあげてビルドしてみましたが変化がありません。
WindowsのZIP作成、7-zipでの作成いずれでも同様です。

**Comment by hsc-morita** [comment]
ご指摘ありがとうございます。
確認したところ少々状況が異なるかもしれませんが、以下の不備がありました。
[手順]
schema_id=0のレコード以外を物理削除し、スキーマアップロードにてshema、shema_v1.0をまとめたZIPをアップロードする
(バックエンドのdevelopmentブランチにて実施)

[状況]
- 74件のアップロードに成功し、バージョン被りのスキーマはエラーが発生(正常ケース)
	- **ただし、エラー表示されるファイル名とスキーマIDが合っていない**
- 同じスキーマIDでバージョンが異なるものはINSERTされた
- **再ログインするとローディング状態のまま画面遷移しなくなる**

[原因]
#### 1. エラーのファイル名とスキーマIDが合っていない件
同一スキーマIDのファイルがある場合古いバージョンから処理されるようソートをかけて順次処理しておりましたが
JSON格納array(ソート済み)とファイル名格納array(未ソート)で同じインデックスのデータを参照していたため表示がズレておりました。
※エラー表示のみの問題です。スキーマ自体はバージョンごとに登録されておりました。

#### 2. 再ログインすると画面遷移しなくなる件
jesgo_document_schemaテーブルのinherit_schemaがnullのレコードがあったことによりエラーが発生しておりました。
inherit_schemaはスキーマアップロード時に更新されますが、最新バージョンのスキーマしか更新しない動作だったため
複数バージョンを同時にアップロードした場合過去バージョンのスキーマが更新されないという状況でした。

修正次第PRを上げますので、お手数ですがそちらで再度ご確認ください

**Comment by hsc-morita** [comment]
https://github.com/jesgo-toitu/jesgo-backend/pull/71
こちら修正してPRしております。

**Comment by hsc-morita** [comment]
対応済み
