### ISSUE TITLE
[バグ] units があると visibleWhen が機能しない

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#291]
```
"properties": {
  "昼メニュー": {
    "type": "sting",
    "enum": [ "定食", "カレー" ]
  },
  "辛さ": {
     "type": "number",
     "units": "倍",
     "jesgo:ui:visibleWhen": {
        "properties": {
           "昼メニュー": {
              "const: "カレー"
           }
        }
     }
  }
}
```
上記、unitsを削除すれば目的通りの動作をします。

**Comment by piyotaicho** [comment]
あ、ちなみに、これは抜粋でarrayのitemです。

**Comment by hsc-morita** [comment]
[調査メモ]
ArrayFieldTemplate内の処理の不備
`const parentClass = element.parentElement?.className;`
として親のクラス名を取得してvisiblewhenの項目か判定していたが、単位付きのテキストボックスの場合1つdivを挟んでいるため、`element.parentElement?.parentElement?.className;`のように親の親を取得しないと判定できない

**Comment by hsc-morita** [comment]
対応済み
