### ISSUE TITLE
[実装忘れ] 合併症アイコン

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#293]
先ほど、合併症アイコンのことを指摘されました。最初のリリースから忘れ去っていました。取り急ぎ表示だけ実装しました。

ドキュメントに手術タグありの場合、合併症タグ(新設) "jesgo:tag": "has_complications" を確認してステータスを保持するようにしました。
実際の合併症入力ではなく、合併症のあり・なしの入力でみています。

**PRs**
- https://github.com/jesgo-toitu/jesgo-backend/pull/73
- https://github.com/jesgo-toitu/jesgo-schema/pull/49

**リスト検索には未対応**
backend/frontendにcomplicationのtypoと思われるcopilacationsというuserDataのプロパティがありますが代入が無いため機能していません。それにあわせて検索の合併症（と、3年・5年予後入力も）checkboxがdisabledになっています。

**Comment by hsc-morita** [comment]
実装漏れており大変申し訳ありません。
検索機能についても修正を試みます。

**Comment by hsc-morita** [comment]
検索機能も対応済み
