### ISSUE TITLE
継承スキーマの継承関係について

### ISSUE THREAD

**Issue by kosaka-hokuto** [jesgo-toitu/jesgo-frontend#30]
### 概要

現在継承スキーマは$idの値に沿って、「"$id":"/schema/foo/bar" は "$id":"/schema/foo" を継承した派生スキーマ」
として定義されておりますが、継承先の継承(孫)まで考慮する必要はありますか？
```
例)
親："$id":"/schema/foo"
子："$id":"/schema/foo/bar"
孫："$id":"/schema/foo/bar/baz"
```
また、孫を考慮する場合は親のスキーマのコントロールボタンに子だけでなく孫の切替を表示する必要はありますか？

**Comment by piyotaicho** [comment]
あまりに複雑になるので孫はなしにしましょう。
- 親 "$id": "/schema/foo"
- 子 "$id": "/schema/foo/bar"
- これも子 "$id": "/schema/foo/bar/hoge"
という扱いでゆきましょう。

**Comment by kosaka-hokuto** [comment]
ご回答ありがとうございます。その方向で対応させていただきます。
