### ISSUE TITLE
[患者一覧]5年予後の「未」アイコンが5年未満でも表示される

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#300]
### 不具合内容
初回治療日から5年たっていないデータでも、予後の日付入力がなければ「未」アイコンの表示対象となってしまう。

- 実行日：2023/12/05
- 初回治療開始日：2018/12/06
- 5年予後の日付：未入力
（ちなみに、初回治療開始日が「2018/12/07」ではアイコン非表示、「2018/12/05」だと表示されます）

5年予後の検索も同様。

### 原因
現在日と初回治療開始日の差分計算で、1年を365日で計算しているため、うるう年を含む期間だと「5年後」となる日付がずれる。

```TypeScript
export const isAgoYearFromNow = (date: Date, year: number): boolean => {
  logging(LOGTYPE.DEBUG, `呼び出し`, 'Utility', 'isAgoYearFromNow');
  const compareDateMillSec = new Date().getTime() - date.getTime();
  // ミリ秒の差を日数に直す
  const compareDay = compareDateMillSec / (24 * 60 * 60 * 1000);
  // N年*365日より差が大きかったらN年以上立ってるものとする
  return compareDay > year * 365;
};
```

**Comment by piyotaicho** [comment]
おっと。これはアレですね。
満3年、満5年が基準となりますので、例えば次回1月1日からはじまる2023年分の登録では、3年が2020年の症例、5年が2018年の症例となるようです。
つまり、2024年1月1日の時点で登録有無について3年のフラグが2020年症例、5年のフラグが2018年症例に立てばよいかたちになります。
つまり、比較はgetYear()で十分ということになりますね。

**Comment by hsc-morita** [comment]
確認ありがとうございます。承知しました。
3年予後、5年予後の判定は年だけを見て判定するようにいたします。
(例：初回治療日が2020/12/31の場合、2023/01/01を持って3年予後の対象とする)

**Comment by piyotaicho** [comment]
予後登録の実施をみていますから、チェック開始は2024/1/1でよいかとおもいます。

**Comment by hsc-morita** [comment]
失礼しました。「初回治療日が2020/12/31の場合、2024/01/01を持って3年予後の対象とする」が正しいです。
コード的には以下になります。
```js
export const isAgoYearFromNow = (date: Date, year: number): boolean => {
  logging(LOGTYPE.DEBUG, `呼び出し`, 'Utility', 'isAgoYearFromNow');

  const yearDiff = new Date().getFullYear() - date.getFullYear();
  return yearDiff > year; // ←yearは3年 or 5年
};
```
