### ISSUE TITLE
jesgo:requiredのハイライト追加要望

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#303]
#282 で要望があった件。

> - jesgo:requiredのハイライトについて
>    - アプリケーションの設定でハイライトのON/OFFについてデフォルトが決められないか
>    - JSOG, JSGOEそれぞれで表示非表示を設定できないか
>    - _将来jesgo:requiredの項目が独自拡張しても対応できるように備えておいてもよいかもしれない、アイコンで無くて文字だけならいけそう_

以下を対応する。

1. JSOG、JSGOE、それ以外（独自拡張分）で分ける
現在はJSOGとJSGOEの項目をまとめてハイライトON/OFFをしているが、それを3つに分ける。
CSSクラスを分けて対応する。
症例登録画面の「JSOG/JSGOE必須項目ハイライト」も3つに分ける。

2. ハイライトのデフォルト
システム設定にデフォルト値を追加する。
ここで設定した値が、症例登録画面のON/OFFのデフォルト値となる。
こちらもJSOG、JSGOE、それ以外（独自拡張分）でそれぞれ持つ。

3. ラベル色の追加
JSOGはグレー、JSGOEは水色でラベル表示をしているため、独自実装分も別の色にする。
bootstrapのbsStyleを指定して色を変えているので、その中の色のどれかを割り当てる。（success ：緑を想定）

独自拡張分も項目の値によってそれぞれ別の項目として扱えるのが理想ではあるのですが、
動的にすると影響範囲が大きすぎるため、今回はこの方向で進めたいと思っています。

**Comment by saso-hokuto** [comment]
[追記]
ハイライトのデフォルト値がシステム設定に無い場合は、OFFとして扱う。
（既存施設でもDBのUPDATEなしで動くようにするため）

**Comment by hsc-morita** [comment]
対応済み
