### ISSUE TITLE
今更ながらに機能追加

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#308]
backendのドキュメント生成に手を加えて、プロパティに "jesgo:schema_id" としてスキーマid文字列を埋め込むように拡張しました。
https://github.com/jesgo-toitu/jesgo-backend/pull/80

スキーマ定義ドキュメントにスキーマの予約語として "jesgo:document_id" に加えて "jesgo:schema_id" も追加してください。

**Comment by hsc-morita** [comment]
対応済み
