### ISSUE TITLE
症例入力レイアウト見直し

### ISSUE THREAD

**Issue by yoshiaki-hokuto** [jesgo-toitu/jesgo-frontend#31]
4/14 dev-alphaで対応したレイアウト見直し内容のまとめ

- 入力コントロールの横幅を調整
  - ドロップダウンリストは autoとして選択文字列の内容で自動調整(minwidthは150px)
  - 入力可能ドロップダウンリストは150px固定とした
  - 日付コントロールは150px固定
 
- ドキュメント追加ボタンの配置をタブに重なるようにし縦の表示量を増やした

- jesgo:ui:subschemastyle:inlineに相当する機能を実装
  - ドキュメント単位で項目を行方向に配置するように改修
  - スキーマ定義は、jesgo:ui:subschemastyle": "column"を適用した箇所
      - titleとコントロールの行方向へ配置する対応は未対応
  - 但し、jesgo:ui:subschemastyle:tabの指定と競合するため定義方法は今後見直す

- arry指定の項目を1レコード内で行方向に配置するように改修

- 行間のmarginをすくなするように見直し

**Comment by piyotaicho** [comment]
お疲れ様です。  
marginを減らすのと、arrayの再配置ではだいぶスッキリしてきたと思います。  

- "jesgo:ui:subschemastyle": "column" は先のスキーマの問題整理でなくなりました。まだ残っていたら削除しておきます。現在見たところ、展開として"inline"がデフォルトになっているようですが、"noindent"で縦に並べるものがデフォルトになっております。  
- 画面幅が若干狭い状態になると .patient-area のボックスサイズ変動に .registration-area が被ってしまいます。.patient-areaのpositionがfixedになっているので、その影響だと思います。画面サイズの変動は考慮した方が良いので、.page-area でページ全体のボックスを定義して、内部はflexで上から流して結果固定されている方が無難だと思います。  
- 単位はpxよりはremに換算しておいた方が、mac/windows混在で使用するフォントもバラバラですので安全と感じます。
- フォントも游ゴシックを指定してフォントによるレイアウトの変化を最低限にする方法もありますが、結局フォントウエイトの問題があるのであんまり上手い感じはしません。https://github.com/piyotaicho/JOED/blob/master/src/cross-plathome-yu-gothic.css いっそのこと、BIZ UDがSIL openで利用できるのでガチガチに固定してしまうのも一案かもしれません。

**Comment by yoshiaki-hokuto** [comment]
確認ありがとうございます。
"jesgo:ui:subschemastyle": "column" は弊社で埋め込んだものもありますので、noindentに戻します。
arrayはinlineで再配置した状態とします。

**Comment by yoshiaki-hokuto** [comment]
取り急ぎヘッダが他のUIに重なってしまう問題を修正してコミットしました。Azure環境にも反映済み。
フォントの選定は少しお時間ください。

**Comment by yoshiaki-hokuto** [comment]
対応が遅くなり申し訳ございません。
フォントをBIZUDPGothicに変更しフォントサイズもremに修正しています。
Azure環境にも反映済みです。

**Comment by piyotaicho** [comment]
ありがとうございます。確認しました。  
BIZUDをドキュメント以外、UIに使っているのを初めて見ましたがすごいですね、そこはかとない高級感が。

**Comment by yoshiaki-hokuto** [comment]
確認ありがとうございます。
レイアウトの見直しは引き続き実施するとして本課題は一度クローズします。
フォントに関しては利用する皆様のご意見もあると思いますが、Webフォントを適用する方針といたします。
