### ISSUE TITLE
プラグインに有効/無効フラグを追加する

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#311]
山本先生のメールより
> ただ気になったのは、スクリプトの数がかなり多くなるので一時的な有効無効を管理出来たほうがよいと思いました。
> 拙宅今回alter tableも掛かりますし、施設数が増えたあとでalter tableをかけるのは気が引けるので、DB の jesgo_plugin に disabled boolean default false というようなカラムを用意しておくのを提案します。

## 対応方針
- jesgo_pluginテーブルにdisabledカラム(boolean default false)を追加し、プラグインの有効/無効を設定できるようにする
- **公開までに実装が間に合わない可能性があるため、カラムの追加だけは先に対応・マージする**
- 最終的にはプラグイン管理画面で有効/無効の切り替えをできるようにする

#### 配布時のSQL
```sql
ALTER TABLE jesgo_plugin ADD disabled boolean default false;
UPDATE jesgo_plugin SET disabled = false;
```

**Comment by hsc-morita** [comment]
取り急ぎ実装しております。

![image](https://github.com/jesgo-toitu/jesgo-frontend/assets/101262997/d03def40-8ee3-482f-a6c3-0c23be3b1e31)

### 仕様
- プラグイン管理画面に「有効」のチェックボックスを追加
- jesgo_pluginテーブルのdisabledがfalseの場合はチェックON(有効)、disabledがtrueの場合はチェックOFF(無効)となる
- プラグイン画面上から有効チェックをON/OFFでdisabledを設定できる
- 保存ボタン押下でDBへ保存する
- 未保存データがある状態での画面遷移は警告を表示する

- disabled=true(無効)なプラグインは各種画面のプラグインメニューからは非表示となる

**Comment by piyotaicho** [comment]
ありがとうございます。

あと、多分ですがプラグインもzipでまとめて登録ができないようです。

**Comment by hsc-morita** [comment]
> あと、多分ですがプラグインもzipでまとめて登録ができないようです。

ローカルで試してみましたが、ZIPで複数ファイルアップロードしても登録されました。
何か条件があるかもしれませんが今のところ発見できておりません。
