### ISSUE TITLE
eventdateの系譜について

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#312]
2024年1月1日でスキーマが切り替わるのですが、2023年治療開始症例については2023年のスキーマが適応されます。
/schema/*/rootから連なる登録に関わるchild_schemaのeventdateは/scehma/*/rootのeventdateを引き継ぐ必要があります。
手術・化学療法・放射線治療のスキーマからeventdate設定を取り除こうと思います。

**この点については2024年にはみ出す入力をされてしまう前に既存施設にはスキーマの更新を促さないといけません。**

**Comment by piyotaicho** [comment]
と思ったら、再発治療の件が難しくなりますね。困った。

**Comment by piyotaicho** [comment]
**問題点の整理**
- 子スキーマでeventdate設定なし
  - 患者台帳の初回治療日を継承してスキーマは適切に更新される→O
    - 台帳は登録に関わる部分なので書き換わるとロジカルチェック・書き出しに影響しうる
    - 運用上これで問題はない
  - 再発の再発確認日を継承してスキーマはずっと更新されない→△本当は更新されてほしい（治療、特に化学療法は進歩する）
    - 再発入力がどのくらい利用されているかわからないが当面は問題が表面化しない

**現実的な解決法**
全てのスキーマでトリガとなる日にちがあるならばeventdateを設定しておく（今まで通り）。  
親スキーマで子スキーマに親のeventdateを強制的に適応するか決めるボキャブラリを新設(例： "jesgo:inheriteventdate": boolean)
  - true 子スキーマで入力されたeventdateは無視され、スキーマ切り替えのトリガとならない
  - false 子スキーマに入力されたeventdateは子スキーマのもの、入力がなければ親スキーマのeventdateを継承
  - ドキュメントツリーの子スキーマで inheriteventdate が宣言された場合、そこで一旦親ドキュメントのeventdateでの上書きが途切れる

**Comment by piyotaicho** [comment]
めも：
- frontendのDBUtility.tsのgetEventDateを弄れば実現出来そう

**Comment by piyotaicho** [comment]
上記やりました。一応こちらで検証する限り目的の動作をしています。
#318 
jesgo-toitu/jesgo-backend#84
jesgo-toitu/jesgo-schema#59

**Comment by hsc-morita** [comment]
対応ありがとうございます。動作確認できたためマージいたします。
