### ISSUE TITLE
[バグ]Arrayで空行と値がある行で順番変更をすると、順番が変更されない

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#315]
### 不具合内容
Arrayの中身がリストのみの場合に保存後に空欄と値がある行の順番変更をすると、どちらも値ありになる。
内部的には入れ替え後の値になっている。
データ保存前は起こらない。 

### 原因
空欄の値が、保存前は`undefined`だが、保存後は`null`になっているため。
<select>での未選択は空文字か`undefined`であるべき。

### 対応
DBのデータ取得後に`null`を`undefined`に変換する処理を追加。
LayerDropdownを使っているコンポーネントはそれだけでは直らないため、
valueを空文字に置き換える処理を追加。

**Comment by hsc-morita** [comment]
対応済み
