### ISSUE TITLE
[バグ]症例登録でのエラー表示時、オブジェクト中の項目にエラーがある場合オブジェクト名が表示されない

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#329]
### 不具合内容
以下は診断所見の腟壁浸潤の「所見」とその他のリンパ節転移の「所見」でエラーが出ているが
オブジェクト名がなく、項目名がどちらも「所見」のためどこでエラーになっているかわかりにくい

![image](https://github.com/jesgo-toitu/jesgo-frontend/assets/101262997/2b0e1507-7f49-4ea6-b69e-c6d662f424ab)

### 対応
`[ 腟壁浸潤 ＞ 所見 ]`のように親のオブジェクト名も表示するよう対応する

**Comment by saso-hokuto** [comment]
### 対応（追記）
- Arrayのitem内でobjectが入れ子になった場合も考慮する
