### ISSUE TITLE
スキーマ定義にないプロパティを読み込んだときの挙動

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#33]
## 概要
データベースからのドキュメント読み込みで、スキーマ定義にないプロパティを読み込んだときの挙動を決めておく必要がある。

例）原則的にスキーマ定義にないプロパティを読み込んだ場合は、そのプロパティの値を string として入力フィールドで扱う

また、その前段階として、スキーマ更新時の仕様についても整理・検討が必要。

**Comment by piyotaicho** [comment]
スキーマに拡張スキーマなどが設定されて、なにかあったときには対応が必要なので 基本的にプロパティ値をスキーマ記載の適当な型で対応でよいとおもいます。
{
 "hoge": "Hello",
 "foo": 10,
 "bar": false
}
については、上から string, number, boolean と適当な型の編集で良いと思います。
（コントロールとしてはbooleanだけがチェックボックスになりますかね）

**Comment by hsc-morita** [comment]
以下の仕様にいたします。arrayとobjectの対応も追加しております。

## スキーマ定義にないプロパティがドキュメントにあった場合の仕様
- ドキュメント側のプロパティの値型からスキーマを生成し、元のスキーマへ一時的に追加することにより  
ドキュメントへ表示できるようにする
- 項目名はプロパティ名とする
- 一時的に追加されたプロパティはreadonlyとして編集不可とする

### 値型変換対象
- 文字列型(string)
	- type: string として表示
	- UI: テキストボックス
- 数値型(number)
	- type: number として表示
	- UI: テキストボックス
- 論理型(boolean)
	- type: boolean として表示
	- UI: チェックボックス
- オブジェクト型(object)
	- type: object として表示
	- オブジェクトのプロパティを解析して適切なスキーマをitemsに設定する
- 配列
	- type: array として表示
	- 配列の値型を判定して適切なスキーマをitemsに設定する
	- オブジェクトの配列の場合は配列内のオブジェクトのプロパティをすべてマージしたスキーマを生成する(※注1)
- 上記以外
	- type: string として表示
	- 表示欄はテキストボックス


#### ※注1：オブジェクト配列のマージについて

例）ドキュメントの内容が以下の時(オブジェクトの項目が異なるケース)
``` 
"タイトル": [
	{
		"項目A": "AAA",
		"項目B": "BBB"
	},
	{
		"項目A": "aaa",
		"項目C": "ccc",
	}
]
```

各オブジェクトの項目をマージし、以下のスキーマを生成する
```
"タイトル": {
	"type": "array",
	"items": {
		"type": "object",
		"properties": {
			"項目名A": {
				"type": "string"
			},
			"項目名B": {
				"type": "string"
			},
			"項目名C": {
				"type": "string"
			},
		}
	}
}
```
