### ISSUE TITLE
Chrome バージョン84以前だとログインできない

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#334]
## 概要
JESGO導入事例で以下のようなお問い合わせがあり調査
```
サーバではJESGOが使用できるがクライアントから使用できないとのお問い合わせがありました。
（サーバへの接続に失敗しました　と出る）

確認した結果、サーバ上のedgeのバージョンが121.0.2277.98、
クライアントのバージョンが44.17763.831.0と古いものを使用しているため正常に使用できない状況かと思われます。
その他、chromeも同様のようでクライアントのバージョンが83.0.4103.97だとログインできず、121.0.6167.140だとログイン出来たとのことでした。
```

## ブラウザバージョンによる動作確認
以下入手できたChromeにて確認
- 83.0.4103.116：ログイン**失敗**
- 84.0.4147.135：ログイン**失敗**
- 86.0.4240.75：ログイン成功
- 90.0.4430.72：ログイン成功

v84以前では動作しない？v86以上で動作する
Edgeは確認できなかったがChromiumベースのためメジャーバージョンはChromeに追従している。
そのためEdgeも同様にv86以上で動作すると推測される
※指摘のあったEdgeのv44はChromiumベースではないため、動作保証外

## 原因
ログインのAPIを実行すると`ERR_BLOCKED_BY_RESPONSE`というエラーが発生していた。
~~これを元に調査するとAPIのHTTPレスポンスヘッダーに`X-Frame-Options`がないことが原因？~~
→レスポンスヘッダーの「Cross-Origin-Resource-Policy」が`same-origin`になっているとエラーが発生

## 対応
~~バックエンド側を修正し、レスポンスヘッダーに`X-Frame-Options`を設定するとログインできるようになった~~
```js
const app = express();
// ↓を追加
app.use(helmet.frameguard({ action: "SAMEORIGIN" }));
app.use(cors());
```

→上記のコードだと元々`helment()`で設定していたデフォルトのヘッダーがセットされなくなっていたため現象が解消されていた。X-Frame-Optionsは関係なさそう
`Cross-Origin-Resource-Policy`を`cross-origin`にすれば一応ログインできるようにはなった。

また、Chrome起動時にパラメータを指定してセキュリティポリシーを一時的に無効化することでもログインできるようになった。
```
chrome.exe --user-data-dir="C://ChromeTmpUser" --disable-web-security
```
※上記は最終手段

**Comment by piyotaicho** [comment]
いま確認してみましたがバックエンドは未対応でもX-Frame-Options: SAMEORIGINはついているようです。
![image](https://github.com/jesgo-toitu/jesgo-frontend/assets/57445173/7ceef4da-ca57-44ab-b73a-20afcb739626)

対応が必要なのはフロントエンドのほうでは？

ただ、動作についてEdgeやChromeの要件としてバージョンは記載して置いた方がよさそうですね。

**Comment by hsc-morita** [comment]
確認ありがとうございます。引き続き調査したところ、`X-Frame-Options`ではなく`Cross-Origin-Resource-Policy`に`same-origin`が設定されているとブロックされるようでした。

**Comment by hsc-morita** [comment]
手順書にv86以降と記載するだけに留める→対応済みのためクローズ
