### ISSUE TITLE
[データ出力系プラグイン]出力データがない場合のOutputViewの表示について

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#340]
### 概要
データ出力系プラグイン実行時、出力結果の表示にOutputViewを別タブで表示していますが
プラグインのmain関数の戻り値がundefined(returnしていない場合も含む)やnullの場合でも必ずOutputViewを表示しています。

OutputViewを用いず独自のダイアログなど表示したいケースでも必ず表示しているため、余計なタブが表示されることになります。

### 背景
実装中のテキストコピー機能にて、別画面をポップアップし出力結果を表示するようにしておりますが
別画面を表示した後にOutputViewが開かれるため、ポップアップさせた画面が後ろに隠れてしまいます。
ウィンドウのfocus()やblur()を呼び出してみましたが、モダンブラウザでは最前面化は制限されているため対処できませんでした。
※モーダルにはあまりしたくない

### 対応
フロントのOutputViewを開く関数内で表示データのnullチェックを行い、null(undefined)の場合は画面オープンをキャンセルする
```js
export const OpenOutputView = (
  win: typeof window,
  srcData: any,
  type: string | undefined = undefined
) => {

  if(srcData == null) {
    return;
  }
```

@piyotaicho 
こちらの仕様で特に問題がなければ対応したいと考えておりますが、よろしいでしょうか？

**Comment by piyotaicho** [comment]
実質出力が無いものはこれで構わないと思います。
※モーダル大好き
