### ISSUE TITLE
患者リストのCSV作成時、初回治療開始日が未入力の患者が出力されない

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#344]
### 内容
患者リストの右上にあるCSV作成にて患者リストをCSV出力できるが
初回治療開始日が未入力の患者が除外されて出力される

仕様としては初回治療開始日の入力有無は無関係のはずのためNG？

### 修正方法
初回治療開始日の入力有無に関わらずCSVを出力するように修正する
- CSVデータ作成処理内の`if (userData.startDate)`の条件を外す
- ifを外すと`startDate: userData.startDate,`の部分で"型が異なる"と怒られるため、`startDate: userData.startDate ?? '',`のようにnullならば空文字を返すようにする
※フロントのソースを`setCsvData`で検索するとCSVデータ作成処理が発見できます

**Comment by toitu-nomura** [comment]
@ina-osm 
本件、リリースいただいた資源で修正を確認しました。
