### ISSUE TITLE
[バグ]11桁以上のパスワードで利用者登録すると、登録エラーになる

### ISSUE THREAD

**Issue by toitu-nomura** [jesgo-toitu/jesgo-frontend#346]
画面上は「8文字以上20文字以内」と表示されていますが、
11桁以上で登録すると登録エラーとなります
![image](https://github.com/jesgo-toitu/jesgo-frontend/assets/98132235/3e70f258-955c-462e-bfcf-4723678607df)

**Comment by toitu-nomura** [comment]
@ina-osm 
本件、リリースいただいた資源で修正を確認しました。

**Comment by ina-osm** [comment]
@toitu-nomura 
確認いただいたのでクローズいたします
