### ISSUE TITLE
【不具合】MISの入力内容

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#347]
スキーマの方に手を入れました。
https://github.com/jesgo-toitu/jesgo-schema/pull/71

**Comment by toitu-nomura** [comment]
@ina-osm 
本件、リリースいただいた資源で修正を確認しました。

**Comment by ina-osm** [comment]
@toitu-nomura 
確認いただいたのでクローズいたします
