### ISSUE TITLE
【不具合】初回治療開始日が未入力の場合にCSV出力できない

### ISSUE THREAD

**Issue by ina-osm** [jesgo-toitu/jesgo-frontend#348]
患者リスト表示画面のCSV作成ボタンからCSV出力を行う際に、各台帳の初回治療開始日が未入力の患者が出力されない
→初回治療開始日が未入力の場合でも出力対象とする

**Comment by toitu-nomura** [comment]
@ina-osm 
本件、リリースいただいた資源で修正を確認しました。

**Comment by ina-osm** [comment]
@toitu-nomura 
確認いただいたのでクローズいたします
