### ISSUE TITLE
プラグイン名称変更、プラグイン実行方法変更(患者データ一括取込)

### ISSUE THREAD

**Issue by ina-shr** [jesgo-toitu/jesgo-frontend#352]
①プラグイン名称変更
　　　　　　　　変更前　　　　　　　　　　　　　　　　　　　変更後
患者データ一括登録（子宮頸がん）2023年用　→　患者データ一括取込（子宮頸がん）2023年様式
患者データ一括登録（子宮頸がん）2024年用　→　患者データ一括取込（子宮頸がん）2024年様式
患者データ一括登録（子宮体がん）2023年用　→　患者データ一括取込（子宮体がん）2023年様式
患者データ一括登録（子宮体がん）2024年用　→　患者データ一括取込（子宮体がん）2024年様式
患者データ一括登録（卵巣がん）2023年用　　→　患者データ一括取込（卵巣がん）2023年様式
患者データ一括登録（卵巣がん）2024年用　　→　患者データ一括取込（卵巣がん）2024年様式

②プラグイン実行方法変更
<現行仕様>
プラグイン選択より各年のプラグインを選択
<変更後仕様>
プラグイン選択では「患者データ一括取込」という入り口だけ作成、
クリックすると別窓で各年の取込プラグインを選択して実行するイメージ

**Comment by toitu-nomura** [comment]
@ina-osm 
本件、リリースいただいた資源で修正を確認しました。
