### ISSUE TITLE
プラグイン実現方法の決定

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#4]
## 概要
プラグイン実現方法について、要検討。

**Comment by piyotaicho** [comment]
バックエンドにnodejsを使うので、もう面倒ついででnpmの仕掛けを利用させて貰うのが楽だとは思います。
ZIPファイルの中身。

- plugin-name
   - node_modules/
      - required_module1/
   - scripts/
      - index.js
      - library1.js
      - library2.js
   - schema/
      - option_schema.js
   - package.json

package.json にプラグインの機能呼び出しなどを内包しておけば呼び出しにあたっての動作も比較的簡単になりますね。プラグインとバックエンドとのインターフェースが重要になると思いますのでここが最大の要検討です。
