### ISSUE TITLE
[schema]treatment/operation_adverse_events.jsonの書き換え

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#49]
## 概要
schemaの記載方法で、使用ライブラリの関係上、そしてカスタムする部分のコーディング量を減らすため、
treatment/operation_adverse_events.jsonのスキーマを書き換えたいと考えています。動きは変わりません。
内容としては、以下です。
- `"type": "array"`のみのフィールドはエラーとなるため、itemの設定がない`"type": "array"`を削除。
- `"type": "array"`で値（enumなど）の設定はあるが、`items`の宣言がない箇所は、`items`と`type`を追記。
-  登録する値と表示ラベルが異なるリストはanyOfを使用
    - #29 の3.で確認いただいた内容です

PRを作成しましたので、内容についてご確認をお願いできますでしょうか。

**Comment by piyotaicho** [comment]
よく見たら、AEについてはかなり複雑なので内容が未実装でした、申し訳ない。

**Comment by saso-hokuto** [comment]
承知しました。
AEについては、スキーマ更新いただけましたら、改めて動作確認をします。

**Comment by saso-hokuto** [comment]
5/30目途でスキーマが大幅に更新されるとのことなので、その際に改めて動作確認します。本件は一旦クローズとします。
