### ISSUE TITLE
【テスト】日付入力のフィールド移動

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#55]
日付入力フィールドへの入力  
- 19601101 → 196011/01/dd
- 1960/11/01のような区切り文字での入力はできない

**Comment by piyotaicho** [comment]
年のフィールドだけがおかしいようです。

**Comment by yoshiaki-hokuto** [comment]
年だけ4桁を超える入力ができてしまうため、制限を追加しました。
Azure環境にも反映済みです。

**Comment by piyotaicho** [comment]
まだ反映されませんね。

併せて弊害として今年よりも先の年号の入力が可能となっています。
さすがにこれは単純なロジックで防ぐ必要がありそうです。

**Comment by saso-hokuto** [comment]
5/26の打ち合わせで問題ないことを確認いただいた。
未来日チェックについては別課題がありますので、本件はクローズします。
