### ISSUE TITLE
【テスト】利用者管理からリストへの遷移

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#57]
- 閉じるボタンがグレーアウトしていて機能するのかわかりにくい
- 閉じるボタンの表記も閉じるわけではないので、リストに戻るのほうがよいかもしれない

**Comment by yoshiaki-hokuto** [comment]
ボタン文言を「リストに戻る」とし、色もブルーに変更しました。
Azure環境にも適用済みです。
