### ISSUE TITLE
継承スキーマについて

### ISSUE THREAD

**Issue by kosaka-hokuto** [jesgo-toitu/jesgo-frontend#58]
## 概要

継承機能において以下のように実装します。運用上、問題がありそうでしたらご指摘ください。

### フォームの引継ぎ
- フォームは引継ぐに際し、同項目名でも入力形式が異なるものがあるため、一括で引継ぎを行いません。
  - 継承時に入力中の内容が削除される旨を表示します。

### 継承先、基底スキーマの選択
- コントロールボタンで継承スキーマ、基底スキーマへの変更(継承)を行います。
- 基底スキーマは常に現在のスキーマから辿れるもっとも上にあたる親とします。
  - 以下の例で自身がA''(```aaa/bbb/ccc```)であった場合、A'(```aaa/bbb```)まででなくA(```aaa```)まで辿ります(ない場合は途中で止まる)。
- 継承先は上記で決定した基底スキーマから見た継承スキーマすべてを対象とします。
  - 以下の例で自身がA''(```aaa/bbb/ccc```)で基底スキーマがA(```aaa```)であった場合、B'(```aaa/zzz/yyy```)も継承先として選択できるようにします。
  
```
# 継承スキーマ例
A aaa
A' aaa/bbb
A'' aaa/bbb/ccc
B aaa/zzz
B' aaa/zzz/yyy
```

**Comment by piyotaicho** [comment]
先日の面談での議論通り、これでよしとします。これ以上細かくすると大変です。

**Comment by kosaka-hokuto** [comment]
ご回答ありがとうございます、上記で対応させていただきます。
