### ISSUE TITLE
subschema/child_schemaの定義について

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#59]
## 概要
subschema/child_schemaの定義について、2点確認させて下さい。

### 1. subschema、child_schemaの定義について
subschema、child_schemaの決定方法について改めて整理しました。

#### subschema
 - 動作
   - 自動で展開される。ユーザーによる並び替えや追加・削除は不可。
 - スキーマでの定義方法
   - `jesgo:subschema`で$id指定しているスキーマ

#### child_schema
- 動作
  - 自動で展開されない。ユーザーによる並び替えや追加・削除が可能。
- スキーマでの定義方法
    - `jesgo:childschema`で$id指定しているスキーマ
    - 自分の$idが`jesgo:parentschema`で指定されているスキーマ

#### 関係性
 - subschemaとして指定されたスキーマは、child_schemaとしては扱わない
   - ※#34でご提案している、child_schemaにsubschemaを包含しない前提で記載しています

以上を前提として、以下確認させてください。
「卵巣がん＞病期診断(OV/staging.json)」は、親の「卵巣がん(OV/root.json)」でsubschema指定されている、かつ、parentschemaで卵巣がんを参照しています。
この場合、「卵巣がん」から見て、「病期診断」はsubschemaとして扱う（child_schemaとしては扱わない）という解釈でよいでしょうか？
   

### 2. subschmaでuniqueではないケース
運用上、親を開いたときに自動で展開したい(=subschemaとして指定)、かつ、ユーザー側で複数ドキュメントを追加・削除したい(="jesgo:unique=false")というケースはあるでしょうか？

**Comment by piyotaicho** [comment]
動作としてはそれでよいとします。もともとデータベースでunionして保持するアイディアは単に時間短縮ですから。
ただし、subschemaについてはユーザによる継承スキーマでの置換は許可です。

卵巣がんについては、stagingはsubschemaです。原則的な動作として：
- subschemaについては親が必ず指定する
- child_schemaは親が指定もすることができるし、子が指定することもできる
です。

晒したものへのレスポンスが帰ってきており、若手が設計したものにかなり修正がかかり、subshcemaがarrayになる可能性は否定できなくなりました。
原則 array > item: object と考えておいた方がよいかと思います。

**Comment by saso-hokuto** [comment]
1.について、回答ありがとうございます。承知しました。
一つのスキーマがsubschemaとchild_schemaが両方に含まれるケースはないものとして扱います。

> 晒したものへのレスポンスが帰ってきており、若手が設計したものにかなり修正がかかり、subshcemaがarrayになる可能性は否定できなくなりました。
原則 array > item: object と考えておいた方がよいかと思います。

こちらですが、実施手術（/schema/treatment/operation_procedures）のように、スキーマのルートで"type":"array"を指定するスキーマが増える、ということでしょうか？
また、

> 2. subschmaでuniqueではないケース

であげた、subschemaで複数ドキュメントを追加したいケースは、unique=falseにするのではなく、array > item: object  で書き換えることで実現する、というイメージでしょうか。

**Comment by saso-hokuto** [comment]
ありがとうございます。
unique=falseのsubschema/childschemaが増えるとのこと、理解しました。
subschemaで複数ドキュメントを持てるようにする場合、
subschemaは並べ替え不可、ドキュメントの追加・削除不可としているため、その部分について考慮が必要になります。
整理・検討して、改めてご提案させてください。

**Comment by saso-hokuto** [comment]
subschema で jesgo:unique=false の場合は以下のようにいたします。  
運用上問題のある点などありましたら、ご指摘いただけますと幸いです。

## subschemaかつjesgo:unique=falseの仕様
- jesgo:unique=falseのスキーマに限り、追加を可能とする。
- スキーマの並べ替えは不可とする。
- 追加したスキーマは、最初に展開された同スキーマの右（もしくは下）に追加される
- 削除も可能。同スキーマで最後の1つのみ削除不可とする。
	- 複数同スキーマのドキュメントがあればどれでも削除可。
    - 初期表示時に展開されたものか、後から追加されたかは区別しない

**Comment by saso-hokuto** [comment]
5/26の打ち合わせで上記仕様を確認いただいた。OKとのことなのでクローズします。
