### ISSUE TITLE
必要な画像類

### ISSUE THREAD

**Issue by kosaka-hokuto** [jesgo-toitu/jesgo-frontend#6]
## 概要
要求仕様 8.1.ログイン画面の背景、要求仕様 8.2.リスト画面のヘッダに使用するロゴ画像が必要。できれば透過してあるものが好ましい。
リスト画面に使用する一部のアイコン(設定、検索、詳細表示設定、編集?)に使用するものはbootstrap3のデフォルトアイコンを使用しているが、アイコンを別途頂ければ差し替えも可能。
ステータスアイコンに関しては[issue#5](https://github.com/jesgo-toitu/jesgo-frontend/issues/5)を参照。

**Comment by piyotaicho** [comment]
取り急ぎ透過PNGのロゴをassets/logo/にpushしました。

**Comment by piyotaicho** [comment]
アイコンはbootstrap標準装備のものでよく見かけますので構わないと思います。

**Comment by piyotaicho** [comment]
若手からリスト画面のアイコンの意見を貰いました、が、いくつか疑義があるので確認します。
また、アイコンが表示されるトリガについても検証が必要となりましたので、話し合って仕様に記載します。
