### ISSUE TITLE
システム設定

### ISSUE THREAD

**Issue by yoshiaki-hokuto** [jesgo-toitu/jesgo-frontend#60]
### データベース
- jesgo_system_setting
	- setting_id : Data Type integer Identity
    - value : Data Type jsonb not null
- 初回導入時はスクリプトでデフォルト設定値のJSONをINSERTする

### 設定値
- 患者IDの桁を揃える
	- true/false(デフォルトtrue)
    - trueの場合は設定された桁数で左0埋めが適用される
    - ハイフン又はアルファベットを許容する設定の場合は、falseのみとなる
- 患者ID(jesgo_case.his_id)の桁数
	- 6~12桁の数字で設定する(デフォルト値は8とする)
	- 症例入力で保存するときに設定値の桁にそろえて保存する(左0埋め)
- ハイフンを許容する
	- true/false(デフォルトはfalse)
- アルファベットを許容する
	- true/false(デフォルトはfalse)
- 施設名称
	- 50文字以内とする(デフォルトは空文字)
    - 画面上、表示することはないがプラグインなどのCSV出力で使うことを想定したもの

### 設定画面
- ヘッダの設定メニューから遷移できる
- 権限はシステム管理者、システムオペレーターのみとする。それ以外は画面を開くことはできない
- 各項目の編集画面として、保存とリスト画面へ戻るボタンを配置する
- 患者ID桁揃えの設定との矛盾をチェックし保存時にエラーメッセージを表示すること
- 患者IDの桁数の範囲をチェックし範囲外はエラーメッセージを表示すること
- 保存はupdateのみで世代管理は不要と思われる

### JSONフォーマット
```JSON
{
  "setting": {
    "hisid" : {
      "alignment": true,
      "digit": 8,
      "hyphen_enable" : false,
      "alphabet_enable" : false
    },
    "FacilityInformation"{
      "name" : ""
    }
  }
}
```

**Comment by piyotaicho** [comment]
施設関連でいうと以下の項目が登録出来るとあとで助かるかと思います。
- 日産婦腫瘍登録施設番号   
フォーマットは失念しました申し訳ない
- 日本産科婦人科内視鏡学会施設番号   
/^(0[1-9]|[2-3]\d|4[0-7])\d{3}$/

あと、施設名称については全角スペースを半角スペースにするなど正規化をしておいた方がこちらもあとで助かるかと思います。

患者IDの入力ルールについては若手に確認してみますが、ハイフンはデフォルトで許可しておいた方がよいかと思います。
