### ISSUE TITLE
【テスト】ドキュメントの移動などの後のタブ選択

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#61]
- タブのドキュメントの表示順を移動すると、「選択されていたタイトルのタブ」では無く、「選択されていたインデックスのタブ」になる
- ドキュメントの削除をするとタブが無選択の状態になる

**Comment by piyotaicho** [comment]
- ドキュメントの削除について一言確認して欲しい

**Comment by hsc-morita** [comment]
ご指摘ありがとうございます。以下のように修正いたします。
- ドキュメント削除前に「[スキーマ名]を削除します。よろしいですか？」と確認ダイアログを表示する
- ドキュメント削除後は削除したドキュメントの右のドキュメントを選択する  
　※削除したドキュメントが右端の場合は左のドキュメントを選択

```タブのドキュメントの表示順を移動すると、「選択されていたタイトルのタブ」では無く、「選択されていたインデックスのタブ」になる```  
→　こちらについてはタブ選択周りは色々修正中のため最新版公開後改めてご確認ください
