### ISSUE TITLE
【テスト】未来の日付の入力に関して

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#62]
- 未来日の入力は禁止もしくはアラートあるとよい

アラートを出して確認したほうがよいと思います。

**Comment by saso-hokuto** [comment]
承知しました。
保存時に、未来日入力されていた場合はエラーとします。
エラーの出し方は他のvalidationと同様、エラーメッセージと対象フィールドの色変更で行います。

**Comment by saso-hokuto** [comment]
5/26の打ち合わせで確認いただいた。上記仕様で実装します。
