### ISSUE TITLE
【テスト】保存タイミング

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#63]
- タブの移動での保存確認
- あらたなタブを開くときに保存確認

が欲しいとの（もともとそういうトリガーにしましょうとはしていましたが）意見がやはりありました。
保存ボタンが機能しているので実装した方がよさそうです。

**Comment by hsc-morita** [comment]
タブ移動での保存については以下のようにいたします。   
問題ございましたらご指摘いただきたく存じます。

### タブ移動等での保存仕様
- 保存トリガーは以下
	- ルートドキュメントのタブ選択
	- 子ドキュメントのタブ選択
	- ドキュメント追加、継承スキーマへの切り替え後

- 以下の操作は対象外
	- ドキュメント並び替え後
	- ドキュメント削除後

- ドキュメント追加時、継承スキーマへの切り替え時は追加(継承)後の状態に対して保存実施

#### 保存確認ダイアログについて
- 保存前に「保存します。よろしいですか？」(はい/いいえ)の確認ダイアログを表示する。
- ダイアログ中の「以降、この症例の編集中の保存については確認しない」のチェックを付けると症例登録画面を抜けるまでダイアログを表示しない
- 確認ダイアログで選択するボタンの挙動は以下
	- 「はい」：保存してタブ移動
	- 「いいえ」：保存せずにタブ移動

- 「確認しない」にチェックを入れた後の挙動はダイアログで選択したボタンの挙動に準ずる  
※いいえを選択していた場合は保存せずにタブ移動

**Comment by piyotaicho** [comment]
閲覧時に毎回確認が出るので編集されていなければ確認しない。
