### ISSUE TITLE
症例入力のvalidationについて

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#65]
## 概要
症例入力画面のドキュメントのvalidationについて、仕様書では以下のように定義されています。

```
5.1. ドキュメントのvalidation
入力に際しては、ドキュメント保存にあたって項目の値が required か否か、日付・文字列などのフォーマットが妥当かの最低限の内容のvalidationが行われる。内容の妥当性については求めない。
jesgo:requiredでの登録に関する必須項目指定があっても、フィールドの強調表示に留め確認の上で保存不可などの対応は行わない。
```
```
5.4.4. 入力フォーム(入力ボックス)の展開
ドキュメントとして成立するために必要な項目(required)については、入力ボックスを強調表示する。
入力内容のvaridationでエラーとなる値については、入力ボックスと内容の両者を強調表示する。
```
タブ移動でもデータ保存をする仕様になったため、
まだ表示したことのないタブについてもrequiredのvalidationエラーが出る場合があります。
その場合、入力フォームを強調表示するだけでは、すぐにはエラー箇所が見つけられない可能性があります。
（ちなみにrequiredの場合、未入力の項目がエラーとなるので、内容の強調表示は反映されず、エラー発生前と同様入力ボックスのみの強調表示となります）

追加の仕様として、validationのエラー箇所が一目でわかるよう、ヘッダとルートタブの間にまとめてエラーメッセージの一覧を出すようにします。
認識に相違あれば、ご指摘いただけますと幸いです。

**Comment by piyotaicho** [comment]
エラーメッセージについてはそれが良いと思います。  
   
一方で、どうしても入力する必要がないから空白になるsubschemaが存在します。これらについては、childschemaと同じく削除可能にしても良いとは思います。実際、入力から閲覧になったときに入力されていないタブが邪魔と言う意見は聞きました。
新規にドキュメントを作成しているときの展開と、編集の際で展開の挙動を分けるのは困難でしょうか？   
（申し訳ないロジックソースまで追いかけている余裕がありません）

**Comment by saso-hokuto** [comment]
エラーメッセージについて、ご確認ありがとうございます。
この仕様で進めます。

ドキュメントの削除可否は、新規作成か編集かに限らず、そのスキーマがsubschemaかchildschemaかどうかで判断しています。そのため、subschemaをドキュメントによっては削除可能にする、というのは、新たに仕様の検討が必要になります。
入力する必要のないドキュメントは、subschemaではなくchildschemaとして定義していただく、ということは難しいでしょうか。

**Comment by piyotaicho** [comment]
subschemaはやはりないと困るので、そうなると非表示化は困難ですね。
ドキュメントの入力のあるタブと、入力のないタブをタブかフォントの濃淡もしくはフォントのウエイトで描き分けるのはどうでしょうか。それならまだわかりやすいと思いますが。

**Comment by saso-hokuto** [comment]
承知しました。
サブスキーマで、ドキュメントの入力があるタブとないタブを見た目でわかるようにします。
以下の仕様で考えています。

- subschemaのみに対応
- 自分のドキュメントと子スキーマ以下（子、孫、ひ孫・・・）のすべてのドキュメントに入力がない場合のみ、「入力がない」と判断。一つでも入力があれば「入力あり」。
- デフォルト値がある項目のドキュメントは常に「入力あり」になる

**Comment by piyotaicho** [comment]
タブの見た目についての決め毎：2022/5/6
- タブのフォントで表示する
  - 他部の内部のドキュメント単位で設定（childについては言及しない）
  - 値がある～デフォルト値含む　：　黒
  - ねがない　：　白
  - プロパティが存在しないドキュメント　：　黒

**Comment by saso-hokuto** [comment]
追記ありがとうございます。以下追記します。
- 全てのタブに対応
- デフォルト値がある項目のドキュメントは常に「入力あり」扱いになる
