### ISSUE TITLE
継承スキーマとjesgo:uniqueの仕様について

### ISSUE THREAD

**Issue by yoshiaki-hokuto** [jesgo-toitu/jesgo-frontend#66]
継承スキーマとjesgo:uniqueの仕様について確認させてください。
継承状態に関わらず、jesgo:uniqueはスキーマ単位で持っているため、
子スキーマに定義のない継承スキーマでは、表示ができないケースがあり得ます。
認識があっているか確認させて下さい。

例：
```
※★は親スキーマAのchild_schema

基底スキーマa（jesgo:unique=true）★
└ 継承スキーマa-1（jesgo:unique=true）★
└ 継承スキーマa-2（jesgo:unique=false）★
└ 継承スキーマa-3（jesgo:unique=true）
```

このようなスキーマがあった場合、具体的に以下の動きを想定しています。

1. 基底スキーマa(unique=true)を追加した
    - 基底スキーマaは再追加できない。
    - 継承スキーマa-1、継承スキーマa-2は追加可。ただし、追加後に基底スキーマaには切り替えできない。
    - 基底スキーマaが再追加できないため、継承スキーマa-3は新たに追加できない。
 
2. 基底スキーマaを追加後、継承スキーマa-1(unique=true)に切り替えた
    - 基底スキーマaは追加できる。ただし、追加後に継承スキーマa-1には切り替えできない。継承スキーマa-2,継承スキーマa-3への切り替えは可。
    - 継承スキーマa-1は追加できない。継承スキーマa-2は追加可。

3. 基底スキーマaを追加後、継承スキーマa-2(unique=false)に切り替えた
    - 基底スキーマa,継承スキーマa-1,継承スキーマa-2 は全て追加できる。
    - 基底スキーマa,継承スキーマa-1,継承スキーマa-2,継承スキーマa-3 は全て切り替えできる。

**Comment by piyotaicho** [comment]
ドキュメントの構造を継承した側が変更してしまうのは望ましくないですね。
継承スキーマでは jesgo:unique についての変更は禁止しましょう。

なので、スキーマ管理でエラーを通知する仕掛けを用意した方が良いかと思います。
この点について別件となりますが、システムとしてのエラー表示などどうしましょう？

**Comment by saso-hokuto** [comment]
回答ありがとうございます。承知しました。
継承スキーマの jesgo:unique が、基底スキーマと異なる場合、スキーマ取り込み時にエラーとします。
システムのエラー表示については別途課題を作成します。

**Comment by saso-hokuto** [comment]
重ねての確認になり恐縮ですが、基底スキーマと継承スキーマの jesgo:uniqueをそろえた場合でも、
uniqueの状態は各スキーマに依存する（継承関係のスキーマ同士でuniqueを共有しない）、という認識でよいでしょうか？

```
※★は親スキーマAのchild_schema

基底スキーマa（jesgo:unique=true）★
└ 継承スキーマa-1（jesgo:unique=true）★
└ 継承スキーマa-2（jesgo:unique=true）★
```

1. 基底スキーマa(unique=true)を追加した
    - 基底スキーマaは再追加できない。
    - 継承スキーマa-1、継承スキーマa-2は追加可。ただし、追加後に基底スキーマaには切り替えできない。
 
2. 基底スキーマaを追加後、継承スキーマa-1(unique=true)に切り替えた
    - 基底スキーマaは追加できる。ただし、追加後に継承スキーマa-1には切り替えできない。継承スキーマa-2への切り替えは可。
    - 継承スキーマa-1は追加できない。継承スキーマa-2は追加可。

**Comment by piyotaicho** [comment]
unique: true
については、ユニークドキュメントの性質を考慮すると継承スキーマまで拡張したほうが目的としてよいと考えます。
また、その方が継承スキーマでuniqueプロパティを変更できない意味がはっきりするでしょう。

なので、上記の例ではa, a-1, a-2いずれかのドキュメントのみ存在可能となります。

**Comment by saso-hokuto** [comment]
回答ありがとうございます。
uniqueは継承関係のスキーマ間で共有するものとします。
