### ISSUE TITLE
患者リスト仕様

### ISSUE THREAD

**Issue by yoshiaki-hokuto** [jesgo-toitu/jesgo-frontend#67]
## 表示項目
- 患者ID
	- 入力値をそのまま表示
- 患者名
	- 入力値をそのまま表示
- 年齢
	- 現在日から算出
- 初回治療開始日
	- 各がん種に対応するドキュメントの診断日の中で最も早いものを表示(```/schema/EM/root```,```/schema/CC/root```,```/schema/OV/root```)
- 最終更新日
	- 症例テーブルのlast_updatedを表示
- 診断
	- 登録しているがん種をすべて表示(```/schema/EM/root```,```/schema/CC/root```,```/schema/OV/root```)
    - 治療開始日の有無も表示条件に含めるか？
- 進行期
	- 癌種ごとにFIGO分類を表示する
- ステータス
	- 手術療法
		- 手術療法ドキュメント(```/schema/treatment/operation```)に診断日の記載がある場合表示
	- 化学療法
		- 化学療法ドキュメント(```/schema/treatment/chemotherapy```)に投与開始日の記載がある場合表示
	- 放射線療法
		- 放射線療法ドキュメント(```/schema/treatment/radiotherapy```)に治療開始日の記載がある場合表示
	- 合併症
    	- 手術合併症ドキュメント(```/schema/treatment/operation_adverse_events```)が登録されている場合に表示
	- 再発
    	- 再発ドキュメント(```/schema/recurrence```)が登録されている場合に表示
        - 確認日の入力がある場合
	- 経過
    	- 経過ドキュメント(```/schema/surveillance```)が登録されている場合に表示
        - 確認日の入力がある場合
	- 死亡
    	- 症例テーブルのdate_of_deathがnullでない場合に表示
	- 未
    	- ★未実装(3年予後、5年予後に関するステータス？)
	- 済
    	- ★未実装(3年予後、5年予後に関するステータス？)

**Comment by yoshiaki-hokuto** [comment]
表示項目とその条件についてご確認をお願いいたします。不足している仕様について加筆していただけますと助かります。

複数の癌種を持つケースにおいてステータスは最初に診断した癌種のみで良いのか、全ての癌種のステータスを表示するのか決めたいと思います（手術療法、化学療法、放射線療法、合併症）

リスト画面にCSV出力機能を設け、リスト表示しているものをCSV形式ファイルで出力します。
複数の癌種を持つ場合を考慮して、癌種毎に診断、進行期などはカラムを設けます。

**Comment by kosaka-hokuto** [comment]
上記に関していくつかご確認させてください。

- 共通
  > 診断・進行期
  ここでいう各がん種に対応するドキュメントには「患者台帳(/schema/other/root)」は含まない認識でよろしいでしょうか。

- 患者リスト表示
  > 初回治療開始日 についてはドキュメントから検索して最もはやいものを採用で結構です。要望があり、jesgo:get の項目としてひけるようにする必要がありそうです。
  ```
  ここでいうドキュメントスレッドで記載した各がん種に対応するドキュメントという認識で良いでしょうか、それともすべてのドキュメントから「初回治療開始日」という項目を探す認識でしょうか。
  がん種のドキュメントに限る場合は「患者台帳(/schema/other/root)」も含む認識でしょうか。
  jesgo:getに関しては細かい実装方法が決まっておりませんが症例情報にデータを持って対応する予定です。
  ```
  
  
- 腫瘍登録管理画面
  > 診断 入力が無ければ「未」を表示
  > 進行期 入力が無ければ「未」を表示
  ```
  同様の表示が患者リストにもありますが、患者リストには「未」の表示は必要ない認識でよろしいでしょうか。
  ```
  
  
  > 登録 腫瘍登録番号が入力された時点で済、それ以前は未、対象外症例は表示無し
  ```
  各種「患者台帳 ○○がん」の腫瘍登録番号でよろしいでしょうか。
  また、がん種を特定しない「患者台帳(/schema/other/root)」の腫瘍登録番号も含む認識でよろしいでしょうか。
  ```
  
  
  > 3年予後 初回治療開始日から3年（区切り方は確認中）で済・未が表示、それ以前は表示無し。登録日については台帳に用意しようと思います。
  > 5年予後 初回治療開始日から5年（区切り方は確認中）で済・未が表示、それ以前は表示無し。登録日については台帳に用意しようと思います。
  ```
  ここでいう台帳は「患者台帳 ○○がん」などのroot.json類のスキーマに項目を追加する認識で相違ないでしょうか。
  ```

**Comment by kosaka-hokuto** [comment]
申し訳ございません、一つ訂正と追加のご質問がございます。

### 訂正
> - ステータス
    - 手術療法
      - 手術療法ドキュメント(/schema/treatment/operation)に診断日の記載がある場合表示

こちら「```診断日```の記載がある場合」と記載しておりますが、「```手術日```の記載がある場合」でした。訂正させてください。

### ご質問

- 患者リスト・ステータスに表示を予定している「緩和療法」とは緩和治療スキーマ(/schema/treatment/supportive_care)のことでよろしいでしょうか。
  こちらであれば条件の指定(評価日が入力されている場合等)と、該当条件時に表示するステータスアイコンを頂きたいです。

- 腫瘍登録管理画面 登録 の「対象外症例」とはどのような条件の症例を指すのでしょうか。
  症例登録時に「登録拒否(decline)」を指定した症例という認識で良いでしょうか。

**Comment by piyotaicho** [comment]
- 診断・進行期における /other/root  
「その他」についての実装は全くないに近いのですが、これも対象となります。
- 治療開始日の一番早いものの検索対象について   
現状の設計では treatment/* のドキュメントにあるevent_dateが対象です。/*/rootの登録日ではありません。が、この点についても要望が挙げられたのでまずはこの方法で実装してください、日付検索は無駄にしません。
- 患者リストの「未」の表示   
無いものは非表示で良いとのことです。が、「-(ハイフン)」ぐらいはあっても良いと思います。
- 腫瘍登録の「済」フラグについて  
先の件と同じく、こちらも/other/rootも対応します
- 3年・5年フラグ   
rootにプロパティを追加します。
- 緩和療法について   
評価日がフラグになります。アイコンについては承知しました。   
この評価日がアイコン表示のフラグになると言うのもスキーマ中に設定できた方が安全ですね。
- 症例と登録管理画面の対象外症例   
*/rootにある、"腫瘍登録対象" == "はい" がフラグです。登録拒否（decline）はそういないと判断していますが、これはこれで管理画面でわかる必要がありますね。腫瘍登録「未・済」の他に「拒否」のアイコンを作成しておきます。

**Comment by kosaka-hokuto** [comment]
ご回答ありがとうございます。
対象外症例について細かくお伺いしたかったので別で課題を立てさせて頂きました。
お手数ですが[#72](https://github.com/jesgo-toitu/jesgo-frontend/issues/72)もご確認よろしくお願い致します。
