### ISSUE TITLE
継承スキーマに設定されるsubschema/childschemaについて

### ISSUE THREAD

**Issue by kosaka-hokuto** [jesgo-toitu/jesgo-frontend#68]
## 概要
スキーマ管理画面において、基底スキーマと継承スキーマはsubschemaであっても表示/非表示の切替、継承グループ間で並び替えが出来るとのことですが、
その場合subschema上で継承グループなのか、childschemaなのかというのが分かり辛く、また並び替えの際も継承グループを超えての並び替えが出来る用に見えてしまう懸念があります。
現在頂いているスキーマでは基底スキーマ、継承スキーマの関係にあるスキーマに関してはそれぞれ同じsubschema、childschemaが設定されております。
上記制約が常に守られる場合であればスキーマ管理画面で継承関係毎の表示がわかりやすくできるのですが、これは今後の継承関係のスキーマにもすべて当てはまる事象でしょうか。
その場合、各継承グループ毎の下に表示されるchildschema、継承グループであるsubschemaの表示順、表示/非表示状態は共通表示されます(下記例参照)。

![image](https://user-images.githubusercontent.com/98303234/168246533-29968526-cd0f-4051-99a9-37ae82821819.png)

上記の例の場合、A～A''の間は並び替えが可能、B～B''、CとC'はそれぞれ並び替え可能で左記の範囲を超える並び替えは出来ない認識です。
しかし、表示としては同じインデントにあるため、グループAにサブスキーマ、子スキーマがない場合、なぜA''とBが入れ替え出来ないのかがわかりにくい表示になってしまう可能性があります。
本来はスキーマ毎に入る区切り線を継承グループ単位では間にいれないことでそれらが一つの継承グループであることがわかりやすく表示できると思います。

これらの形式で実装することで運用上問題ありそうでしょうか。

**Comment by piyotaicho** [comment]
このあたりかなりややこしいのは事実です。  

継承スキーマは原則的にカスタマイズの手段としてのアイディアです。
現在 /schema/summary と /schema/summary/detailed、/schema/treatment/operation と /schema/treatment/operation/detailed をデモ的に用意して居ますが、最初の配布に含めるのは不適当と判断しましたのでここは作成し直しています。

その際、カスタマイズされた継承スキーマが独自に subschema, childschema を持つことは許容されるべきと考えています。

スキーマ管理画面は、あくまでスキーマ管理をするものですので、再生成されたツリー構造のドキュメント構造を示さなくてもよいとはおもいます。（もちろん、スキーマを作成している自分ですら時々見失いますので、広大になりますがドキュメント構造をツリー構造で表示できる仕掛けはあってもよいとおもいます）
正直、全部jsonでガチガチに作ってしまえれば

その辺を考慮して、文書構造と、スキーマそれぞれの管理を行うデザインのポンチ絵をつくってみました。
文書構造は閲覧とスキーマの選択のみ、スキーマ自体の構造規定因子はマニュアルで行えるようにするしかけです。欠点は、ワイルドカードを超える指定はできないことでしょうか。
![image](https://user-images.githubusercontent.com/57445173/169331365-fd47c512-4520-4d3e-a291-74b2a20bec6d.png)

**Comment by kosaka-hokuto** [comment]
デザインのご提案ありがとうございます。
頂いたデザインに関していくつかご確認したいことがあります。

### 文書構造ビュー
- 項目の一番上にルートを記載させてください
  - 上記を挟むことにより、ルートから見た下位スキーマとしてルートスキーマの表示、非表示、並び替えが可能になります。
  
- 各項目の先頭についている記号の色の違いは何を意味しているのでしょうか。
  - こちらの解釈としては以下の認識ですが相違ないでしょうか。
    - ```▷``` 下位スキーマが登録されていないスキーマ、インデントのために表示され押下しても変化しない
    - ```▽``` 下位スキーマを展開中のスキーマ、押下で```▶```に変更され、下位スキーマを格納する
    - ```▶``` 下位スキーマが展開できるスキーマ、押下で```▽```に変更され、下位スキーマが展開される
    
- 並び替えに関してはスキーマ設定ビューから行えるため、ツリー上では実装しません

### スキーマ設定ビュー  
- スキーマ設定での各項目は以下の機能の認識です。間違っている部分等ありましたらご指摘ください。
  
|項目|編集可否|内容|
|----|--------|----|
|文書(スキーマタイトル)|×|スキーマ名を表示。プルダウンで編集対象のスキーマを切り替え可能
|スキーマID|×|スキーマの$IDを表示|
|継承スキーマ|×|継承スキーマか否かを表示|
|有効期限|×|スキーマの有効期限を表示|
|上位スキーマ|×|親スキーマ(1世代分)を表示|
|下位スキーマ|△|サブスキーマ(1世代分)、子スキーマ(1世代分)を表示。表示、非表示、並び替えは子スキーマに対してのみ設定可能<br>サブスキーマで継承関係にあるものに関してはその中でのみ表示、非表示、並び替えの設定が可能|

**Comment by piyotaicho** [comment]
なんか夜中にやるといろいろ抜けていますね申し訳ない。このスキーマ設定ビューでは、スキーマが本来持っている設計情報をオーバーライドすることも許容しています。データベース親子情報を保持するように設計されているのはそのためです。ただ、スキーマが本来もつ親子情報を破棄する形で変更する場合はconfirmが出た方が良いとは思います。

- ルートの表示

必要だと思います。トップの順番を設定するためにも必要ですね。

先頭の記号は
- 右向き 下位を展開して表示していない、下向き 下位を展開して表示している～所謂tree viewの展開・非展開です
- 白三角：childschema 任意追加可能ドキュメント
- 黒三角：subschema 必ず追加されるドキュメント

です。

スキーマ設定ビューについては大旨その理解で結構です。上位下位スキーマボックスにある桁に名前のついていないチェックボックスは表示・非表示の設定です。ただし、上位下位スキーマいずれも編集可能とします。
- 上位スキーマ表示で、この例のようにdisableされているものは上位スキーマから subschema として指定されていることを示します
- 上位スキーマ表示で、編集可能チェックボックスとなるものは以下の条件になります
  - スキーマの親設定で上位スキーマとして設定されているもの（チェック解除時にconfirmあり）
  - 上位スキーマから childschema と指定されているもの
- 下位スキーマ表示で必ず展開 にチェックされているものは subschema 扱いとなります。
  - subschemaは必ず表示設定がされます（チェック＋disabledでもよかったかもしれませんね）
  - スキーマ設計で subschema として設定されているものを解除する場合にはconfirmが表示されます

**Comment by piyotaicho** [comment]
今更ながらですが、上位、下位スキーマに手入力で追加が可能だと（開発に関しても）利便性が上がりますね。
当面、ここから json や zip をアップロードできると更によいかとおもいます。
