### ISSUE TITLE
スキーマに設定されている有効期限について

### ISSUE THREAD

**Issue by kosaka-hokuto** [jesgo-toitu/jesgo-frontend#69]
## 概要
スキーマに設定されている有効期限(valid_date)に関してですがこちらは有効期限同士の重複がないように設定する認識です。
本来必須のパラメータとなっておりすが現状設定されていないスキーマが殆どということもあり、こちらで以下の様に実装しようと思います。

- 有効期限が設定されていないスキーマを登録した場合、そのスキーマの有効期限は開始日が登録日、終了日が無しとして扱われる
- 既に登録されているスキーマと同じ$IDを持っているスキーマを登録する場合、前者の有効期限終了日が後者の有効期限開始日以上になっていないか(有効期限が重複していないか)を確認する
  - 有効期限が重複している場合、前者の有効期限終了日が未設定の場合は後者の有効期限開始日の前日に更新する
    ```
    例)
    $ID:fooのスキーマ1が有効期限2021年4月1日から2022年3月31日で登録されている時に、
    $ID:fooのスキーマ2を有効期限2022年3月15日から2023年3月31日で新規登録すると、
    スキーマ1の有効期限は2021年4月1日から2022年3月14日に設定される。
    
    $ID:barのスキーマ3が有効期限2021年4月1日から終了日未定で登録されている時に、
    $ID:barのスキーマ4を有効期限2022年3月15日から2023年3月31日で新規登録すると、
    スキーマ3の有効期限は2021年4月1日から2022年3月14日に設定される。
    ```

上記仕様で実装したときに運用上問題ありそうでしょうか。

**Comment by piyotaicho** [comment]
未設定についてはすっかり忘れていたので、そのような形で結構です。
開始日だけ最低限指定されていれば有効なスキーマは検索できるので終了日はNOT NULLにしていませんでした。実装上都合の良い方法を選んでいただいて結構です。
