### ISSUE TITLE
リスト画面、症例情報登録時での年齢の算出基準日

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#7]
## 概要
ドキュメント単位で使用する年齢はevent_dateを基準日として算出しますが、リスト画面や症例を新規登録する際の患者情報（症例テーブルのデータ）では基準日が決まっていない。
何を基準日とするか検討が必要。
例
 - 現在日時
 - 対象の症例レコードに紐づくドキュメントがあれば、それらのevent_dateの最新　など

**Comment by piyotaicho** [comment]
リスト画面・症例編集画面の患者年齢は原則現在日時でよいと思います。一方、死亡症例については死亡のところでの年齢にするのがよいかと思います。いちいち状態で変更する必要は無いでしょう。  
一方、日付設定のあるドキュメントの日付入力ボックスにフォーカスしたら hover で入力日付での年齢が表示されるとちょっと嬉しいかもしれません。  
（年齢を取得するフィールドは "jesgo:get": "age" を使うので対応できるとおもいますし、プラグインからは計算できるようにしておけば良いと思います。）

スキーマのところで "jesgo:set": "death" をデータベースに保持するかを検討しましょうとしましたが、データベースの患者テーブルに 死亡日 を保持するようにしますか？

**Comment by saso-hokuto** [comment]
確認ありがとうございます。
ご提案の通り、患者テーブルに死亡日を持つのが楽かと思います。そのように修正します。
リスト画面・症例編集画面の患者年齢は、死亡日があれば死亡日を、なければ現在日時を基準日として算出します。
ただ、hoverでの年齢表示につきましては、まずは既存の仕様の実装を優先したいため、β版以降の課題とさせてください。
