### ISSUE TITLE
症例における登録拒否と、患者台帳の腫瘍登録対象症例について

### ISSUE THREAD

**Issue by kosaka-hokuto** [jesgo-toitu/jesgo-frontend#72]
## 概要

症例における登録拒否(患者登録時のチェックボックス)と、腫瘍登録対象症例(患者台帳の婦人科腫瘍登録対象症例)についてご確認させてください。

- こちら2つに関しては同期の必要がない(片方をチェックしたら強制チェック等)はなく、全く別のものという認識でよろしいでしょうか
- 以下それぞれの項目における機能を記載しました。他に影響する部分等あれば教えてください

  - 症例における登録拒否
    - 患者登録時「登録拒否」にチェックを入れると拒否状態になる認識です
    - リスト画面、腫瘍登録管理画面の検索項目にある「腫瘍登録対象のみ表示」にチェックを入れた場合、登録拒否されている症例が表示されなくなる
    - 拒否状態であれば腫瘍登録管理画面における「登録」項目に最優先で「拒否」を表示
    
  - 患者台帳の腫瘍登録対象症例
    - 患者台帳 ○○がん 内の婦人科腫瘍登録対象症例に含まれる値
    - 腫瘍登録管理画面における「登録」項目に表示するアイコンの条件に使用
      - 登録対象症例の値が 未入力/いいえ であれば「未」を表示
      - 登録対象症例の値が はい であり、腫瘍登録番号が登録されていなければ「未」を表示
      - 登録対象症例の値が はい であり、腫瘍登録番号が登録されていれば「済」を表示
    
- また、腫瘍登録対象症例において複数の患者台帳で異なる値が設定されている場合はどのように処理すべきでしょうか
  - こちらの解釈としては「拒否」＞「未」＞「済」の優先でアイコンを表示する認識です

**Comment by piyotaicho** [comment]
登録拒否は非常に重たいもので、そもそも簡単にチェックできないようにはしないところではあります。
現状の実装では、対外的な登録に関して一切拒否をした症例と考えていただいて結構です。ただ、このチェックがなされるタイミングが、登録を行った後でおこる可能性もあります。
なので
- リスト画面、腫瘍登録管理画面の検索項目にある「腫瘍登録対象のみ表示」にチェックを入れた場合、登録拒否されている症例が表示されなくなる

は、では一応「腫瘍登録対象」自体は生きているのでそのまま表示されていたほうがよいとおもいます。
一方で、
- 拒否状態であれば腫瘍登録管理画面における「登録」項目に最優先で「拒否」を表示

は、大変有難いです。「拒否」というアイコンも用意します。
腫瘍登録管理画面での登録の項の扱いですが
- 登録対象症例の値が 未入力/いいえ であれば「未」を表示

は不要で、登録対象症例が「はい」ではじめて「未」を表示していただければとおもいます。ロジックもそのほうが簡単でしょう。

複数の患者台帳　○○ がある場合ですが、いろいろ考えていますので別に回答します。

**Comment by kosaka-hokuto** [comment]
ご回答ありがとうございます。

上記を踏まえまして改めて以下の点をご確認させてください。

> 「腫瘍登録対象」自体は生きているのでそのまま表示されていたほうがよい

- こちらですが、その場合検索にある「腫瘍登録対象のみ表示」の項目で表示されるのは「登録対象症例の値が はい」であるドキュメントを持つ症例という認識でしょうか
  
> 登録対象症例の値が 未入力/いいえ であれば「未」を表示は不要で、登録対象症例が「はい」ではじめて「未」を表示していただければとおもいます。

- こちらは上記の「登録対象症例の値が 未入力/いいえ」の条件の場合、何も表示しないという認識でしょうか
  - 未入力の場合、確認漏れがある恐れがありますが問題ないでしょうか

**Comment by kosaka-hokuto** [comment]
上記で実装を行いましたのでこちらはクローズします。
