### ISSUE TITLE
【テスト】患者ID番号桁数

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#73]
桁数設定をしても怒られる。
![image](https://user-images.githubusercontent.com/57445173/171106052-83d9f02e-0875-41b4-896f-b273dd39677e.png)
![image](https://user-images.githubusercontent.com/57445173/171106094-25ef7ded-01ef-4333-8dd6-6bf4d8f452fd.png)

**Comment by piyotaicho** [comment]
数を数えていなかった。。。気にしないでください。

**Comment by piyotaicho** [comment]
と思ったら、ハイフンも一文字として数えていましたね。このあたりの仕様はどうしましょう？

**Comment by yoshiaki-hokuto** [comment]
患者桁数設定はハイフンを許容しない基幹電子カルテに依存した考え方で定義していました。
桁数を制限するシステム上の理由は、電子カルテ等のシステムから起動するときの整合のためです。
ハイフンと英字を許容する場合、桁数制限のチェックは無効にして、システム上のガードとして内部で20桁の上限を設けようと思いますがいかがでしょうか？

**Comment by piyotaicho** [comment]
そうですね。
- 桁数指定　もしくは　ハイフン許容で20文字まで
- 桁数指定の場合は右詰めで0埋めの要否を確認
という形ではいかがでしょうか？

それとも、IDのフォーマットとして 00-0000-00 000-000-0 とかで指定するようにしますか？

**Comment by yoshiaki-hokuto** [comment]
ご回答いただいた下記仕様で問題ございません。汎用性を持たせた方が多数ある施設のルールで困らないと思いました。
- 桁数指定　もしくは　ハイフン許容で20文字まで
- 桁数指定の場合は右詰めで0埋めの要否を確認
