### ISSUE TITLE
【テスト】日付入力

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#74]
今更ですが、input[type="date"] のアトリビュートにminが設定されていないので、西暦0年とかも入力できます。
先の議論で、未来の日付を入力不可にするということは決まっていましたが、過去の方がよりトラブルを起こしそうです。

現在 input[type="date"] には max="2100-12-31" は入っていますが日付入力の制約を考慮して以下のようにしてしまうのが楽ではないかと。

- min="1900-01-01"
- max="入力している日"

**Comment by hsc-morita** [comment]
承知しました。minとmaxの設定はそのようにいたします。  
ただしキーボードから直接日付を入力した場合に範囲外の日付も入力できてしまうケースがあったため  
保存時のvalidationにてminとmaxの範囲チェックを行うようにいたします。
