### ISSUE TITLE
スキーマの有効期限に関する仕様について

### ISSUE THREAD

**Issue by kosaka-hokuto** [jesgo-toitu/jesgo-frontend#76]
## 概要
スキーマの有効期限を伴う更新について以下の仕様で実装を行う予定です。問題あればお教えください。

- 新規でドキュメントが作成される際、設定されている場合はevent_date、いない場合は当日の日付で有効期限内のスキーマを取得する
    - 入力値からeventdateを設定する場合はスキーマの有効期限外に設定できないようにする

- 既存のドキュメントが開かれるたびに、現在のeventdateを取得し、当てはまるスキーマを探す
    - 当てはまるスキーマがない
        - 過去スキーマを参照(後述)
    - 当てはまるスキーマがあり、かつメジャーバージョンも一緒の場合
        - スキーマ変更されたかの有無に関わらず入力値の修正は不要
        - 項目の減少により、スキーマに無くドキュメントには存在している項目に関してはreadonlyで表示/保存のみ行う
    - 当てはまるスキーマがあり、かつメジャーバージョンが変更されている場合
        - スキーマを最新のもので読込み、入力値の修正を要請する

- 有効期限更新時は過去を含む日付を許容する
    - あるスキーマを削除する代わりに有効期限が過去の日付で更新を行うことにより実質的に削除ができる
    - ただし、入力項目の増減、固定選択肢の増減など、ドキュメントの再編集が必須になる場合は基本的にはメジャーバージョンを上げてもらう
        - メジャーバージョンを上げることでドキュメントを再度開いた際に再入力を促すことができる
    
- 過去スキーマの参照
    - 過去日付で既存のスキーマを更新することにより、既存のドキュメントが有効期限内にスキーマが無くなってしまった場合、そのドキュメントはreadonlyとして扱う。
        - readonlyになっているドキュメントから派生するサブスキーマ、子スキーマ、継承スキーマは同様にreadonlyとし、新規作成、編集、削除は出来ないものとする。

- スキーマの親子関係、継承関係は過去のスキーマを見ている場合でも常に最新の継承関係で処理をする
    - 現在親子関係(特に子スキーマ)は親と子双方からのJSONファイルの記載で関係を決めているが、どの有効期限を使うかはスキーマ毎に違うため、1つ1つ分けて関係を保持するのが難しい
    - 過去スキーマで矛盾が出た場合は既存のドキュメントは削除しないが、現在親子関係、継承関係にないドキュメントは新規で追加できないものとする

**Comment by kosaka-hokuto** [comment]
上記に加えて以下の仕様を追加します。
- スキーマ登録時に過去日付を許容するが、同じ$IDを持つ登録済スキーマの有効期限開始日以前(同日含む)は許容しない
  - 上記を許容すると過去ドキュメントを開いた際にスキーマの整合性が取れない懸念がある

**Comment by kosaka-hokuto** [comment]
ご回答ありがとうございます。
最終的には上記に記載した仕様で進めたいのですがβ版までにお出しするのは作業量的に少し難しいものがあります。
従いまして、β版としては以下の仕様でお出しさせて頂きたいのですが問題ないでしょうか。
重ね重ねのご質問になりまして申し訳ございません。

- ドキュメント作成時、更新時等スキーマを取得する必要がある際はevent_dateを参照せず、本日の日付を使用する
  - 該当の日付が有効期限内に存在しない場合は同じ$IDを持つ一番新しいスキーマを取得する
  
- ドキュメントの保存時に、event_dateが同じ$IDを持つスキーマの有効期限に入っているかをチェックする
  - 最新に限らず、過去の物も許容し、入っていなければエラーとして保存が出来ないようにする
  - この仕様に関しては最終的な仕様と変わらない認識

```
ex.) 
前提条件：$IDが`aaa`のスキーマが有効期限2022/04/01-2022/05/31の物と、2022/07/01-2022/08/31の物が登録されている
2022/06/08に$ID=`aaa`のドキュメントを作成すると、有効期限が2022/06/08の物がないため、最新の2022/07/01-2022/08/31のスキーマが適用される。
保存時にはevent_date属性を持つ日付は2022/04/01-2022/05/31か2022/07/01-2022/08/31のいずれかに属している必要がある
```

**Comment by piyotaicho** [comment]
このあたりは、当面すぐに必要になる実装ではなく、カスタマイズなどが軌道に乗った時点で必要になる機能です。
なのでStep2ではちゃんと実装できているを目標とすれば良いと思います。

当面、期日に対してはそれほど厳密では無く、スキーマの$idのチェックなどは行うこととして、スキーマ管理などから同じ$idのスキーマを登録する場合などに古いものを上手く無効化できるようになっていればよいでしょう。
