### ISSUE TITLE
【テスト】縦に長いドキュメントのスクロール挙動

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#77]
縦に長いドキュメントの高さがビューヘイトのある程度を越えるた状態で、コントロールの操作をすると、フォーカスはそのままで先頭の適当なところにスクロールが戻ってしまう。
（反省してChromeでやっています）

**Comment by hsc-morita** [comment]
ご指摘ありがとうございます。  
スクロール位置が戻ってしまう件については現在修正中です。

**Comment by piyotaicho** [comment]
仕様で決めたことなので入力操作毎にスキーマのvalidationが掛かります。
その都度stateに変更が掛かりDOMが再構成され、再レンダリングされているのが原因ですね。

VueJSなら勝手知ったるFAQなのですが、Reactでここまで追い込んだのは無かったので調べたらこれが常套句のようです。
https://morioh.com/p/70c20548243e
