### ISSUE TITLE
【テスト】"jesgo:ui:liststyle": "combo"や"suggestlist"

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#78]
そういえばどうなっていましたっけ？

**Comment by hsc-morita** [comment]
申し訳ありません。jesgo:ui:liststyleですが現在未対応となっております。  
現在対応済みのものは以下に記載の対応一覧「対応状況」列をご確認ください
https://github.com/jesgo-toitu/jesgo-frontend/blob/development/docs/schemaDefinition/SchemaDefinition.md

**Comment by piyotaicho** [comment]
承知いたしました。これでできるように組みます。
