### ISSUE TITLE
最上位コントロールボタンでの追加ドキュメントの表示順

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#8]
## 概要
最上位のコントロールボタンで追加できるドキュメント（ルートドキュメント）を表示する順番について検討が必要。
また、子ドキュメントの順番はsubschema,child_schemaで定義可能だが、ルートドキュメントにはそれらがないため、どこかに定義を持つ必要がある。

**Comment by piyotaicho** [comment]
確かに仰るとおりです。  
一応、この順序決めもスキーマ管理テーブルで行う考えです。なので、インストールの際にはデフォルト構成のミニマムデータベースを持つ必要があると思います。

**Comment by saso-hokuto** [comment]
確認ありがとうございます。
スキーマ管理テーブルでルートドキュメントの順序も管理するイメージですね。
まだスキーマ管理テーブルについては検討できていないため、設計時にそちらも考慮します。
