### ISSUE TITLE
【テスト】tab なドキュメントの挙動

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#80]
トップレベルは大丈夫だが、ドキュメント中のタブには左右に移動があったりなかったりする。

**Comment by hsc-morita** [comment]
左右に移動(タブの並び替え)ができるドキュメントはchildSchemaのドキュメントに限られますので、subSchemaは並び替え不可となっております。  
もしchildSchemaのドキュメントの並び替えができない、またはsubSchemaのドキュメントが並び替えができてしまっている場合は不具合ですのでご連絡いただきたく存じます。
