### ISSUE TITLE
【テスト】継承・回帰の選択とドキュメントの挙動

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#81]
*** 継承・回帰を選択するとドキュメントがクリアされてしまう。***   
入力の時点で決めておいてくださいね。としたいところですが、各施設で項目をカスタマイズした場合のダメージが大きいですね。
可能な限り流し込んでいただいた方がよいと思いますのでよろしくお願いいたします。

**Comment by hsc-morita** [comment]
対応方法を検討させていただきます。
現状わかっている範囲で以下の問題がございます。

1. 継承元と継承先で同名プロパティかつtypeが異なる、またはtypeがいずれもobjectやarrayでitemsの内容が異なる場合  
そのままデータを引き継ぐと不正な値が表示されてしまう  
→ 上記に関しては継承元と継承先のスキーマのプロパティを比較して、  
引継ぎ可能なスキーマ構成であれば引継ぎ、そうでなければ引き継がないとすることは可能かと存じます。

2. サブスキーマ、子スキーマの扱い  
→ 継承元と継承先でサブスキーマの構成が変わることがあるため、現状すべて再作成しております。  
  継承でサブスキーマ、子スキーマの構成が変わった場合にどうするべきかを検討する必要がございます。  
  例) 同一スキーマに限り値を引き継ぐ、継承したことでサブスキーマでなくなったドキュメントは子スキーマとしてreadOnlyで表示する など


1については継承したドキュメント自身に限り引継ぎを行うことは比較的簡単に実装できそうです。  
2のサブスキーマ、子スキーマに関しては色々と検討事項が多くβ版では制限事項となる可能性がございます。

**Comment by piyotaicho** [comment]
まず、継承の原則として「継承元の拡張である」があります。（ドキュメントに明示はしませんが）
プロパティのtypeが継承元と異なることもありますが、そのような大きな問題を除きデータは継承されたほうがよいと考えます。
リリースにあたっては、運用規定で「継承スキーマでは継承元のプロパティは踏襲する」「同名のプロパティのtypeは継承してください」という但し書きをつけてもよいとおもいます。

いまあるoperationとoperation/detailedのようなものがさすがにアレかとおもいますので、修正します。

**Comment by piyotaicho** [comment]
継承スキーマから元スキーマに戻した場合がちょっとやっかいですが、存在しないプロパティに関してはreadonly/削除可能にしておけばよいのではないかと。

**Comment by hsc-morita** [comment]
ご回答ありがとうございました。  
> いまあるoperationとoperation/detailedのようなものがさすがにアレかとおもいますので、修正します。  

まさにoperationとoraperation/detailedの「術者」のことでした。修正の件承知いたしました。  

ご回答いただいた内容を元にβ版での仕様を検討いたしました。  
この内容ですと来週6/15辺りには実装できる見込みとなります。
お忙しいところ恐れ入りますが、問題がないかご確認いただきたく存じます。

### スキーマ継承時のデータ引継ぎ仕様(β版向け)
- 継承したドキュメントのデータ引継ぎについて
	- 基本的にすべてのプロパティを引き継ぐ
	- 継承・回帰した先のスキーマに存在しないプロパティがあった場合、readOnlyで表示する  
	　※readOnlyの項目は編集不可のため、削除したい場合は一旦元のスキーマに戻してから値をクリアする
	- 継承元と継承先で同名プロパティかつtype不一致の場合、不適切な表示になることがあるが制限事項とする  
	※継承スキーマを作成する場合は原則typeを合わせる運用とする

- 継承したドキュメント配下のサブスキーマ、子スキーマのデータ引継ぎについて
	- 継承先のサブスキーマ、子スキーマに継承元と同一のサブスキーマ、子スキーマが存在すればデータを引き継ぐ
	- 継承先に同一のスキーマがなければデータは引き継がない
	- 継承先と継承元でサブスキーマと子スキーマの定義が逆(格下げ、格上げ)になっている場合でもデータは引き継ぐ
	- 孫ドキュメントも同様の仕様でデータ引継ぎを行う

- β版以降での実装
	- readOnly項目の削除機能
	- サブスキーマ、子スキーマのデータ引継ぎ時、継承先スキーマに存在しないスキーマの表示・削除機能

**Comment by hsc-morita** [comment]
9/16状況
以下未対応
- readOnly項目の削除機能
- サブスキーマ、子スキーマのデータ引継ぎ時、継承先スキーマに存在しないスキーマの表示・削除機能
- type不一致時の対処
