### ISSUE TITLE
【テスト】患者を開いたときの挙動

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#82]
本当に今更なんですが、最後に開いていたドキュメントを記憶してそれを開きたいという希望がありそうな気がしてきました。
（スキーマの作り直しがほぼ形になってきました）
ユーザ個人個人で患者毎に記憶していたら大変なので、システムとして患者毎に記憶するのはいかがでしょうか。

- 準備：jesgo_case に last_viewed_document というカラムを増設   
```
ALTER TABLE jesgo_case ADD COLUMN last_viewed_document integer;
```
- リストに戻る を行ったとき、最後に開いていたトップレベルのドキュメントのdocument_idを保存、ドキュメントが無い時は NULL
- NULLならば現状の挙動と同じ
- ドキュメントを開いたときには、当該document_idを手繰ってフォーカスする

**Comment by hsc-morita** [comment]
返信が遅くなり申し訳ありません。
提示いただいた方法で実装は可能かと存じますが、対応はβ版以降とさせていただきたく存じます。

**Comment by piyotaicho** [comment]
要求が来たら対応しましょう。Step2でも良いと思います。
