### ISSUE TITLE
backend : schemaListUpdate

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#83]
schmeListUpdate はobosolutedですか？
ワイルドカードでのchild指定が効いていない気がします。

```
Error: Client was closed and is not queryable
    at K:\Development\jesgo\jesgo-backend\node_modules\pg\lib\client.js:570:27
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by kosaka-hokuto** [comment]
申し訳ございません、お伝えし忘れておりましたがschmeListUpdateは現在json2schemaと同時に実行されるようになっております。
ワイルドカード指定に関しては仕様の見逃しです、急ぎ対応致します。

**Comment by piyotaicho** [comment]
承知しました。
ワイルドカードと、一括変更はSQLを叩く必要があるので各施設へのβリリース（のあと初回アップデート）までにはスキーマ管理画面へのアップロードは用意できた方がよいかと考えます。

**Comment by kosaka-hokuto** [comment]
ZIP形式でのアップロードに関しては目途が付いておりますので近いうちに反映できると思います。
ワイルドカード指定ですが、以下のような指定方式を想定しております。認識違いなどありましたらご指摘お願いいいたします。

- ワイルドカード指定方法は正規表現を使用せず、```*```で指定
- ```*```の指定についてはパスの```/```区切りを跨がない

```
ex.)
// 指定が"/schema/aaa/*"の場合
// 該当する
   /schema/aaa/bbb
   /schema/aaa/ccc
   
// 該当しない
   /schema/bbb/aaa
   /schema/aaa/bbb/ccc
```
