### ISSUE TITLE
【テスト】複数の台帳が存在するときの病期診断

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#86]
病期診断が二つ目などが入力されていないときは null と出力されてしまいます。
backendのsearchPatientsで3大がん腫ごとに拾っているようですが、null の場合は(未)などをあてるようにしておいたほうが良いと思います。

あと、現時点では3大がん腫しか拾っていませんが、他もスタンバイしているのでスキーマ名称をハードコードしているロジックはリリース後早めにでも見直しておいた方がよいかとおもいます。

**Comment by piyotaicho** [comment]
これも当面すぐに必要になる部分ではないので、step2準備できちんと修正すればよいと思います。
まずはクイックハックで対応でよいかとおもいます。

**Comment by kosaka-hokuto** [comment]
ご指摘ありがとうございます。
現時点ではnullに対して何らかの文字列を当てる対応のみ行います。
β後のどこかのタイミングでより汎用的な修正を行います。

**Comment by piyotaicho** [comment]
これでよいと思います。

**Comment by kosaka-hokuto** [comment]
上記仕様で実装するに従い、以下のタグが付いている値を取得して表示、検索対象にする予定です。
複数表示の並び順は同タグの中では$ID順に整列されます。
タグの形式は "jesgo:tag":"tag_name"を想定しております。

| 名称 | tag_name | 概要 |
| -- | -- | -- |
| 主要がん種 | cancer_major | 診断の項目に表示、前に優先して表示される | 
| その他がん種 | cancer_minor | 診断の項目に表示、主要がん種の後に表示される |
| 進行期 | figo | 進行期の項目に表示される |
| 初回治療日 | initial_treatment_date | 初回治療日の項目に表示、複数ある場合最も早いものが適用される |
| 診断日 | diagnosis_date | 診断日の検索に使用、複数ある場合最も早いものが適用される |
| 腫瘍登録番号 | registration_number | 腫瘍登録番号の有無として登録の表示に使用される |

お手数ですが、スキーマの該当箇所への対応をよろしくお願いいたします。

**Comment by kosaka-hokuto** [comment]
上記以外にもスキーマ名をハードコーディングしている部分があったため、そちらも同様にjesgo:tagで対応したいと思います。

| 名称 | tag_name | 概要 |
| -- | -- | -- |
| 再発属性 | recurrence | ステータスの項目に「再発」アイコンを表示、子ドキュメントに再発属性を持たせる |
| 手術療法アイコン | treatment_surgery | ステータスの項目に「手」アイコンを表示、再発属性でなければ初回治療の項目にも「手」アイコンを表示する
| 化学療法アイコン | treatment_chemo | ステータスの項目に「化」アイコンを表示、再発属性でなければ初回治療の項目にも「化」アイコンを表示する
| 放射線療法アイコン | treatment_radio | ステータスの項目に「放」アイコンを表示、再発属性でなければ初回治療の項目にも「放」アイコンを表示する
| 緩和療法アイコン | treatment_supportivecare | ステータスの項目に「緩和」アイコンを表示、再発属性でなければ初回治療の項目にも「緩和」アイコンを表示する
| 3年予後アイコン | three_year_prognosis | ステータスの項目、3年予後の項目に「3」アイコンを表示する(アイコン未受領)
| 5年予後アイコン | five_year_prognosis | ステータスの項目、5年予後の項目に「5」アイコンを表示する(アイコン未受領)

お手数ですが、スキーマの該当箇所への対応をよろしくお願いいたします。

**Comment by kosaka-hokuto** [comment]
上記タグのみでは腫瘍登録対象症例の管理が不可能であったため、腫瘍登録可否についても以下の様にタグを追加致しました。
また、その他いくつかのタグに関しても修正を行ったため、そちらも合わせて記載致します。
腫瘍登録対象症例に関しては[#72で最後にコメント](https://github.com/jesgo-toitu/jesgo-frontend/issues/72#issuecomment-1135614126)させていただいた仕様で実装しております。

| 名称 | tag_name | 概要 |
| -- | -- | -- |
| 腫瘍登録可否 | registrability | 腫瘍登録対象症例かどうかの確認に使用される、「はい」であれば登録対象症例とする |
| 【変更】腫瘍登録番号 | registration_number | 腫瘍登録番号の有無として登録の表示に使用される、腫瘍登録可否と同じドキュメントに設定する必要がある |
| 【変更】3年予後アイコン | three_year_prognosis | 該当項目が入力済であり、初回治療日から3年(3*365日)経過している場合、ステータスの項目、3年予後の項目に「済」アイコンを表示する |
| 【変更】5年予後アイコン | five_year_prognosis | 該当項目が入力済であり、初回治療日から5年(5*365日)経過している場合、ステータスの項目、5年予後の項目に「済」アイコンを表示する |

タグの記載位置ですが、「再発属性」以外のタグに関してはスキーマ内、プロパティの対象となる入力欄の項目に該当タグを指定します。
「再発属性」のタグは対象となるスキーマのバージョンなどと同列の部分にタグを指定します。
以下に例を記載しますのでご確認ください。
```
// 「再発属性」以外
□ CC/root.json
{
    "$schema": "../jesgo.json",
    "$id": "/schema/CC/root",
    "jesgo:version": "1.12",
    "type": "object",
    "title": "患者台帳 子宮頸がん",
    "$comment": "患者レコードの最上位に位置する基本情報.",
    "jesgo:unique": true,
    "jesgo:parentschema": [
        "/"
    ],
    "required": [
        "がん種"
    ],
    "properties": {
        "がん種": {
            "type": "string",
            "jesgo:tag": "cancer_major", // 入力欄に同タグを設定してください
            "jesgo:required": [
                "JSOG"
            ],
            "default": "子宮頸がん",
            "readOnly": true
        },
        ...
    },
    "jesgo:childschema": [
        "/schema/evaluations/cervix"
    ]
}
```

```
// 「再発属性」
□ common/recurrence.json
{
    "$schema": "../jesgo.json",
    "$id": "/schema/recurrence",
    "jesgo:tag":"recurrence", // スキーマのトップレベルにタグを指定してください
    "jesgo:version": "1.1",
    "type": "object",
    "title": "再発",
    "description": "再発診断に関わる所見情報も併せて設定して下さい.",
    "jesgo:parentschema": [
        "/"
    ],
    "required": [
        "再発確認日",
        "再発したがん種"
    ],
    ...
    "jesgo:childschema": [
        "/schema/treatment/relapse_treatment",
        "/schema/evaluation/*"
    ]
}
```

お手数をおかけしますが改めてスキーマの該当箇所への対応をよろしくお願いいたします。

**Comment by hsc-morita** [comment]
対応済み
