### ISSUE TITLE
【テスト】jesgo:unique false なドキュメントの追加

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#87]
指定がsubschemaの場合、追加が一回だけしかできない。これも複数できないとカンファレンス記録などが実装できない。

**Comment by hsc-morita** [comment]
申し訳ありません。jesgo:unique:falseのサブスキーマの対応については現在実装中となります。
β版では対応いたします。

**Comment by piyotaicho** [comment]
subschema だと複数存在しても削除・順番の変更ができませんね。一部はchildschemaでできるようちょっと上手いこと実装を考えます。

**Comment by hsc-morita** [comment]
jesgo:unique=falseが設定されているサブスキーマは以下のコメントの仕様に基づき実装しております。
https://github.com/jesgo-toitu/jesgo-frontend/issues/59#issuecomment-1128522129

並び替えは不可の仕様で実装しております。
同一サブスキーマが複数存在した場合は削除できるようにしているのですが、削除できないでしょうか？  
※GitHubにアップしたソースで確認してみましたが、私の環境では再現しておりません
作成したスキーマをいただければこちらでも確認いたします。

**Comment by piyotaicho** [comment]
作業中のスキーマですが #85 にいくつか機能しないところを修正中のものがありますので、そちらで経過をテストしてみてください。

**Comment by hsc-morita** [comment]
ありがとうございます。確認いたしました。
経過のサブスキーマである「経過・所見」が該当のスキーマかと存じますが再現いたしました。
コードの不備であることが判明いたしましたので、申し訳ありませんが来週火曜日を目途に更新いたします。
※スキーマの変更は不要です

なお、更新前にご自身でjesgo:unique=falseかつサブスキーマであるドキュメントの挙動を確認する場合は
お手数をお掛けしますが、以下を修正願います。

- 経過・所見のスキーマに「**"jesgo:unique": false**」を追加  
  ※修正版ではjesgo:unique未設定時のデフォルトをfalseにいたします
- スキーマアップロード後、DBのjesgo_document_schemaテーブル「経過」レコードにあるchild_schemaカラムから、subschemaと共通しているスキーマIDを削除
　※subschemaとchild_schemaに同一のIDが設定されていたため、誤作動しておりました
　※データの更新はpgAdmin等をご利用ください
