### ISSUE TITLE
schemaファイルについての確認事項

### ISSUE THREAD

**Issue by saso-hokuto** [jesgo-toitu/jesgo-frontend#9]
## 概要
2022/01/04にいただいたschemaファイル一式について、定義の意図やプロパティの意味について確認させていただきたいです。

### 全体
- `additionalProperties`の設定について
  - 主に`type:object`の項目、またはスキーマのルートに定義されているようですが、どのような意図で使用されているでしょうか。
    jsonSchemaとしては、`additionalProperties`は定義のない項目の追加可否を表現していると思いますが、今回のSchemaではユーザーが自由に項目追加できる仕様ではないため、どのようなイメージなのか確認したいです。

- HTML・MarkDown記法の使用
  - 選択肢の内容で、`<BR/>`や`<SUP>`タグが使用されているスキーマがいくつかありました。また、descriptionにMarkDown記法が使用されている箇所もあります。表示項目について、HTML（もしくはMarkdown）が反映されるようにしておく必要があるでしょうか？

### /schema/surveillance.json
- `死亡`について
  - if~thenで、`状態`で「死亡」に関連する項目を選択した時に、`死亡`チェックボックスの値がtrueになるよう定義しているかと思います。
    その際、`死亡`の項目は表示されますか？また、読み取り専用となるでしょうか？（`jesgo:hidden`を`jesgo:ui:hidden`と解釈しました）

### /schema/CC/staging.json
- `進行期分類の選択`のoneOf
  - oneOfの条件は、以下解釈で合っていますか？
    - `進行期分類の選択`で「手術により進行期を決定した症例」を選択
      - `進行期分類の選択`のdescriptionとして「術前に放射線治療や化学療法を施行した症例は～（略）」を表示
    - `進行期分類の選択`で「治療開始前に進行期を決定した症例」を選択
      - `進行期分類の選択`のdescriptionとして「根治的放射線療法、術前化学療法・術前放射線療法実施例など」を表示

- データ形式が複数パターンある場合
  - `T1a期の広がり`のように、oneOf内でtypeを定義しており、それらの種類が異なる場合（この場合はnumberとstring）のUIのイメージを確認したいです。
  　プロトタイプ版ではユーザーに入力形式を選択させ（この場合数値入力か選択入力か）、選択によって入力形式が異なるinputを表示するUIとしましたが、イメージ合っているでしょうか。

### /schema/EM/staging.json
- `ypTNM`のプロパティ
  - `ypTNM`内の`if~Then~else`で、elseの定義に以下記載がありますが、どのようなUIを意図していたでしょうか？
    また、`allOf`ではelseなしで同じ定義が記載されていますが、どちらが正でしょうか。
```
"else": {
    "type": "object",
    "additionalProperties": true
}
```

### /schema/evaluation/physical_status/performance_status.json
- `Examples`の扱い
  - ルート、および各項目内にexamplesとして値の例が書いてありますが、こちらは`$comment`などと同様、内部管理のための値であり、画面には表示されない、という解釈でよいでしょうか？

### /schema/treatment/chemotharapy.json
- `jesgo:ui:subschemastyle`の設定値について
  - `治療情報`で` "jesgo:ui:subschemastyle": "column"`の定義がありますが、`column`という設定値はないようです。（`row`,`noindent`,`inline`のみ）`column`の場合のUIイメージについてご教授いただければ幸いです。

**Comment by piyotaicho** [comment]
- additionalProperties  
JSON schema 2019の定義通りで、追加のプロパティを許可するか否かです。  
当初編集を開始した時点にはいちいち記載していたので残ってしまっていますがカスタマイズも前提としているため基本的には true で、ドキュメントのプロパティの追加については許可してよいと考えています。  
しかし、TMN分類などのかなりキモになる部分ではこれを許容するわけにはいかず残っています。が、これは（実際でも）かなり煩雑な問題なのでちょっと整理を考えます。 (staging.json全体にあたるのでとりあえず適当に実装しておいてください)
  
- surveillance.json  
死亡についてはチェックボックスでの入力では無く、非表示のプロパティ'死亡'を設定するものです。恐らく、この形だとpropertyの重複としてJSON parserで蹴られてしまうと思うのでif then elseに修正しておきます。  
本来は患者にテーブルに死亡のフラグを設定するものでしたが、テーブルとスキーマの定義に時系列ズレが生じていたので患者テーブルフィールドに死亡を設けていませんでしたね。死亡についていちいち検索が不要になるのでバックエンドの負担が減り、一覧表示が楽になるとは思うのですが、"jesgo:set" : "death" でデータベースの患者レコードに情報を保持するようにしますか？  

- oneOf について
  - 臨床進行期についてはご指摘の通りで、上のプロパティの値により続く入力内容が大きく変化します。なので、入力のたびに、JSONのvalidation→レンダリングが必要になります。
  - 一方で、プロパティのtypeが複数あるものについては、所謂(ドロップダウン)コンボボックスで、自由入力とリスト選択のどちらでも行えるものになります。
  - 同時に選択肢の構成で、選択肢のツリーに明示的改段を入れるためにも利用しています。

- $example, $comment
ご指摘の通り、スキーマを見る人以外関係ないものです。無視してください。  

- chemotherapy.json
この、columnはinlineでした。pushしておきます。

**Comment by saso-hokuto** [comment]
確認ありがとうございます。

- additionalProperties
扱いを整理いただけるとのこと、承知いたしました。よろしくお願いいたします。
ただ、開発側の都合で恐縮なのですが、使用しているUI自動生成ライブラリの仕様として、`additionalProperties`キーワードがあると、配列Widget（＋ボタンで複数追加可能なUI）が自動生成されてしまいます。
それを避けるため、`additionalProperties`ではなく、新たな拡張ボキャブラリーを作ってそちらで定義できると助かります。
このキーワードに限らず、ライブラリの都合上、JSON schema 2019には準拠できないケースが出てきます。それらについては、改めて課題を立てて確認させてください。

- surveillance.json
`死亡`というステータスを保持する意図だった旨、承知しました。年齢算出のissueでもあがった通り、患者レコードに死亡日を登録することで対応したいと思います。
今回のケースの場合、「状態」で死亡に関する項目が選択されていた場合、「確認日」を死亡日として登録、という扱いとします。

- oneOf について
  - 進行期分類の選択について、選択によって注釈も切り替えるということですね。承知しました。
  - プロパティのtypeが複数あるものについてもイメージ承知しました。
    それを踏まえて重ねて確認させてください。今回の`T1a期の広がり`でもそうなのですが、複数条件がある場合に、`units`の定義があるもの・ないものが混在していた場合、入力ボックス外の単位表示はどのようなイメージになりますか？
  - 「選択肢の構成で、選択肢のツリーに明示的改段を入れるため」にoneOfを使用しているケースですが、例えば、chemotherapy.jsonのdrugsなど、要素が{title:"XXX" type:string enum:["AAA","BBB"]}となっているケースが該当するでしょうか？

- $example, $comment
  - 画面表示には関係しない旨、承知しました。

- chemotherapy.json
  - columnはinlineとのこと、承知しました。

----------------

また、以下については引き続き確認をお待ちしております。項目が多く申し訳ありませんが、よろしくお願いいたします。
HTML・MarkDown記法の使用に関してですが、対応する場合、HTMLに統一する方向としたいです。
また、対応する場合はHTMLを直接画面に表示することになり、スキーマが外部から登録できる仕様上、XSSの可能性があるため、セキュリティ上の危険があります。
対応する場合は、β版以降の検討事項とさせていただきたいです。

### 全体
- HTML・MarkDown記法の使用
  - 選択肢の内容で、`<BR/>`や`<SUP>`タグが使用されているスキーマがいくつかありました。また、descriptionにMarkDown記法が使用されている箇所もあります。表示項目について、HTML（もしくはMarkdown）が反映されるようにしておく必要があるでしょうか？


### /schema/EM/staging.json
- `ypTNM`のプロパティ
  - `ypTNM`内の`if~Then~else`で、elseの定義に以下記載がありますが、どのようなUIを意図していたでしょうか？
    また、`allOf`ではelseなしで同じ定義が記載されていますが、どちらが正でしょうか。
```
"else": {
    "type": "object",
    "additionalProperties": true
}
```

**Comment by piyotaicho** [comment]
若手からの意見もあり、死亡ステータスの設定については、死亡に関する経過の継承スキーマを作成することになりそうです。

**Comment by piyotaicho** [comment]
"additionalProperties" は削除しておきます。

**Comment by saso-hokuto** [comment]
2022/03/10打ち合わせ結果

> HTML・MarkDown記法の使用
#10でもふれたとおり、以下とします。
- HTML表記の使用はdescriptionのみとし、対象タグは<br>,<sup>,<sub>とします。
- β版では少なくとも<br>については対応します。

**Comment by saso-hokuto** [comment]
一部残課題はありますが、別途課題を立てるため、こちらは一旦クローズとします。

関連
- #19 
- #21
