### ISSUE TITLE
エラーがあると保存されない？

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#90]
required なフィールドが入力されていない場合保存されない？

**Comment by piyotaicho** [comment]
エラーがあります
だけしか表示されないので保存されない旨を表示したほうが良いかもしれません。

subschemaでrequiredにするとなかなかえげつないので基本的になしにします。

**Comment by hsc-morita** [comment]
ご指摘ありがとうございます。承知いたしました。以下のメッセージに変更いたします。
```
症例ドキュメントに入力エラーがあるため保存できません。
エラー一覧を確認し、再度保存してください。
```

また、別件ですが子タブでエラーとなった場合にどこのタブでエラーになっているかわかりにくかったため
以下のようにパンくずリスト的に表示するよう改善いたします。
![image](https://user-images.githubusercontent.com/101262997/174265948-7841c897-e776-41bd-92ee-3e0becb6e528.png)

特にご指摘がなければ上記仕様にて来週更新いたします。

**Comment by piyotaicho** [comment]
現在、subschemaに指定されていても入力されなくてもよい部分に入力が無いとエラーになるので保存されないので結局なにも入力できないという神状態にあるので、 childschemaではなくsubschema相当にrequiredがあまり入らないようにスキーマを修正します。

**Comment by hsc-morita** [comment]
こちらのエラー表記の改善もdevelopmentに反映いたしました。
