### ISSUE TITLE
正規表現patternに合わない場合のvalidationの表現について

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#91]
@piyotaicho 
患者台帳 子宮頸がんの「腫瘍登録番号」など正規表現で入力形式のpatternが設定されているものがありますが
validationに引っかかった場合のメッセージ内容に正規表現がそのまま表示されており
ユーザに伝わりにくいものになっておりました。気が付かず申し訳ありません。
![image](https://user-images.githubusercontent.com/101262997/174551260-e162173c-4dd6-4bad-b97c-d2e6aedd8427.png)

そこで以下のように改善を検討しておりますがいかがでしょうか？
スキーマの修正も必要になります。
- メッセージ内容を「不正な入力形式です。？アイコンの記載例を参考に入力してください。」とする
- patternが設定されているプロパティに"description"を追加し、入力形式の説明を記載する

**Comment by piyotaicho** [comment]
ボキャブラリーの追加 jesgo:validationalert でも追加しましょう。

**Comment by hsc-morita** [comment]
ボキャブラリーの追加承知いたしました。以下の仕様といたします。
- validation対象の項目のスキーマに"jesgo:validationalert"を追加し、独自のメッセージを定義する
- "jesgo:validationalert"が未定義の場合はデフォルトのメッセージを表示する
- "jesgo:validationalert"はvalidationの対象となる項目すべてに対し定義できるものとする


#### 設定イメージ
```
"腫瘍登録番号": {
                "jesgo:required": [
                    "JSOG"
                ],
                "type": "string",
                "pattern": "^CC20[0-9]{2}-[1-9][0-9]*$",
                "jesgo:validationalert": "独自のvalidationメッセージ"
            },
```

**Comment by hsc-morita** [comment]
9/16状況
- 機能的には対応済み
- 現状のスキーマではjesgo:validationalert未使用
