### ISSUE TITLE
β版不具合情報

### ISSUE THREAD

**Issue by hsc-morita** [jesgo-toitu/jesgo-frontend#92]
## β版不具合情報
※随時更新
- [x] #91
- [x] 保存に失敗した場合、入力中のドキュメントの内容が保存前の内容に戻ってしまう
- [x] 登録拒否患者を表示する場合、本来「拒否」のアイコンが表示されるが「化」のアイコン(拒否アイコン未受領のため、仮アイコン)が表示されてしまう
- [x] 生年月日の範囲チェックが入っていない　→　Github反映済み
- [x] 保存時の確認ダイアログで「次回以降表示しない」にチェックする → いいえを選択した場合、その後のドキュメント追加時にタブが選択されない → Github反映済み
- [x] childSchemaドキュメントを2つ追加(保存しない)→1つ削除して保存すると2つとも消えてしまう → Github反映済み
- [x] プロパティがないスキーマのタブフォントが黒boldにならない → Github反映済み
	- [x] 上記対応で実施手術が未入力でもタブが強調されていたため修正
- [x] #79
- [x] 初回治療開始日が症例一覧に表示されない
- [x] 症例一覧の診断に患者台帳(その他)のがん種が表示されない(検索条件未対応)

**Comment by piyotaicho** [comment]
- [ ] TEXTAREAのX方向へのリサイズでレイアウトが崩れる。  
全体を通して問題が無ければCSSで textarea.form-control { resize: vertical; } としてもよいかと思います。
- [ ] プロパティ中のARRAYのタイトル部分が大きい。  
若手からも指摘されていましたが、ARRAYとなった場合legendのフォントサイズが1.3remと大きくなっています。  
これはドキュメント中のライブラリで生成されるスタイル指定で .form-group fieldset legend の中で設定されているようです。他の部分への影響もあるので悩ましいですがおいおい全体のスタイルシート調整とあわせて調整が必要です。おいおいやりましょう。試しに他の部分と同じく14pxにしてみましたが、まあ不都合は感じないです。

**Comment by piyotaicho** [comment]
```
        "手術時間": {
            "description": "加刀~終刀までの時間(分)",
            "oneOf": [
                {
                    "type": "integer",
                    "units": "分",
                    "minimum": 0
                },
                {
                    "type": "string",
                    "pattern": "^([1-9][0-9]?:)?[0-5]?[0-9]$"
                }
            ]
        },
```
の展開が
![image](https://user-images.githubusercontent.com/57445173/175363815-bbe0234a-b655-4da7-a3bb-91cb798ce023.png)
となる。333の由来は？

**Comment by piyotaicho** [comment]
- タブの強調表示
![image](https://user-images.githubusercontent.com/57445173/175364619-5b791d86-acd6-486f-97a8-4e994f4c4543.png)
サブスキーマのタブも OR で拾った方がわかりやすいと思います。
** とりあえず後 **

**Comment by piyotaicho** [comment]
数少ないrequiresプロパティですが、入力されていても赤くハイライト。
![image](https://user-images.githubusercontent.com/57445173/175452100-758fb5b5-1406-444f-b5b1-edcad383aa44.png)
これで仕様上は正しいのでしたっけ？

**Comment by hsc-morita** [comment]
要求仕様の以下の記述となります。
![image](https://user-images.githubusercontent.com/101262997/175453411-eeffbce9-6e5d-4861-978c-f19ec572b583.png)

入力されたらハイライトを消す動作は非対応となります。
ユーザビリティ的に消した方が望ましいとは思いますので、申し訳ありませんがStep2での対応とさせてください。

**Comment by piyotaicho** [comment]
承知いたしました。
