### ISSUE TITLE
【テスト】新規患者作成

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-frontend#96]
新規に患者を作成したときには、IDなどを入れるまでドキュメント作成ボタンをdisableしておいたほうが良かったですね。
なんで今までこんなことに気付かなかったのか。

**今後まとめてアップデート対応しましょう。**

**Comment by hsc-morita** [comment]
承知いたしました。
患者情報を保存するまで、ドキュメント作成ボタンはdisabledにすることを検討します。
またボタンが押せない理由が不明で戸惑うかと思いましたので、保存が必要であることをメッセージで表記するようにしたいと考えております。
【患者情報保存前(新規作成時)】
![image](https://user-images.githubusercontent.com/101262997/176105467-7eddef48-f2cc-42f9-b932-66efef0565ef.png)
【患者情報保存後(ドキュメント未作成)】
※ドキュメント作成済みの場合はメッセージ非表示
![image](https://user-images.githubusercontent.com/101262997/176105493-a14fae2b-5db1-401c-91f9-823683f7dce7.png)

この仕様でよろしいでしょうか？特にご指摘がなければこの仕様で対応いたします。

**Comment by hsc-morita** [comment]
対応済み
